"""
Asgard - Divine Oversight & Strategic Planning
=============================================

Realm of the Aesir gods—Odin's wisdom, Thor's command.
High-level vision and foresight.

Processes:
- Query decomposition and analysis
- Strategic planning and DAG generation
- Dependency mapping
- Confidence estimation
- Goal identification

This is where Huginn first reports to Odin with his observations.
"""

import logging
from typing import Dict, List, Any
from dataclasses import dataclass, field
from datetime import datetime

logger = logging.getLogger(__name__)


@dataclass
class StrategicPlan:
    """A strategic plan generated by Asgard."""
    goal: str
    branches: List[str]
    nodes: List[Dict[str, Any]]
    dependencies: Dict[str, List[str]]
    confidence: float
    estimated_complexity: int  # 1-10
    requires_llm: bool
    timestamp: datetime = field(default_factory=datetime.now)


class Asgard:
    """
    Divine Oversight & Strategic Planning.
    
    Handles:
    - Query intake and high-level decomposition
    - Strategic foresight for synergies across realms
    - Lightweight LLM-guided DAG outlining
    - Preliminary dependency mapping
    - Initial confidence estimation
    """
    
    # Keywords that indicate different processing strategies
    COMPLEXITY_KEYWORDS = {
        "high": ["complex", "analyze", "research", "comprehensive", "detailed", "multi"],
        "medium": ["explain", "describe", "calculate", "process", "compare"],
        "low": ["simple", "quick", "basic", "find", "check", "get"]
    }
    
    DECOMPOSITION_PATTERNS = {
        "sequential": ["then", "after", "next", "finally", "first"],
        "parallel": ["and", "also", "simultaneously", "both", "together"],
        "conditional": ["if", "when", "unless", "depending", "based on"]
    }
    
    def __init__(self, llm_queue=None):
        """
        Initialize Asgard.
        
        Args:
            llm_queue: Optional LLM queue for planning calls
        """
        self.llm_queue = llm_queue
        self._plan_cache: Dict[str, StrategicPlan] = {}
        self._plan_history: List[StrategicPlan] = []
    
    def decompose_query(self, query: str) -> Dict[str, Any]:
        """
        Decompose a query into core branches.
        
        Args:
            query: The input query
            
        Returns:
            Dict with branches and analysis
        """
        safe_query = (query or "").strip()[:1200]
        query_lower = safe_query.lower()
        words = query_lower.split()
        
        # Identify key action words
        actions = []
        subjects = []
        
        action_words = ["find", "get", "calculate", "analyze", "create", "generate",
                       "search", "retrieve", "process", "verify", "transform"]
        
        for word in words:
            if word in action_words:
                actions.append(word)
            elif len(word) > 4 and word not in ["about", "their", "would", "could"]:
                subjects.append(word)
        
        # Create branches based on structure
        branches = []
        
        if not actions:
            actions = ["process"]  # Default action
        
        for action in actions:
            for subject in subjects[:3]:  # Max 3 subjects per action
                branches.append(f"{action}_{subject}")
        
        if not branches:
            branches = [query_lower[:50].replace(" ", "_")]
        
        return {
            "original_query": query,
            "branches": branches[:5],  # Max 5 branches
            "actions": actions,
            "subjects": subjects,
            "word_count": len(words),
        }
    
    def outline_dag(self, query: str, decomposition: Dict = None) -> Dict[str, Any]:
        """
        Create a DAG outline for the query.
        
        Args:
            query: The input query
            decomposition: Optional pre-computed decomposition
            
        Returns:
            DAG structure with nodes and dependencies
        """
        if decomposition is None:
            decomposition = self.decompose_query(query)
        
        branches = decomposition.get("branches", [])
        
        # Build nodes
        nodes = []
        node_id = 0
        
        # Root planning node
        nodes.append({
            "id": f"node_{node_id}",
            "type": "plan",
            "realm": "asgard",
            "description": "Initial planning",
            "depends_on": []
        })
        node_id += 1
        
        # Branch nodes
        branch_node_ids = []
        for branch in branches:
            node = {
                "id": f"node_{node_id}",
                "type": "task",
                "realm": self._determine_realm_for_branch(branch),
                "description": branch,
                "depends_on": ["node_0"]  # Depends on planning
            }
            nodes.append(node)
            branch_node_ids.append(f"node_{node_id}")
            node_id += 1
        
        # Verification node
        nodes.append({
            "id": f"node_{node_id}",
            "type": "verify",
            "realm": "niflheim",
            "description": "Verify results",
            "depends_on": branch_node_ids
        })
        verify_node_id = f"node_{node_id}"
        node_id += 1
        
        # Assembly node
        nodes.append({
            "id": f"node_{node_id}",
            "type": "assemble",
            "realm": "midgard",
            "description": "Assemble final output",
            "depends_on": [verify_node_id]
        })
        
        return {
            "goal": query,
            "nodes": nodes,
            "total_nodes": len(nodes),
            "branch_count": len(branches),
        }
    
    def _determine_realm_for_branch(self, branch: str) -> str:
        """Determine which realm should handle a branch."""
        branch_lower = branch.lower()
        
        if any(kw in branch_lower for kw in ["calculate", "compute", "math", "data"]):
            return "jotunheim"
        elif any(kw in branch_lower for kw in ["find", "search", "retrieve", "memory"]):
            return "helheim"
        elif any(kw in branch_lower for kw in ["create", "generate", "forge", "build"]):
            return "svartalfheim"
        elif any(kw in branch_lower for kw in ["verify", "check", "validate"]):
            return "niflheim"
        elif any(kw in branch_lower for kw in ["transform", "convert", "refine"]):
            return "muspelheim"
        else:
            return "jotunheim"  # Default to execution
    
    def map_dependencies(self, nodes: List[Dict]) -> Dict[str, List[str]]:
        """
        Create a dependency map from nodes.
        
        Args:
            nodes: List of node dictionaries
            
        Returns:
            Dict mapping node IDs to their dependencies
        """
        dep_map = {}
        
        for node in nodes:
            node_id = node.get("id", "unknown")
            deps = node.get("depends_on", [])
            dep_map[node_id] = deps
        
        return dep_map
    
    def estimate_confidence(self, query: str, decomposition: Dict = None) -> float:
        """
        Estimate confidence in the decomposition.
        
        Args:
            query: The input query
            decomposition: Optional pre-computed decomposition
            
        Returns:
            Confidence score 0.0 to 1.0
        """
        if decomposition is None:
            decomposition = self.decompose_query(query)
        
        # Base confidence
        confidence = 0.5
        
        # Adjust based on decomposition quality
        branches = decomposition.get("branches", [])
        
        if len(branches) >= 2:
            confidence += 0.1
        if len(branches) >= 3:
            confidence += 0.1
        
        # Adjust based on action clarity
        actions = decomposition.get("actions", [])
        if actions:
            confidence += 0.1
        
        # Adjust based on subject identification
        subjects = decomposition.get("subjects", [])
        if len(subjects) >= 2:
            confidence += 0.1
        
        if decomposition.get("word_count", 0) > 25:
            confidence -= 0.05

        return max(0.1, min(1.0, confidence))
    
    def estimate_complexity(self, query: str) -> int:
        """
        Estimate task complexity on scale 1-10.
        
        Args:
            query: The input query
            
        Returns:
            Complexity score 1-10
        """
        query_lower = (query or "").lower()
        
        score = 4

        # Check for high complexity indicators
        for kw in self.COMPLEXITY_KEYWORDS["high"]:
            if kw in query_lower:
                score += 3

        # Check for medium complexity
        for kw in self.COMPLEXITY_KEYWORDS["medium"]:
            if kw in query_lower:
                score += 1

        # Check for low complexity
        for kw in self.COMPLEXITY_KEYWORDS["low"]:
            if kw in query_lower:
                score -= 2

        score += min(2, max(0, len(query_lower.split()) // 20))
        return max(1, min(10, score))
    
    def requires_llm(self, query: str) -> bool:
        """
        Determine if query requires LLM processing.
        
        Args:
            query: The input query
            
        Returns:
            True if LLM needed
        """
        llm_indicators = [
            "explain", "describe", "why", "how", "what do you think",
            "analyze", "interpret", "creative", "write", "generate text",
            "summarize", "compare", "recommend"
        ]
        
        query_lower = (query or "").lower()
        return any(ind in query_lower for ind in llm_indicators)
    
    def create_strategic_plan(self, query: str) -> StrategicPlan:
        """
        Create a complete strategic plan for a query.
        
        Args:
            query: The input query
            
        Returns:
            StrategicPlan object
        """
        # Check cache
        safe_query = (query or "").strip()
        cache_key = safe_query
        if cache_key in self._plan_cache:
            return self._plan_cache[cache_key]
        
        # Decompose
        decomposition = self.decompose_query(safe_query)
        
        # Create DAG outline
        dag = self.outline_dag(safe_query, decomposition)
        
        # Map dependencies
        dependencies = self.map_dependencies(dag["nodes"])
        
        # Estimates
        confidence = self.estimate_confidence(safe_query, decomposition)
        complexity = self.estimate_complexity(safe_query)
        needs_llm = self.requires_llm(safe_query)
        
        plan = StrategicPlan(
            goal=safe_query,
            branches=decomposition["branches"],
            nodes=dag["nodes"],
            dependencies=dependencies,
            confidence=confidence,
            estimated_complexity=complexity,
            requires_llm=needs_llm,
        )
        
        # Cache and record
        self._plan_cache[cache_key] = plan
        self._plan_history.append(plan)
        
        # Trim history
        if len(self._plan_history) > 100:
            self._plan_history = self._plan_history[-50:]
        
        logger.info(f"Asgard created plan: {len(plan.nodes)} nodes, "
                   f"confidence={confidence:.2f}, complexity={complexity}")
        
        return plan
    
    def divine_foresight(self, query: str, context: Dict = None) -> Dict[str, Any]:
        """
        Odin's foresight - analyze and predict best approach.
        
        Args:
            query: The input query
            context: Additional context
            
        Returns:
            Foresight analysis
        """
        context = context or {}
        
        plan = self.create_strategic_plan(query)
        
        # Predict potential issues
        potential_issues = []
        
        if plan.estimated_complexity > 7:
            potential_issues.append("High complexity - may need multiple iterations")
        
        if plan.requires_llm and not self.llm_queue:
            potential_issues.append("LLM required but queue not available")
        
        if len(plan.branches) > 4:
            potential_issues.append("Many branches - consider parallelization")
        
        # Predict resource needs
        resource_needs = {
            "llm_calls": len([n for n in plan.nodes if n.get("type") == "llm"]) + (1 if plan.requires_llm else 0),
            "python_tasks": len([n for n in plan.nodes if n.get("type") in ["task", "compute"]]),
            "verifications": len([n for n in plan.nodes if n.get("type") == "verify"]),
        }
        
        return {
            "plan": plan,
            "foresight": {
                "success_probability": plan.confidence,
                "estimated_steps": len(plan.nodes),
                "parallel_potential": len(plan.branches) > 1,
                "potential_issues": potential_issues,
                "resource_needs": resource_needs,
            },
            "recommendation": self._recommend_approach(plan),
        }
    
    def _recommend_approach(self, plan: StrategicPlan) -> str:
        """Generate recommendation based on plan."""
        if plan.estimated_complexity <= 3:
            return "Simple task - direct execution recommended"
        elif plan.estimated_complexity <= 6:
            return "Moderate task - standard DAG execution"
        else:
            return "Complex task - consider iterative refinement with Muspelheim critique"
    
    def get_plan_history(self, limit: int = 10) -> List[Dict]:
        """Get recent plan summaries."""
        return [
            {
                "goal": p.goal[:50],
                "branches": len(p.branches),
                "nodes": len(p.nodes),
                "confidence": p.confidence,
                "complexity": p.estimated_complexity,
                "timestamp": p.timestamp.isoformat(),
            }
            for p in self._plan_history[-limit:]
        ]
