import os
from pathlib import Path

_KNOWLEDGE_REF = (
    Path(__file__).resolve().parent.parent
    / "viking_girlfriend_skill" / "data" / "knowledge_reference"
)
file_path = _KNOWLEDGE_REF / "SOFTWARE_ENGINEERING.md"

entries = [
    "**Recursion**: A method of solving a problem where the solution depends on solutions to smaller instances of the same problem.",
    "**Memoization**: An optimization technique used primarily to speed up computer programs by storing the results of expensive function calls.",
    "**Big O Notation**: A mathematical notation that describes the limiting behavior of a function when the argument tends towards a particular value or infinity.",
    "**Time Complexity**: The computational complexity that describes the amount of computer time it takes to run an algorithm.",
    "**Space Complexity**: The amount of memory space required by the algorithm in its life cycle.",
    "**Arrays**: A data structure consisting of a collection of elements, each identified by at least one array index or key.",
    "**Linked Lists**: A linear collection of data elements whose order is not given by their physical placement in memory.",
    "**Stacks (Data Structure)**: A collection of elements that supports two principal operations: push and pop (LIFO).",
    "**Queues (Data Structure)**: A collection of elements that supports two principal operations: enqueue and dequeue (FIFO).",
    "**Hash Tables**: A data structure that implements an associative array abstract data type, a structure that can map keys to values.",
    "**Binary Search Tree (BST)**: A rooted binary tree data structure whose internal nodes each store a key greater than all the keys in the node's left subtree and less than those in its right subtree.",
    "**AVL Trees**: A self-balancing binary search tree.",
    "**Red-Black Trees**: Another type of self-balancing binary search tree.",
    "**B-Trees**: A self-balancing tree data structure that maintains sorted data and allows searches, sequential access, insertions, and deletions in logarithmic time.",
    "**Graphs (Data Structure)**: An abstract functional representation that consists of a set of vertices and a set of edges that establish relationships between the vertices.",
    "**Tries (Prefix Tree)**: A type of search tree, an ordered tree data structure used to store a dynamic set or associative array where the keys are usually strings.",
    "**Heaps (Data Structure)**: A specialized tree-based data structure which is an almost complete tree that satisfies the heap property.",
    "**Bloom Filters**: A space-efficient probabilistic data structure used to test whether an element is a member of a set.",
    "**Depth-First Search (DFS)**: An algorithm for traversing or searching tree or graph data structures.",
    "**Breadth-First Search (BFS)**: An algorithm for searching a tree data structure that explores all of the neighbor nodes at the present depth prior to moving on to the nodes at the next depth level.",
    "**Dijkstra's Algorithm**: An algorithm for finding the shortest paths between nodes in a graph.",
    "**A* Search Algorithm**: A graph traversal and path search algorithm, which is often used in many fields of computer science due to its completeness, optimality, and optimal efficiency.",
    "**Dynamic Programming**: A method for solving a complex problem by breaking it down into a collection of simpler subproblems.",
    "**Greedy Algorithms**: An algorithmic paradigm that follows the problem-solving heuristic of making the locally optimal choice at each stage.",
    "**Divide and Conquer**: An algorithm design paradigm based on multi-branched recursion.",
    "**Backtracking**: A general algorithm for finding all (or some) solutions to some computational problems, notably constraint satisfaction problems.",
    "**Bit Manipulation**: The act of algorithmically manipulating bits or other pieces of data shorter than a word.",
    "**Regular Expressions (Regex)**: A sequence of characters that specifies a search pattern in text.",
    "**Compilers**: A computer program that translates computer code written in one programming language into another language.",
    "**Interpreters**: A computer program that directly executes instructions written in a programming or scripting language.",
    "**Transpilers**: A type of compiler that takes the source code of a programming language as its input and outputs the source code into another programming language.",
    "**Garbage Collection Algorithms**: Mark-and-sweep, reference counting, generational, etc.",
    "**Virtual Machine (VM)**: An emulation of a computer system.",
    "**Bytecode**: Computer object code that is processed by a program, usually referred to as a virtual machine, rather than by the \"real\" computer machine.",
    "**Just-In-Time (JIT) Compilation**: A way of executing computer code that involves compilation during execution of a program at run time.",
    "**Static Typing**: The process of verifying the type safety of a program based on analysis of a program's text.",
    "**Dynamic Typing**: The process of verifying the type safety of a program at runtime.",
    "**Strong Typing**: A language in which one can only perform operations which are defined for the type.",
    "**Weak Typing**: A language in which types can be ignored or implicitly converted.",
    "**Polymorphism**: The provision of a single interface to entities of different types.",
    "**Encapsulation**: The bundling of data with the methods that operate on that data.",
    "**Inheritance**: A mechanism where a new class is derived from an existing class.",
    "**Abstraction**: The process of removing physical, spatial, or temporal details or attributes in the study of objects or systems to focus attention on details of greater importance.",
    "**Composition over Inheritance**: A principle in object-oriented programming that states that classes should achieve polymorphic behavior and code reuse by their composition.",
    "**Lazy Loading**: A design pattern commonly used in computer programming to defer initialization of an object until the point at which it is needed.",
    "**Eager Loading**: The opposite of lazy loading, where data is loaded immediately.",
    "**Throttling**: The process of limiting the number of times a function can be called over a certain period.",
    "**Debouncing**: A technique used to ensure that time-consuming tasks do not fire so often, by waiting for a pause in the calls.",
    "**Event Loop**: A programming construct or design pattern that waits for and dispatches events or messages in a program.",
    "**Promises**: An object representing the eventual completion (or failure) of an asynchronous operation and its resulting value.",
    "**Async/Await**: A syntactic sugar in programming for working with asynchronous functions.",
    "**Callbacks**: A piece of executable code that is passed as an argument to other code.",
    "**Higher-Order Functions**: A function that does at least one of the following: takes one or more functions as arguments, returns a function as its result.",
    "**Closures**: A record storing a function together with an environment.",
    "**Immutability**: An object whose state cannot be modified after it is created.",
    "**Pure Functions**: A function where the return value is determined only by its input values, without observable side effects.",
    "**Side Effects**: Any observable change in the state of the program or environment caused by a function.",
    "**Currying**: The technique of transforming a function that takes multiple arguments into a sequence of functions that each take a single argument.",
    "**Monads**: A design pattern used to describe computations as a series of steps.",
    "**Domain-Driven Design (DDD)**: An approach to software development for complex needs by connecting the implementation to an evolving model.",
    "**Bounded Contexts**: A central pattern in Domain-Driven Design that defines where a particular model is defined and applied.",
    "**Service Locator Pattern**: A design pattern used in software development to encapsulate the processes involved in obtaining a service with a strong abstraction layer.",
    "**Dependency Injection (DI)**: A technique in which an object receives other objects that it depends on.",
    "**IoC (Inversion of Control) Container**: A framework for implementing automatic dependency injection.",
    "**Middleware**: Software that provides common services and capabilities to applications outside of what's offered by the operating system.",
    "**Proxy Servers**: A server that acts as an intermediary for requests from clients seeking resources from other servers.",
    "**Reverse Proxy**: A type of proxy server that retrieves resources on behalf of a client from one or more servers.",
    "**Load Balancing**: The process of distributing network traffic across multiple servers.",
    "**Caching Strategies**: Cache-aside, read-through, write-through, write-back, etc.",
    "**CDN (Content Delivery Network)**: A geographically distributed network of proxy servers and their data centers.",
    "**DNS (Domain Name System)**: The phonebook of the Internet.",
    "**HTTP/HTTPS**: Hypertext Transfer Protocol (Secure).",
    "**WebSockets**: A computer communications protocol providing full-duplex communication channels over a single TCP connection.",
    "**TCP/IP Stack**: The set of communications protocols used for the Internet and other similar networks.",
    "**UDP (User Datagram Protocol)**: A communications protocol used across the Internet for especially time-sensitive transmissions.",
    "**SQL Injection**: A code injection technique that might destroy your database.",
    "**XSS (Cross-Site Scripting)**: A type of vulnerability in which an attacker injects malicious scripts into content from otherwise trusted websites.",
    "**CSRF (Cross-Site Request Forgery)**: An attack that forces an authenticated user to execute unwanted actions on a web application in which they are currently authenticated.",
    "**Encryption at Rest**: Securely storing data on a persistent device.",
    "**Encryption in Transit**: Protecting data as it moves between locations.",
    "**Symmetric Encryption**: Encryption that uses the same key for both encryption and decryption.",
    "**Asymmetric Encryption**: Encryption that uses two different keys (public and private).",
    "**Hashing**: The process of converting an arbitrary amount of data into a fixed-size value.",
    "**Salting**: Adding random data to the input of a hash function to guarantee a unique output.",
    "**OAuth 2.0 Flows**: Authorization Code, Implicit, Resource Owner Password Credentials, Client Credentials.",
    "**OpenID Connect (OIDC)**: An identity layer on top of the OAuth 2.0 protocol.",
    "**SAML (Security Assertion Markup Language)**: An open standard for exchanging authentication and authorization data between parties.",
    "**Zero Trust Architecture**: A security model that requires all users to be authenticated, authorized, and continuously validated.",
    "**Threat Modeling**: A process by which potential threats can be identified and enumerated.",
    "**Vulnerability Scanning**: The automated process of identifying security vulnerabilities in a system.",
    "**Penetration Testing**: A simulated cyberattack against your computer system to check for exploitable vulnerabilities.",
    "**Logging & Monitoring**: The process of recording events and observing the status of a system.",
    "**分布式系统 (Distributed Systems)**: A system whose components are located on different networked computers.",
    "**CAP Theorem**: Consistency, Availability, Partition tolerance - a database can only provide two out of three.",
    "**Eventual Consistency**: A theoretical basis for distributed systems where data will eventually become consistent.",
    "**Strong Consistency**: A model where every read receives the most recent write or an error.",
    "**Quorum**: The minimum number of votes that a distributed transaction must obtain in order to be allowed to perform an operation.",
    "**Raft Consensus Algorithm**: A consensus algorithm that is designed to be easy to understand.",
    "**Paxos Algorithm**: A family of protocols for solving consensus in a network of unreliable processors.",
    "**Sharding**: A type of database partitioning that separates very large databases into smaller, faster, more easily managed parts called data shards."
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 101 - 200\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+101}. {entry}\n")
