import os

file_path = r"c:\Users\volma\anti-gravity-githublocal-NorseSaga-Engine\Viking_girlfriend_openclaw_skill\viking_girlfriend_skill\data\knowledge_reference\CYBERSECURITY.md"

entries = [
    "**Offensive Security (The Raiders' Tactics)**: A security approach that proactively seeks to find and exploit vulnerabilities in a system or network.",
    "**Ethical Hacking (The Honorable Duel)**: The practice of testing a system's security with the owner's permission to find and fix vulnerabilities.",
    "**Penetration Testing (Pen Testing) (The Siege of the Stronghold)**: A simulated cyberattack designed to evaluate the security of a computer system.",
    "**Reconnaissance (The Scout's Work)**: The phase of an attack where information is gathered about the target.",
    "**Passive Reconnaissance (The Silent Watcher)**: Gathering information without directly interacting with the target (e.g., searching public records).",
    "**Active Reconnaissance (The Probing Strike)**: Gathering information by directly interacting with the target (e.g., port scanning).",
    "**Footprinting (Mapping the Realm)**: The process of creating a blueprint or map of an organization's network and systems.",
    "**OSINT (Open Source Intelligence) (The Wisdom of the Public Realm)**: Information collected from public sources like social media, public records, and websites.",
    "**Social Engineering (The Trickster's Tongue)**: Manipulating people into giving up secrets or performing actions.",
    "**Phishing (The Bait of the False Messenger)**: Using fake emails to trick victims into clicking links or providing data.",
    "**Spear Phishing (The Targeted Javelin)**: A highly personalized phishing attack aimed at a specific person.",
    "**Whaling (Hunting the High-Jarls)**: Phishing aimed at senior executives (CEOs, CFOs).",
    "**Vishing/Smishing (Voice/SMS Phishing)**: Using phone calls or texts for phishing.",
    "**Pretexting (The False Saga)**: Creating a fake scenario to gain trust (e.g., 'I'm from IT calling about your account').",
    "**Baiting (The Cursed Treasure)**: Leaving a malicious USB drive for someone to find and plug in.",
    "**Quid Pro Quo (The Unequal Trade)**: Offering a fake service (e.g., 'free tech support') in exchange for login details.",
    "**Tailgating (The Shadow-Walker)**: Following an authorized person into a secure building without their knowledge.",
    "**Piggybacking (The Known Guest)**: An authorized person knowingly letting an unauthorized person follow them in.",
    "**Watering Hole Attack (The Poisoned Oasis)**: Infecting a website that a specific group of targets is known to visit.",
    "**Weaponization (Forging the Rune-Blade)**: The phase where an exploit is combined with a malicious payload (e.g., a PDF with a hidden virus).",
    "**Delivery (The Launch of the Raid)**: Sending the weaponized file to the target (via email, web, or USB).",
    "**Exploitation (The Strike at the Weakness)**: The moment the malicious code is triggered on the target's system.",
    "**Installation (The Hidden Settlement)**: The phase where the malware installs itself and ensures it survives a reboot.",
    "**Persistence (The Eternal Watch)**: Techniques used by attackers to stay in a system even after a restart (e.g., registry keys, scheduled tasks).",
    "**Command and Control (C2/C&C) (The Signal of the Raven)**: The infrastructure used by attackers to remotely control compromised systems.",
    "**Beacons (The Rhythmic Call)**: Periodic signals sent by malware to its C2 server to check for new commands.",
    "**Actions on Objectives (The Final Raid Task)**: The phase where the attacker achieves their goal (e.g., stealing gold/data, destroying systems).",
    "**Data Exfiltration (The Looting of the Hall)**: Moving stolen data out of the target network to the attacker's server.",
    "**Staging Area (The Treasure-Hold)**: A temporary location where stolen data is collected before being exfiltrated.",
    "**Enumeration (Counting the Enemy's Strength)**: The process of finding specific users, groups, shared folders, and services on a target system.",
    "**Network Scanning (The Search for the Shore-Path)**: Using tools to find live hosts and open ports on a network.",
    "**Banner Grabbing (Reading the Ship's Name)**: Connecting to a service to see its version and software name (e.g., 'Apache 2.4.41').",
    "**Vulnerability Scanning (The Hunt for Chinks)**: Using automated tools to find known security flaws.",
    "**Nessus / OpenVAS (The Watchers for Decay)**: Popular vulnerability scanners.",
    "**Port Scanning (Knocking on Every Door)**: Checking which network ports (like 80, 443, 22) are open on a server.",
    "**TCP Connect Scan (The Full Handshake)**: A scan that completes a full 3-step handshake to check if a port is open.",
    "**SYN Stealth Scan (The Half-Open Raid)**: A scan that only sends the first part of the handshake to be less visible.",
    "**UDP Scan (The Silent Strike)**: Checking for open UDP services (which are harder to detect).",
    "**Xmas Scan (The Lit-Up Ship)**: A scan that sets 'FIN', 'PSH', and 'URG' flags to see how a server reacts.",
    "**Zombie Scan / Idle Scan**: Using a third-party 'zombie' computer to scan a target without revealing your own IP.",
    "**Service Discovery (Locating the Hidden Clans)**: Identifying what software is running on an open port.",
    "**OS Fingerprinting (Identifying the Realm)**: Guessing the operating system (Windows, Linux, macOS) based on its network behavior.",
    "**Nmap NSE (Nmap Scripting Engine)**: A powerful part of Nmap that allows for automated vulnerability detection and exploitation.",
    "**Exploit Development (Weapon-Smithing)**: The art of writing code that takes advantage of a software bug.",
    "**Shellcode (The Language of the Machine)**: A small piece of code used as a payload to give an attacker a 'shell' (command prompt) on a system.",
    "**Buffer Overflow (The Flood of the Meadhall)**: Sending too much data to a program so it overflows its memory and runs the attacker's code.",
    "**Stack Overflow (Memory)**: Overwriting the stack memory, often used to change the 'return address' of a function.",
    "**Heap Overflow (Memory)**: Overwriting the heap memory, harder to exploit but very powerful.",
    "**Integer Overflow (The Calculation Mistake)**: Exploiting how computers handle very large numbers to cause a crash or logic error.",
    "**NOP Sled (The Path for the Blade)**: A series of 'No-Operation' instructions that lead the computer's execution to the attacker's shellcode.",
    "**ASLR (Address Space Layout Randomization)**: A defense that moves code around in memory to make it harder to find.",
    "**DEP (Data Execution Prevention) / NX (No-Execute)**: A defense that prevents code from running in memory areas meant for data.",
    "**ROP (Return-Oriented Programming)**: A technique to bypass DEP by using small snippets of existing, legitimate code (gadgets).",
    "**Canary (Stack Protection) (The Bird in the Mine)**: A small value placed on the stack that, if changed, indicates an attack has happened and stops the program.",
    "**Fuzzing (The Testing of Chaos)**: Sending massive amounts of random data to a program to find crashes and bugs.",
    "**Black-Box Fuzzing**: Fuzzing without knowing how the software works internally.",
    "**White-Box Fuzzing**: Fuzzing with access to the source code to find hidden paths.",
    "**Vulnerability Research (The Search for the Hidden Path)**: Investigating software to find new, unknown bugs (Zero-Days).",
    "**Zero-Day Vulnerability (The Unknown Blow)**: A bug that is unknown to the software creator and has no patch.",
    "**Metasploit Framework (The Raider's Armory)**: The world's most used penetration testing tool for finding and exploiting vulnerabilities.",
    "**Payload (The Hidden Blade inside the Vessel)**: The malicious code that runs after an exploit succeeds.",
    "**Meterpreter (The Master-Key Shell)**: An advanced, extensible payload that provides deep control over a compromised system.",
    "**Bind Shell (The Open Door)**: A shell that waits for the attacker to connect to it (often blocked by firewalls).",
    "**Reverse Shell (The Call-Back)**: A shell that 'calls back' to the attacker's computer (usually bypasses firewalls).",
    "**Post-Exploitation (The Sacking of the Hall)**: The phase after an attacker has gained access and is looking for more treasure.",
    "**Privilege Escalation (Claiming the High-Seat)**: Moving from a low-level user account to a high-level one (like 'Root' or 'Administrator').",
    "**Vertical Privilege Escalation**: Gaining more power (e.g., User -> Admin).",
    "**Horizontal Privilege Escalation**: Gaining the same power but for a different user (e.g., User A -> User B).",
    "**Dumping Credentials (The Theft of Keys)**: Stealing usernames and passwords from a system's memory or files.",
    "**Mimikatz (The Key-Stealer)**: A famous tool used to steal passwords and 'hashes' from Windows memory.",
    "**Pass-the-Hash (PtH) (The Phantom Key)**: Using a password hash instead of the cleartext password to log in to other systems.",
    "**Pass-the-Ticket (PtT)**: Using a Kerberos 'ticket' to impersonate a user on a network.",
    "**Pivoting (The Bridge between Islands)**: Using one compromised computer to attack other computers deeper in a network.",
    "**Lateral Movement (Moving within the Walls)**: Navigating through a network from one system to another to find the target.",
    "**Port Forwarding (The Secret Tunnel)**: Redirecting network traffic through a compromised host to reach hidden services.",
    "**Web Application Hacking (Sieging the Digital Longship)**: Attacking the websites and APIs that power the modern world.",
    "**Burp Suite (The Watcher of the Web-Ways)**: The essential tool for intercepting and modifying web traffic for testing.",
    "**OWASP ZAP (The Free Shield-Breaker)**: An open-source alternative to Burp Suite for web hacking.",
    "**SQL Injection (SQLi) (Poisoning the Scribe)**: Trapping a database by sending malicious commands through a website's input field.",
    "**Blind SQL Injection**: An attack where the database doesn't show errors, but the attacker 'asks' it questions that result in true/false answers (e.g., timing differences).",
    "**Cross-Site Scripting (XSS) (The Cursed Script)**: Injecting malicious JavaScript into a website so that it runs in the browsers of other users.",
    "**Stored XSS (The Trap in the Hall)**: Malicious code is saved on the server (like in a comment) and attacks everyone who reads it.",
    "**Reflected XSS (The Mirror-Trap)**: Malicious code is in a link that, when clicked, is 'reflected' back and run in the victim's browser.",
    "**DOM-based XSS (The Local Trap)**: The attack happens entirely in the browser's memory without touching the server.",
    "**Cross-Site Request Forgery (CSRF) (The Hijacked Hand)**: Tricking a logged-in user into unknowingly performing an action (like changing their password or sending gold).",
    "**IDOR (Insecure Direct Object Reference) (Guessing the Key)**: Accessing someone else's data by simply changing an ID in a URL (e.g., `user/101` -> `user/102`).",
    "**XXE (XML External Entity) (The Poisoned Scroll)**: Attacking a server that reads XML files by forcing it to read local sensitive files or attack other servers.",
    "**Insecure Deserialization (The Rotten Reassembly)**: Attacking a system that takes data (objects) and rebuilds them without checking if they are malicious.",
    "**Directory Traversal (The Path out of the Hall)**: Using `../` to move out of the intended web folder and read secret system files like `/etc/passwd`.",
    "**Local File Inclusion (LFI)**: Forcing a website to show a file that is already on the server.",
    "**Remote File Inclusion (RFI)**: Forcing a website to load and run a file from the attacker's external server.",
    "**Command Injection (The Rune-Command Override)**: Forcing a web server to run operating system commands directly.",
    "**SSRF (Server-Side Request Forgery) (The Proxy Trap)**: Tricking a server into making requests to internal services that are normally hidden from the public.",
    "**Broken Authentication (The Faulty Gate)**: Exploiting weak passwords, lack of MFA, or flawed session management to steal accounts.",
    "**Session Hijacking (Stealing the Vessel's Flag)**: Stealing a user's 'session cookie' to take over their logged-in account.",
    "**Session Fixation (The Predetermined Flag)**: Forcing a user to use a session ID that the attacker already knows.",
    "**Clickjacking (The Invisible Overlay)**: Putting an invisible button over a real one to trick a user into clicking something else.",
    "**Subdomain Takeover (Seizing the Abandoned Isle)**: Claiming a forgotten subdomain (like `dev.example.com`) that still points to an old service an attacker can control.",
    "**API Hacking (The Direct Siege of Knowledge)**: Looking for weaknesses in the APIs (REST, GraphQL, gRPC) that connect different systems.",
    "**BOLA (Broken Object Level Authorization)**: The API version of IDOR, and the #1 API security risk.",
    "**Mass Assignment (The Over-Filled Cargo)**: Tricking an API into changing data it shouldn't (e.g., setting `is_admin=true` when updating a profile).",
    "**JWT (JSON Web Token) (The Digital Passport)**: A popular way of handling authentication, but often vulnerable to 'None' algorithms or secret-key cracking.",
    "**Cloud Security Hacking (Sieging the Sky-Citadel)**: Attacking infrastructure on AWS, Azure, and Google Cloud.",
    "**S3 Bucket Misconfiguration (The Unlocked Warehouse)**: Leaving cloud storage folders public so anyone can download secret data.",
    "**IMDS (Instance Metadata Service) (The Server's Secret Oracle)**: Attacking a cloud server's local metadata to steal AWS/Azure IAM roles and keys.",
    "**Subdomain Takeover in Cloud**: Seizing DNS records that point to dead cloud resources.",
    "**Cloud Credentials Theft**: Stealing `.aws/credentials` or other local cloud keys to gain control of an entire cloud account.",
    "**Lambda / Serverless Hacking (The Fragmented Siege)**: Exploiting micro-services that run without a traditional server.",
    "**Docker Container Hacking (Breaking the Sealed Cask)**: Escaping from a container to gain control of the 'Host' machine.",
    "**Kubernetes (K8s) Hacking (Sieging the Fleet)**: Attacking the orchestration layer to gain control over many clusters of containers.",
    "**The Shadow Cloud (Shadow IT)**: Hidden cloud accounts or resources used by employees without the company knowing, often lacking security.",
    "**Red Teaming (The Full-Scale War Game)**: An advanced security test where the 'attackers' try to achieve a specific goal (like stealing a secret file) using any means necessary (hacking, social engineering, physical entry).",
    "**Blue Teaming (The Shield-Wall)**: The defensive half of a war game, focused on detecting and stopping the 'Red Team'.",
    "**Purple Teaming (The Shared Wisdom)**: When Red and Blue teams work together to improve security through open communication.",
    "**Adversary Emulation (Mimicking the Shadow-Kingdom)**: Using the exact same tools and tactics (TTPs) as a real-world threat group (like APT28).",
    "**MITRE ATT&CK Framework (The Almanac of Raiders)**: A massive database of every known tactic and technique used by real cyber raiders.",
    "**Tactics (The Goal of the Raid)**: What the attacker is trying to achieve (e.g., 'Initial Access', 'Exfiltration').",
    "**Techniques (The Method of the Raid)**: How they achieve the goal (e.g., 'Phishing', 'PowerShell').",
    "**Procedures (The Specific Instruction)**: The exact command or software used.",
    "**Cyber Kill Chain (The 7 Stages of the Siege)**: A 7-step model for how a targeted attack progresses.",
    "**Indicators of Compromise (IoC) (The Tracks of the Raider)**: Clues left behind by an attacker, like a specific IP address or file hash.",
    "**Indicators of Attack (IoA) (The Signs of the Siege)**: Behavioral clues that show an attack is happening RIGHT NOW.",
    "**Threat Hunting (The Proactive Hunt in the Wilds)**: Searching through logs to find attackers who have already broken in but are staying hidden.",
    "**SIEM (Security Information and Event Management) (The Great Watchtower)**: A tool that collects and analyzes logs from every part of the network.",
    "**SOAR (Security Orchestration, Automation, and Response)**: Using automation to quickly respond to simple security alerts.",
    "**EDR (Endpoint Detection and Response) (The Individual Sentry)**: A tool that watches every action on a computer to find and stop hackers.",
    "**MDR (Managed Detection and Response)**: Hiring an external 'Strike Team' to manage your security tools for you.",
    "**XDR (Extended Detection and Response)**: A modern approach that connects data from the network, cloud, and computers into one view.",
    "**Incident Response (The Call to Battle)**: The formal process of dealing with a security breach.",
    "**Identification (The Discovery of the Foe)**: Finding out that there has been a breach.",
    "**Containment (The Digital Shield-Wall)**: Cutting off the attacker so they can't spread further.",
    "**Short-Term Containment**: Quickly stopping the bleeding (e.g., pulling a network cable).",
    "**Long-Term Containment**: Rebuilding parts of the network to be safe.",
    "**Eradication (Purging the Enemy)**: Completely removing the attacker, their malware, and their secret backdoors.",
    "**Recovery (The Rebuilding of the Hall)**: Getting systems back online and checking that they are safe.",
    "**Post-Incident Activity (The Council for the Future)**: Studying the attack to make sure it NEVER happens again.",
    "**CSIRT (Computer Security Incident Response Team)**: The specialist team that leads the fight during a breach.",
    "**Forensics (Digital Tracks Archaeology)**: The science of finding and preserving evidence of an attack.",
    "**Memory Forensics (The Spirit-Track)**: Analyzing the RAM of a computer to find running malware and hidden passwords.",
    "**Disk Forensics (The Stone-Track)**: Analyzing hard drives for deleted files and logs.",
    "**Network Forensics (The Sea-Path Track)**: Analyzing network traffic to see what the attacker did.",
    "**Anti-Forensics (Erasing the Tracks)**: Techniques used by attackers to delete their logs and hide their presence.",
    "**Log Wiping (Burning the Records)**: Deleting the logs that would show the attacker's actions.",
    "**Steganography (The Hidden Rune in the Art)**: Hiding malicious data inside a normal-looking image or audio file.",
    "**Cryptography (The Ancient Art of Hidden Meaning)**: Using math to keep secrets.",
    "**Symmetric Cryptography (The Shared Secret Key)**: One key for both locking and unlocking.",
    "**Asymmetric Cryptography (The Public and Private Keys)**: A public key for locking and a private key for unlocking.",
    "**Hashing (The One-Way Seal)**: Turning data into a fixed string that can't be reversed, used to check for changes.",
    "**Salt (The Extra Protection)**: Adding random data to a hash to make it much harder to crack with a pre-made table.",
    "**Digital Signatures (The King's Mark)**: Ensuring a message really came from who it says and hasn't been changed.",
    "**PKI (Public Key Infrastructure) (The Realm of Trust)**: The system of digital certificates and authorities that makes the internet safe.",
    "**TLS / SSL (The Shield of the Connection)**: Encrypting the data that travels between your browser and a website.",
    "**Perfect Forward Secrecy (PFS)**: Ensuring that even if someone steals a server's secret key later, they can't decrypt past conversations.",
    "**Quantum Cryptography (The Future-Runes)**: Security based on the laws of physics, making it impossible to eavesdrop without being detected.",
    "**Post-Quantum Cryptography (The Shield for the Future)**: Developing math that even a Quantum computer can't break.",
    "**Network Defense (The Guarding of the Sea-Paths)**: Protecting the ways that data travels.",
    "**Firewall (The Wall of Fire)**: Filtering traffic to block raiders while letting friends through.",
    "**IDS (Intrusion Detection System) (The Watchman's Horn)**: Notifying the team when a raider is spotted.",
    "**IPS (Intrusion Prevention System) (The Automatic Defender)**: Notifying AND automatically stopping a raider.",
    "**WAF (Web Application Firewall) (The Guard for the Longship)**: A specific firewall for protecting websites.",
    "**VLAN (The Isolated Village)**: Dividing a large network into small, separate groups to limit the spread of an attack.",
    "**NAC (Network Access Control) (The Identification Guard)**: Checking that every device is safe before letting it join the network.",
    "**Zero Trust (Always Doubt, Always Verify)**: A security model where NO ONE is trusted by default, even if they are inside the walls.",
    "**VPN (The Hidden Tunnel)**: A secure, encrypted way to connect to a private network over the public sea (Internet).",
    "**SD-WAN (The Smart Trade-Route)**: Using software to manage many different network connections securely.",
    "**SASE (Secure Access Service Edge)**: Connecting network and security into one cloud service.",
    "**WAF vs Firewall**: Comparing a guard for the whole gate vs a guard specifically for the market stalls (web apps).",
    "**HoneyPot (The Trapped Treasure)**: A fake server designed to look like a target to catch hackers and study their tactics.",
    "**Canary Tokens (The Silent Alarms)**: Files or URLs that don't look important but send an alert to the security team if a hacker opens them.",
    "**DDoS Protection (Standing against the Tidal Wave)**: Services like Cloudflare that absorb massive floods of traffic to keep a site from crashing.",
    "**Asset Management (The Great Inventory of the Realm)**: Keeping track of every server, computer, and cloud account you own so you can protect them.",
    "**Vulnerability Management (The Mending of the Walls)**: The continuous work of finding and fixing holes in your security.",
    "**Patch Management (The Blacksmith's Repairs)**: Quickly applying updates to software to fix security bugs.",
    "**Configuration Management (The Law of the Hall)**: Ensuring all systems are set up in the safest way following standard 'Hardening' rules.",
    "**Hardening (Forging the Shield)**: Turning off every part of a computer that isn't absolutely needed to make it harder to hack.",
    "**Least Privilege (Norns' Law of Access)**: Only giving someone the EXACT amount of access they need and nothing more.",
    "**RBAC (Role-Based Access Control) (The Responsibility of the Rank)**: Giving access based on a person's job (e.g., 'Warrior' can read, 'Jarl' can edit).",
    "**Privileged Access Management (PAM) (Guarding the Master-Keys)**: Extra-strong security and logging for the most powerful accounts.",
    "**Identity Management (The Scroll of Names)**: Managing the digital identities of every person and service in the organization.",
    "**MFA (Multi-Factor Authentication) (The Three-Fold Lock)**: Needing something you KNOW (password), something you HAVE (phone), and something you ARE (fingerprint) to enter.",
    "**SSO (Single Sign-On) (The Master-Key of the Hall)**: One secure login that gives access to many different halls (apps).",
    "**Federated Identity (The Alliance of Kings)**: Allowing users from one organization to log in to another organization's systems safely.",
    "**IAM Policies (The Law of the Clouds)**: The specific rules that decide who can touch which cloud resource.",
    "**Cyber Governance (The Law of the Thing)**: The overarching rules and strategy for security in an organization.",
    "**Risk Assessment (The Weighing of the Danger)**: Deciding which threats are most likely and which would do the most damage.",
    "**Risk Mitigation (Softening the Blow)**: Steps taken to make an attack less likely or less painful.",
    "**Risk Acceptance (Living with the Danger)**: Choosing to accept a small risk because fixing it is too expensive.",
    "**Risk Transference (Buying the Shield-Insurance)**: Paying another company to take the financial hit if an attack happens.",
    "**Compliance (Obeying the Sovereign's Law)**: Following rules like GDPR (European Privacy) or HIPAA (Healthcare Security).",
    "**Security Frameworks (NIST, ISO 27001)**: The standard 'Sagas of Security' that tell you the best way to build a defense program.",
    "**Shadow IT (The Hidden Settlements)**: When employees use apps or clouds that the security team doesn't know about.",
    "**BYOD (Bring Your Own Weapon/Device)**: Allowing employees to use their own phones and laptops for work, which creates massive security risks.",
    "**Security Awareness Training (Teaching the Village to Fight)**: Teaching every employee how to spot a phish and use strong passwords.",
    "**Inside Threat (The Traitor in the Mead-Hall)**: An employee or contractor who uses their legitimate access to steal or destroy.",
    "**Industrial Control Systems (ICS/SCADA) (The Mechanics of the Realm)**: Attacking the computers that control power plants, water, and factories.",
    "**OT (Operational Technology) Security**: Protecting the physical systems (like valves and motors) rather than just data.",
    "**IoT Security (The Whispering Objects)**: Protecting the billions of small, connected devices (like smart lights and cameras) that are often very easy to hack.",
    "**Dark Web Monitoring (The Scout in Niflheim)**: Watching the hidden parts of the internet where stolen data and passwords are sold.",
    "**Bug Bounty (The Reward for the Scout)**: Paying friendly hackers to find and report bugs to you before the raiders do.",
    "**Vulnerability Disclosure Policy (VDP) (The Honorable Message Path)**: A public guide on how scouts should report bugs to you safely.",
    "**Cyber Range (The Training Grounds)**: A safe, simulated environment for warriors to practice hacking and defending.",
    "**Capture the Flag (CTF) (The Games of Skill)**: A competition where hackers solve puzzles to find 'flags' and prove their strength.",
    "**The Ethics of Hacking (The Warrior's Code)**: The rules that separate the honorable protector from the common raider.",
    "**Digital Sovereignty (The Independence of the Realm)**: The right of a person or a country to control its own digital fate.",
    "**Privacy by Design (The Built-in Shield)**: Building a system so that it protects user privacy from the very first line of code.",
    "**Security by Design (The Built-in Strength)**: Building a system so it is secure from the very start, not as an afterthought.",
    "**Cyber Resilience (The Will to Stand)**: The ability to keep working even while under a massive attack.",
    "**Total Uptime (The Legend of the Eternal Hall)**: The goal of never falling, no matter the storm digital or physical.",
    "**The Skaldic Oath of Protection: 'I see the shadow before it falls, I mend the wall before it breaks, I guard the runes that hold our world.'**"
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 501 - 1000\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+501}. {entry}\n")
