import os
from pathlib import Path

_KNOWLEDGE_REF = (
    Path(__file__).resolve().parent.parent
    / "viking_girlfriend_skill" / "data" / "knowledge_reference"
)
file_path = _KNOWLEDGE_REF / "SOFTWARE_ENGINEERING.md"

entries = [
    "**Apache Pulsar**: A distributed pub-sub messaging system originally created at Yahoo.",
    "**Google Pub/Sub**: A messaging service for exchanged event data among applications and services.",
    "**Amazon SQS (Simple Queue Service)**: A fully managed message queuing service that enables you to decouple and scale microservices, distributed systems, and serverless applications.",
    "**Amazon SNS (Simple Notification Service)**: A fully managed messaging service for both system-to-system and system-to-person communication.",
    "**Azure Service Bus**: A fully managed enterprise message broker with message queues and publish-subscribe topics.",
    "**ZeroMQ**: A high-performance asynchronous messaging library, aimed at use in distributed or concurrent applications.",
    "**MQTT (Message Queuing Telemetry Transport)**: A lightweight, publish-subscribe network protocol that transports messages between devices.",
    "**AMQP (Advanced Message Queuing Protocol)**: An open standard application layer protocol for message-oriented middleware.",
    "**Stomp (Simple Text Oriented Messaging Protocol)**: An interoperable wire-level protocol that allows any STOMP client to talk with any message broker supporting the protocol.",
    "**WebRTC (Web Real-Time Communication)**: A free, open-source project that provides web browsers and mobile applications with real-time communication via simple application programming interfaces.",
    "**RTMP (Real-Time Messaging Protocol)**: A TCP-based protocol which maintains persistent connections and allows low-latency communication.",
    "**HLS (HTTP Live Streaming)**: An adaptive bitrate streaming communications protocol implemented by Apple Inc.",
    "**DASH (Dynamic Adaptive Streaming over HTTP)**: An adaptive bitrate streaming technique that enables high quality streaming of media content over the Internet delivered from conventional HTTP web servers.",
    "**FFmpeg**: A complete, cross-platform solution to record, convert and stream audio and video.",
    "**WebM**: An open, royalty-free, media file format designed for the web.",
    "**H.264 (AVC)**: A block-oriented motion-compensation-based video compression standard.",
    "**H.265 (HEVC)**: A video compression standard, one of several potential successors to the widely used AVC.",
    "**VP8 & VP9**: Open and royalty-free video compression formats developed by Google.",
    "**AV1**: An open, royalty-free video coding format designed for video transmissions over the Internet.",
    "**FLAC (Free Lossless Audio Codec)**: An audio coding format for lossless compression of digital audio.",
    "**Opus (Audio Format)**: A totally open, royalty-free, highly versatile audio codec.",
    "**PCM (Pulse-Code Modulation)**: A method used to digitally represent sampled analog signals.",
    "**Bitrate (CBR, VBR)**: Constant Bitrate vs Variable Bitrate.",
    "**Sampling Rate**: The number of samples of audio carried per second.",
    "**Quantization (Audio/Video)**: The process of mapping input values from a large set to output values in a smaller set.",
    "**Interlaced vs Progressive Video**: Two primary methods for 'painting' a video image on a display screen.",
    "**Aspect Ratio**: The ratio of the width to the height of an image or screen.",
    "**Frame Rate (FPS)**: The frequency at which consecutive images called frames appear on a display.",
    "**Color Space (sRGB, Adobe RGB, Rec. 709, Rec. 2020)**: A specific organization of colors.",
    "**HDR (High Dynamic Range)**: This allows for a much higher contrast and color range than standard dynamic range (SDR).",
    "**Dolby Vision**: A set of technologies for high dynamic range (HDR) video.",
    "**HDR10 & HDR10+**: Open standards for high dynamic range (HDR) video.",
    "**Chromecast**: A line of digital media players developed by Google.",
    "**AirPlay**: A proprietary protocol stack/suite developed by Apple Inc. that allows wireless streaming between devices.",
    "**Miracast**: A standard for wireless connections from devices to displays.",
    "**DLNA (Digital Living Network Alliance)**: A set of interoperability guidelines for sharing digital media among multimedia devices.",
    "**UPnP (Universal Plug and Play)**: A set of networking protocols that permits networked devices to seamlessly discover each other's presence on the network.",
    "**mDNS (Multicast DNS)**: A protocol that resolves hostnames to IP addresses within small networks that do not include a local name server.",
    "**DNS-SD (DNS Service Discovery)**: A way of using standard DNS programming interfaces, servers, and packet formats to browse the network for services.",
    "**Bonjour (Apple)**: Apple’s implementation of Zero-configuration networking.",
    "**Avahi**: A free Zero-configuration networking implementation, including a system for multicast DNS/DNS-SD service discovery.",
    "**LLDP (Link Layer Discovery Protocol)**: A vendor-neutral link layer protocol used by network devices for advertising their identity, capabilities, and neighbors.",
    "**CDP (Cisco Discovery Protocol)**: A proprietary Data Link Layer protocol developed by Cisco Systems.",
    "**SNMP (Simple Network Management Protocol)**: An Internet-standard protocol for collecting and organizing information about managed devices on IP networks.",
    "**RMON (Remote Monitoring)**: An extension to the SNMP MIB.",
    "**NetFlow**: A feature that was introduced on Cisco routers to provide the ability to collect IP network traffic as it enters or exits an interface.",
    "**sFlow**: A standard for monitoring high speed switched or routed networks.",
    "**IPFIX (IP Flow Information Export)**: An IETF protocol for exporting IP flow information from routers, switches, and other devices.",
    "**Packet Sniffing**: The practice of capturing and inspecting packets as they travel across a network.",
    "**Deep Packet Inspection (DPI)**: A type of data processing that inspects in detail the data being sent over a computer network.",
    "**Traffic Shaping**: A bandwidth management technique used on computer networks which delays some or all datagrams to bring them into compliance with a desired traffic profile.",
    "**QoS (Quality of Service)**: The description or measurement of the overall performance of a service.",
    "**VLAN (Virtual Local Area Network)**: Any broadcast domain that is partitioned and isolated in a computer network at the data link layer.",
    "**VPN Tunneling**: Encapsulating one network protocol within another.",
    "**IPsec (Internet Protocol Security)**: A secure network protocol suite that authenticates and encrypts the packets of data to provide secure stepwise communication between two computers over an IP network.",
    "**WireGuard**: An extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography.",
    "**OpenVPN**: An open-source commercial software that implements virtual private network techniques.",
    "**L2TP (Layer 2 Tunneling Protocol)**: A tunneling protocol used to support virtual private networks or as part of the delivery of services by ISPs.",
    "**PPTP (Point-to-Point Tunneling Protocol)**: An obsolete method for implementing virtual private networks.",
    "**IKEv2 (Internet Key Exchange version 2)**: A VPN encryption protocol used to handle request and response actions.",
    "**Shadowsocks**: A free and open-source encryption protocol project, widely used in China to circumvent Internet censorship.",
    "**V2Ray (Project V)**: A set of tools to help you build your own privacy network over internet.",
    "**Tor (The Onion Router)**: Free and open-source software for enabling anonymous communication.",
    "**I2P (Invisible Internet Project)**: An anonymous network layer that allows for censorship-resistant, peer-to-peer communication.",
    "**Freenet**: A peer-to-peer platform for censorship-resistant, anonymous communication.",
    "**Darknet**: An overlay network within the Internet which can only be accessed with specific software, configurations, or authorization.",
    "**Deep Web**: Parts of the World Wide Web whose contents are not indexed by standard web search-engines.",
    "**Clearnet**: The publicly accessible Internet.",
    "**Surface Web**: The portion of the World Wide Web that is readily available to the general public and searchable with standard web search engines.",
    "**Dark Web Marketplaces**: Sites on the dark web that offer illegal products and services.",
    "**Onion Services**: Specialized services that can only be reached via the Tor network.",
    "**Hidden Services**: Original term for Onion Services.",
    "**Exit Nodes (Tor)**: The gateways where Tor traffic hits the Internet.",
    "**Bridges (Tor)**: Tor relays that are not listed in the public Tor directory.",
    "**Snowflake (Tor)**: A pluggable transport that allows people from anywhere in the world to help users in censored countries access Tor.",
    "**Obfs4**: A pluggable transport that makes Tor traffic look like random data.",
    "**Meek (Tor)**: A pluggable transport that uses HTTP 'fronting' to disguise Tor traffic.",
    "**Domain Fronting**: A technique that circumvents censorship by using different domain names in the SNI and the Host header.",
    "**ECH (Encrypted Client Hello)**: An extension for TLS that encrypts the entire ClientHello message, including the SNI.",
    "**DNS over HTTPS (DoH)**: A protocol for performing remote Domain Name System resolution via the HTTPS protocol.",
    "**DNS over TLS (DoT)**: A security protocol for encrypting and wrapping Domain Name System queries and answers via the Transport Layer Security protocol.",
    "**DNS over QUIC (DoQ)**: An IETF standard for DNS over QUIC.",
    "**DNSCrypt**: A protocol that authenticates and encrypts Domain Name System traffic between a user's computer and a recursive nameserver.",
    "**DNSSEC (Domain Name System Security Extensions)**: A suite of IETF specifications for securing certain kinds of information provided by the Domain Name System.",
    "**TSIG (Transaction Signature)**: A mechanism for authenticating DNS messages using shared secret keys.",
    "**Dynamic DNS (DDNS)**: A method of automatically updating a name server in the Domain Name System.",
    "**Anycast DNS**: A network addressing and routing methodology in which a single destination IP address is shared by devices in multiple locations.",
    "**Recursive DNS Resolver**: A DNS server that receives queries from clients and handles the process of resolving the domain name.",
    "**Authoritative DNS Server**: A DNS server that holds the actual records for a domain.",
    "**Root Name Servers**: The servers at the root of the DNS hierarchy.",
    "**TLD (Top-Level Domain)**: One of the domains at the highest level in the hierarchical Domain Name System of the Internet.",
    "**gTLD vs ccTLD**: Generic vs Country Code Top-Level Domains.",
    "**WHOIS**: A query and response protocol that is widely used for querying databases that store the registered users or assignees of an Internet resource.",
    "**ICANN (Internet Corporation for Assigned Names and Numbers)**: A nonprofit organization responsible for coordinating the maintenance and procedures of several databases related to the namespaces and numerical spaces of the Internet.",
    "**IANA (Internet Assigned Numbers Authority)**: A function of ICANN that oversees global IP address allocation, autonomous system number allocation, root zone management in the Domain Name System, and other Internet Protocol-related symbols and Internet numbers.",
    "**ARIN, RIPE NCC, APNIC, AFRINIC, LACNIC**: Regional Internet Registries (RIRs).",
    "**Autonomous System (AS)**: A collection of connected Internet Protocol routing prefixes under the control of one or more network operators on behalf of a single administrative entity or domain.",
    "**BGP (Border Gateway Protocol)**: A standardized exterior gateway protocol designed to exchange routing and reachability information among autonomous systems on the Internet.",
    "**OSPF (Open Shortest Path First)**: A routing protocol for Internet Protocol networks.",
    "**IS-IS (Intermediate System to Intermediate System)**: A routing protocol designed to move information efficiently within a computer network.",
    "**RIP (Routing Information Protocol)**: One of the oldest distance-vector routing protocols which employs the hop count as a routing metric.",
    "**EIGRP (Enhanced Interior Gateway Routing Protocol)**: An advanced distance-vector routing protocol that is used on a computer network for automating routing decisions and configuration.",
    "**MPLS (Multiprotocol Label Switching)**: A routing technique in telecommunications networks that directs data from one node to the next based on short path labels rather than long network addresses.",
    "**SD-WAN (Software-Defined Wide Area Network)**: A virtual WAN architecture that allows enterprises to leverage any combination of transport services to securely connect users to applications.",
    "**OpenFlow**: A communications protocol that gives access to the forwarding plane of a network switch or router over the network.",
    "**SDN (Software-Defined Networking)**: An approach to network management that enables dynamic, programmatically efficient network configuration.",
    "**NFV (Network Functions Virtualization)**: A network architecture concept that uses the technologies of IT virtualization to virtualize entire classes of network node functions.",
    "**VXLAN (Virtual Extensible LAN)**: A network virtualization technology that attempts to address the scalability problems associated with large cloud computing deployments.",
    "**NVGRE (Network Virtualization using Generic Routing Encapsulation)**: A network virtualization technology that specifies how Virtual Machines can be organized into virtual networks.",
    "**Overlay Network**: A computer network that is built on top of another network.",
    "**Underlay Network**: The physical infrastructure over which the overlay network is built.",
    "**Control Plane (Networking)**: The part of a network that carries signaling traffic and is responsible for routing.",
    "**Data Plane (Forwarding Plane)**: The part of a network that carries user traffic.",
    "**Management Plane**: The part of a network that carries administrative traffic.",
    "**Northbound API (SDN)**: An interface that enables a component to communicate with a higher-level component.",
    "**Southbound API (SDN)**: An interface that enables a component to communicate with a lower-level component.",
    "**East-West Traffic**: Network traffic that travels between servers within a data center.",
    "**North-South Traffic**: Network traffic that enters or leaves a data center.",
    "**Spine-Leaf Architecture**: A two-tier network topology used in data centers.",
    "**Fat Tree Topology**: A type of network topology where each level in the tree has the same aggregate bandwidth.",
    "**CLOS Network**: A kind of multistage circuit-switching network.",
    "**LACP (Link Aggregation Control Protocol)**: A protocol that provides a method to control the bundling of several physical links together to form a single logical link.",
    "**EtherChannel**: A port-link aggregation technology used primarily on Cisco switches.",
    "**VPC (Virtual Port Channel)**: A virtualization technology where a pair of switches appear as a single logical entity to a third device.",
    "**Stacking (Switches)**: Connecting multiple switches so they behave as a single unit.",
    "**VRRP (Virtual Router Redundancy Protocol)**: A computer networking protocol that provides for automatic assignment of available Internet Protocol routers to participating hosts.",
    "**HSRP (Hot Standby Router Protocol)**: A Cisco proprietary redundancy protocol for establishing a fault-tolerant default gateway.",
    "**GLBP (Gateway Load Balancing Protocol)**: A Cisco proprietary protocol that attempts to overcome the limitations of existing redundant router protocols.",
    "**STP (Spanning Tree Protocol)**: A network protocol that builds a loop-free logical topology for Ethernet networks.",
    "**RSTP (Rapid Spanning Tree Protocol)**: An evolution of STP that provides significantly faster spanning tree convergence.",
    "**MSTP (Multiple Spanning Tree Protocol)**: A protocol that allows for multiple spanning trees based on VLANs.",
    "**BPDU Guard**: A feature that disables a port if it receives a Bridge Protocol Data Unit.",
    "**Root Guard**: A feature that prevents a switch from becoming the root bridge if it receives BPDUs from a 'superior' switch on a specific port.",
    "**Loop Guard**: A feature that prevents loops on ports where BPDUs have stopped being received.",
    "**Port Fast**: A feature that allows a switch port to bypass the listening and learning states and go straight to the forwarding state.",
    "**MAC Address Table**: A table stored in a switch that maps MAC addresses to physical ports.",
    "**CAM (Content Addressable Memory)**: A special type of computer memory used in switch lookups.",
    "**TCAM (Ternary Content Addressable Memory)**: A specialized type of High-speed memory that searches its entire contents in a single clock cycle.",
    "**VLAN Trunking (802.1Q)**: A networking standard that supports virtual LANs (VLANs) on an IEEE 802.3 Ethernet network.",
    "**VTP (VLAN Trunking Protocol)**: A Cisco proprietary protocol that propagates the definition of Virtual Local Area Networks (VLAN) on the whole local area network.",
    "**GVRP (GARP VLAN Registration Protocol)**: A standards-based protocol for propagating VLAN information.",
    "**MVRP (Multiple VLAN Registration Protocol)**: The successor to GVRP.",
    "**Private VLANs (PVLANs)**: A technique in computer networking where a VLAN contains switch ports that are restricted such that they can only communicate with a given 'uplink'.",
    "**VLAN Hopping**: A network security exploit where an attacker on a VLAN gains access to traffic on other VLANs that would normally not be accessible.",
    "**Double Tagging Attack**: A type of VLAN hopping attack where an attacker adds two VLAN tags to an Ethernet frame.",
    "**Switch Spoofing Attack**: A type of VLAN hopping attack where an attacker configures their device to behave like a switch and negotiate a trunk link.",
    "**DHCP Snooping**: A security feature that acts like a firewall between untrusted hosts and trusted DHCP servers.",
    "**Dynamic ARP Inspection (DAI)**: A security feature that validates Address Resolution Protocol (ARP) packets in a network.",
    "**IP Source Guard**: A security feature that prevents IP spoofing by filtering traffic based on the DHCP snooping binding database or static IP source entries.",
    "**Port Security**: A feature that restricts the number of MAC addresses that can be learned on a specific switch port.",
    "**Sticky MAC Addresses**: A feature that allows a switch to dynamically learn MAC addresses and save them to the running configuration.",
    "**802.1X (Dot1x)**: An IEEE Standard for port-based Network Access Control.",
    "**RADIUS (Remote Authentication Dial-In User Service)**: A networking protocol that provides centralized Authentication, Authorization, and Accounting (AAA) management.",
    "**TACACS+ (Terminal Access Controller Access-Control System Plus)**: A protocol that handles authentication, authorization, and accounting (AAA) services.",
    "**MAB (MAC Authentication Bypass)**: A mechanism that allows devices without an 802.1X supplicant to be authenticated based on their MAC address.",
    "**EAP (Extensible Authentication Protocol)**: An authentication framework frequently used in wireless networks and point-to-point connections.",
    "**PEAP (Protected EAP)**: A version of EAP that encapsulates EAP within an encrypted and authenticated Transport Layer Security (TLS) tunnel.",
    "**EAP-TLS**: A version of EAP that uses digital certificates for mutual authentication.",
    "**EAP-TTLS**: A version of EAP that uses a server-side certificate to establish a secure tunnel.",
    "**MS-CHAPv2**: A password-based, challenge-response mutual authentication protocol.",
    "**OAuth 2.0 Device Flow**: An OAuth 2.0 extension that allows devices with limited input capabilities to obtain user authorization.",
    "**OIDC Discovery**: A mechanism for obtaining the configuration of an OpenID Provider.",
    "**JWKS (JSON Web Key Set)**: A set of keys which contains the public keys used to verify any JSON Web Token (JWT) issued by the authorization server.",
    "**SCIM (System for Cross-domain Identity Management)**: An open standard for automating the exchange of user identity information between identity domains, or IT systems.",
    "**IdP (Identity Provider)**: A system entity that creates, maintains, and manages identity information for principals while providing authentication services to relying applications.",
    "**SP (Service Provider)**: An entity that provides a service to a principal.",
    "**Relying Party (RP)**: An entity that relies on the identity information provided by an IdP.",
    "**Active Directory (AD)**: A directory service developed by Microsoft for Windows domain networks.",
    "**LDAP (Lightweight Directory Access Protocol)**: An open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services.",
    "**Azure AD (Entra ID)**: Microsoft's cloud-based identity and access management service.",
    "**Okta**: A leading independent identity provider.",
    "**Auth0**: An adaptable authentication and authorization platform.",
    "**Keycloak**: An open source identity and access management solution.",
    "**Casdoor**: A UI-first centralized authentication / Single-Sign-On (SSO) platform.",
    "**Authentik**: An open-source Identity Provider focused on flexibility and versatility.",
    "**Authelia**: An open-source authentication and authorization server.",
    "**Boundary (HashiCorp)**: Secure remote access to sensitive systems based on trusted identity.",
    "**Vault (HashiCorp)**: A tool for securely accessing secrets.",
    "**Secrets Management**: The practice of managing digital authentication credentials (secrets).",
    "**Hardware Security Module (HSM)**: A physical computing device that safeguards and manages digital keys for strong authentication and provides cryptoprocessing.",
    "**TPM (Trusted Platform Module)**: An international standard for a secure cryptoprocessor.",
    "**FIDO2**: A set of standards that enable users to leverage common devices to easily authenticate to online services in both mobile and desktop environments.",
    "**WebAuthn**: A web standard published by the W3C for secure web authentication.",
    "**U2F (Universal 2nd Factor)**: An open standard that strengthens and simplifies two-factor authentication (2FA) using specialized USB or NFC devices.",
    "**CTAP (Client to Authenticator Protocol)**: Part of the FIDO2 project, allowing external authenticators to communicate with a client.",
    "**Passkeys**: A digital credential that is stored on your device and used to sign in to websites and apps.",
    "**Magic Links**: A type of passwordless authentication where a user is sent a link via email or SMS.",
    "**OTP (One-Time Password)**: A password that is valid for only one login session or transaction.",
    "**TOTP (Time-based One-Time Password)**: An OTP that is generated based on the current time.",
    "**HOTP (HMAC-based One-Time Password)**: An OTP that is generated based on a counter.",
    "**Google Authenticator**: A software-based authenticator by Google.",
    "**Authy**: A popular two-factor authentication app.",
    "**Microsoft Authenticator**: A two-factor authentication app by Microsoft.",
    "**Duo Security**: A cloud-based security platform that provides two-factor authentication.",
    "**YubiKey**: A hardware authentication device that supports one-time passwords, public-key cryptography, and authentication.",
    "**Titan Security Key**: A FIDO-compliant security key designed by Google.",
    "**Recovery Codes**: One-time use codes that can be used to log in if you lose access to your primary 2FA method.",
    "**Backup Keys**: Physical keys that are kept as a backup for your primary security key.",
    "**Session Hijacking**: An attack where the attacker takes over a valid user session.",
    "**Session Fixation**: An attack where the attacker sets a user's session ID to a known value.",
    "**Cookie Hijacking**: A type of session hijacking where the attacker steals a cookie.",
    "**Cookie Poisoning**: An attack where the attacker modifies the content of a cookie.",
    "**Secure Session Management Guidelines**: Using secure, HttpOnly, and SameSite flags; rotating session IDs; using short-lived sessions.",
    "**OIDC Scopes (openid, profile, email, address, phone)**: Predefined scopes for requesting specific user information.",
    "**Claims (JWT)**: Pieces of information asserted about a subject.",
    "**Registered Claims (iss, sub, aud, exp, nbf, iat, jti)**: Predefined claim names in the JWT spec.",
    "**Private Claims**: Claims that are defined by the application instead of the JWT spec.",
    "**Access Token**: A credential that can be used by an application to access an API.",
    "**ID Token**: A credential that contains information about the authenticated user.",
    "**Refresh Token**: A credential that can be used to obtain new access tokens.",
    "**Introspection (OAuth 2.0)**: An endpoint that allows clients to check the validity of an access token.",
    "**Revocation (OAuth 2.0)**: An endpoint that allows clients to invalidate an access or refresh token.",
    "**Dynamic Client Registration (OAuth 2.0)**: A protocol for dynamically registering OAuth 2.0 clients with authorization servers.",
    "**PKCE (Proof Key for Code Exchange)**: An extension to the OAuth 2.0 authorization code flow to prevent code injection attacks.",
    "**State Parameter (OAuth 2.0)**: An opaque value used by the client to maintain state between the request and callback.",
    "**Nonce Parameter (OIDC)**: A string value used to associate a client session with an ID Token, and to mitigate replay attacks.",
    "**Implicit Flow (Deprecated)**: An OAuth 2.0 flow designed for browser-based apps that is now considered insecure.",
    "**Authorization Code Flow with PKCE**: The recommended flow for mobile and single-page applications.",
    "**Client Credentials Flow**: An OAuth 2.0 flow used for machine-to-machine communication.",
    "**Resource Owner Password Credentials Flow (Deprecated)**: An insecure flow where the user provides their username and password directly to the client.",
    "**Device Authorization Grant**: Useful for devices that have no browser or limited input (e.g. Smart TVs).",
    "**Ciba (Client-Initiated Backchannel Authentication)**: A flow where the client requests authentication on behalf of a user without the user being present on the client.",
    "**Fapi (Financial-grade API)**: A set of security profiles for APIs used in high-security environments like banking.",
    "**DPoP (Demonstrating Proof-of-Possession at the Application Layer)**: A mechanism for sender-constraining OAuth 2.0 tokens.",
    "**Mutual TLS (mTLS) for OAuth 2.0**: Using mTLS to authenticate clients and sender-constrain tokens.",
    "**RAR (Rich Authorization Requests)**: An extension for requesting fine-grained authorization in OAuth 2.0.",
    "**Pushed Authorization Requests (PAR)**: An extension that allows clients to push the payload of an authorization request to the authorization server.",
    "**JARM (JWT Secured Authorization Response Mode)**: An extension for signing and encrypting authorization responses.",
    "**JAR (JWT Secured Authorization Request)**: An extension for signing and encrypting authorization requests.",
    "**OIDC Core**: The primary OpenID Connect specification.",
    "**OIDC Session Management**: Specs for managing user sessions across multiple applications.",
    "**OIDC Front-Channel Logout**: A mechanism for logging out a user from multiple applications via the browser.",
    "**OIDC Back-Channel Logout**: A mechanism for logging out a user from multiple applications via server-to-server communication.",
    "**Self-Issued OpenID Provider (SIOP)**: An OIDC provider that is managed by the user themselves.",
    "**Verifiable Credentials (VC)**: A standard for digital credentials that are tamper-evident and can be verified.",
    "**Decentralized Identifiers (DID)**: A new type of identifier that enables verifiable, decentralized digital identity.",
    "**SSI (Self-Sovereign Identity)**: An approach to digital identity that gives individuals control over their own data.",
    "**Zero-Knowledge Architecture (Client-Side Encryption)**: A design where the server has zero knowledge of the user's data.",
    "**Privacy by Design**: An approach to systems engineering that takes privacy into account throughout the whole engineering process.",
    "**Data Protection Impact Assessment (DPIA)**: A process used to identify and minimize the data protection risks of a project.",
    "**Data Portability**: The right of an individual to receive their personal data from a controller in a structured, commonly used and machine-readable format.",
    "**Right to be Forgotten (ERASURE)**: The right of an individual to have their personal data erased.",
    "**Right to Object**: The right of an individual to object to the processing of their personal data.",
    "**Data Minimization**: The principle that only the data necessary for a specific purpose should be processed.",
    "**Purpose Limitation**: The principle that data should only be collected for specified, explicit and legitimate purposes.",
    "**Storage Limitation**: The principle that data should only be kept for as long as necessary.",
    "**Integrity and Confidentiality (Information Security Principle)**: Ensuring that data is accurate and only accessible by authorized parties.",
    "**Accountability (GDPR Principle)**: The responsibility of the data controller to demonstrate compliance.",
    "**Privacy Policy**: A statement or legal document that discloses some or all of the ways a party gathers, uses, discloses, and manages a customer or client's data.",
    "**Terms of Service (ToS)**: Rules by which one must agree to abide in order to use a service.",
    "**End User License Agreement (EULA)**: A legal contract between a software application author or publisher and the user of that application.",
    "**Cookies (First-party vs Third-party)**: Small pieces of data sent from a website and stored on the user's computer by the user's web browser.",
    "**Zombie Cookies (Evercookies)**: Any HTTP cookie that is recreated by a script after a user attempts to delete it.",
    "**Supercookies**: Not a cookie, but a persistent identifier injected by an ISP or a tracking pixel.",
    "**Canvas Fingerprinting**: A type of browser fingerprinting that uses the HTML5 canvas element to identify a user.",
    "**Audio Fingerprinting**: A technique used to identify a browser by analyzing the subtle differences in its audio processing stack.",
    "**Font Fingerprinting**: Identifying a user based on the list of fonts installed on their system.",
    "**Battery Level Fingerprinting**: Using the Battery Status API to track users.",
    "**WebRTC IP Leak**: A vulnerability where a user's real IP address is revealed even when using a VPN or proxy.",
    "**DNS Leak**: When DNS queries are sent outside the VPN tunnel.",
    "**IPv6 Leak**: When IPv6 traffic bypasses the VPN tunnel.",
    "**Kill Switch (VPN)**: A feature that automatically disconnects your device from the Internet if the VPN connection is lost.",
    "**Split Tunneling**: A VPN feature that allows you to route some of your device or app traffic through the encrypted VPN tunnel while other apps or devices go directly.",
    "**Multi-hop VPN (Double VPN)**: Routing your traffic through two or more VPN servers.",
    "**Tor over VPN**: Connecting to a VPN and then using the Tor browser.",
    "**VPN over Tor**: Connecting to the Tor network and then using a VPN.",
    "**Obfuscated Servers (VPN)**: Servers that hide the fact that you're using a VPN.",
    "**No-logs Policy (VPN)**: A claim by a VPN provider that they do not store any records of your online activity.",
    "**Five Eyes, Nine Eyes, Fourteen Eyes**: Intelligence-sharing alliances between countries.",
    "**Data Retention Laws**: Laws that require ISPs and other service providers to store user data for a certain period.",
    "**Net Neutrality**: The principle that Internet service providers should treat all data on the Internet the same.",
    "**Censorship (Internet)**: The control or suppression of what can be accessed, published, or viewed on the Internet.",
    "**Great Firewall of China**: Combining legislative actions and technologies enforced by the People's Republic of China to regulate the Internet domestically.",
    "**Internet Shutdowns (Kill Switches)**: Intentional disruption of internet or electronic communications.",
    "**Cyber Sovereignty**: The idea that a state has the right to govern its own cyberspace.",
    "**Safe Harbor (Deprecated)**: An agreement between the US and the EU on data protection.",
    "**Privacy Shield (Deprecated)**: The successor to Safe Harbor.",
    "**Data Privacy Framework (DPF)**: The current EU-US data transfer agreement.",
    "**Standard Contractual Clauses (SCCs)**: Sets of standard data protection clauses for transferring personal data to third countries.",
    "**Binding Corporate Rules (BCRs)**: Internal rules for data transfers within a multinational group.",
    "**Schrems I & Schrems II**: Landmark decisions by the Court of Justice of the European Union on data transfers to the US.",
    "**California Consumer Privacy Act (CCPA)**: A state statute intended to enhance privacy rights and consumer protection for residents of California.",
    "**California Privacy Rights Act (CPRA)**: An amendment to the CCPA that strengthens privacy protections.",
    "**Brazil LGPD (Lei Geral de Proteção de Dados)**: Brazil's comprehensive data protection law.",
    "**India DPDP (Digital Personal Data Protection Act)**: India's data protection law.",
    "**Personal Identifiable Information (PII)**: Any data that could potentially identify a specific individual.",
    "**Personal Health Information (PHI)**: Any information about health status, provision of health care, or payment for health care that can be linked to a specific individual.",
    "**Cross-Border Data Transfers**: The movement of personal data from one country to another.",
    "**Adequacy Decision**: A decision by a regulator that a third country provides an adequate level of data protection.",
    "**Data Controller**: The entity that determines the purposes and means of processing personal data.",
    "**Data Processor**: The entity that processes personal data on behalf of the controller.",
    "**Sub-processor**: A third party engaged by a data processor to carry out specific processing activities.",
    "**Joint Controllers**: Two or more controllers that jointly determine the purposes and means of processing.",
    "**Data Subject**: An identifiable natural person to whom personal data relates.",
    "**Sensitive Personal Data**: Special categories of personal data that require more protection (e.g. race, religion, health).",
    "**Genetic Data**: Personal data relating to the inherited or acquired genetic characteristics of a natural person.",
    "**Biometric Data (Personal Data)**: Personal data resulting from specific technical processing relating to the physical, physiological or behavioral characteristics of a natural person.",
    "**Profiling (Personal Data)**: Any form of automated processing of personal data to evaluate certain personal aspects relating to a natural person.",
    "**Automated Decision-Making**: Making a decision solely by automated means without any human involvement.",
    "**Transparency (GDPR Principle)**: The requirement to provide information to data subjects in a clear and accessible way.",
    "**Lawfulness, Fairness and Transparency**: The core principles of data processing.",
    "**Legal Basis for Processing (Consent, Contract, Legal Obligation, Vital Interests, Public Task, Legitimate Interests)**: The valid reasons for processing personal data under GDPR.",
    "**Explicit Consent**: A higher standard of consent required for certain types of processing.",
    "**Parental Consent (Digital services)**: Requirements for obtaining consent for processing the data of children.",
    "**Standard for Automated Management of Personal Data**: A concept related to simplifying privacy management.",
    "**Data Protection Officer (DPO)**: A leadership role within an organization that is responsible for overseeing data protection strategy and implementation.",
    "**Supervisory Authority (Data Protection Authority)**: An independent public authority which is established by an EU Member State.",
    "**One-Stop Shop (GDPR)**: A mechanism that allows data controllers and processors to deal with a single supervisory authority.",
    "**Consistency Mechanism (GDPR)**: A mechanism intended to ensure the consistent application of GDPR across the EU.",
    "**EDPB (European Data Protection Board)**: An independent European body which contributes to the consistent application of data protection rules throughout the European Union.",
    "**Art. 29 Working Party**: The predecessor to the EDPB.",
    "**Privacy Impact Assessment (PIA)**: An older term for a DPIA.",
    "**Data Breach Notification**: The requirement to inform the supervisory authority and sometimes data subjects about a data breach.",
    "**72-Hour Rule (Data Breach)**: The requirement to notify the supervisory authority within 72 hours of becoming aware of a data breach.",
    "**Security of Processing**: The requirement to implement appropriate technical and organizational measures to ensure a level of security appropriate to the risk.",
    "**Encryption (Technical Measure)**: A common technical measure for protecting personal data.",
    "**Pseudonymization**: The processing of personal data in such a manner that the personal data can no longer be attributed to a specific data subject without the use of additional information.",
    "**Anonymization (Irreversible)**: Rendering personal data anonymous in such a way that the data subject is no longer identifiable.",
    "**De-identification**: The process of removing identifying information from a dataset.",
    "**Re-identification (De-anonymization)**: The process of matching anonymized data with publicly available information or other datasets to identify the data subject.",
    "**K-Anonymity**: A property of a dataset such that each individual's data cannot be distinguished from at least k-1 other individuals.",
    "**L-Diversity**: An extension of k-anonymity that requires each group of k individuals to have at least l different values for sensitive attributes.",
    "**T-Closeness**: A refinement of l-diversity that requires the distribution of a sensitive attribute in any group of k individuals to be close to the distribution of that attribute in the entire dataset.",
    "**Noise Injection (Differential Privacy)**: Adding random noise to data to mask individual contributions.",
    "**Epsilon (Privacy Parameter)**: A measure of the privacy loss in a differentially private algorithm.",
    "**Delta (Privacy Parameter)**: A measure of the probability that a differentially private algorithm fails to provide epsilon-differential privacy.",
    "**Local vs Global Differential Privacy**: Whether noise is added at the user level or by a central aggregator.",
    "**Federated Learning**: A machine learning technique that trains an algorithm across multiple decentralized edge devices or servers holding local data samples, without exchanging them.",
    "**Confidential Computing**: A cloud computing technology that isolates data within a protected CPU enclave during processing.",
    "**Enclave (Confidential Computing)**: A secure, isolated area of memory.",
    "**Attestation (Remote)**: The process of verifying the state and identity of a remote device or enclave.",
    "**Oblivious RAM (ORAM)**: A cryptographic primitive that hides the pattern of memory accesses.",
    "**Property-Preserving Encryption**: Encryption that allows certain operations to be performed on the ciphertext.",
    "**Searchable Encryption**: Encryption that allows for keyword searches on encrypted data.",
    "**Signal Protocol**: A non-federated cryptographic protocol that provides end-to-end encryption for voice, video, and instant messaging.",
    "**Double Ratchet Algorithm**: A key management algorithm that provides self-healing and forward secrecy.",
    "**X3DH (Extended Triple Diffie-Hellman)**: A key agreement protocol that provides mutual authentication and forward secrecy.",
    "**Sealed Sender (Signal)**: A feature that hides who sent a message from the Signal servers.",
    "**Metadata (Privacy)**: Information about a communication (who, when, where) as opposed to the content.",
    "**Metadata-Private Messaging**: Systems that attempt to hide not just message content but also communication patterns.",
    "**Pung**: A metadata-private messaging system based on PIR.",
    "**Vuvuzela (Messaging System)**: A scalable private messaging system that provides differential privacy for metadata.",
    "**Private Information Retrieval (PIR)**: A cryptographic protocol that allows a user to retrieve an item from a database without the server learning which item was retrieved.",
    "**Mix Network (Mixnet)**: A routing protocol that uses proxy servers to hide the relationship between incoming and outgoing messages.",
    "**Loopix**: A practical and efficient mixnet design.",
    "**NYM (Mixnet)**: A privacy infrastructure that protects against mass surveillance.",
    "**Orchid (VPN)**: A decentralized VPN powered by a blockchain.",
    "**Mysterium Network**: A decentralized P2P VPN.",
    "**Sentinel (dVPN)**: A decentralized VPN protocol built on the Cosmos SDK.",
    "**Peer-to-Peer (P2P) Networking**: A distributed application architecture that partitions tasks or workloads between peers.",
    "**BitTorrent Protocol**: A communication protocol for peer-to-peer file sharing.",
    "**DHT (Distributed Hash Table)**: A class of decentralized distributed systems that provide a lookup service similar to a hash table.",
    "**Kademlia**: A distributed hash table for decentralized peer-to-peer computer networks.",
    "**Chord (Peer-to-Peer)**: A protocol and algorithm for a distributed hash table.",
    "**Pastry (Peer-to-Peer)**: A substrate for self-organizing social peer-to-peer networks.",
    "**Tapestry (Peer-to-Peer)**: A peer-to-peer overlay network which provides location-aware routing and multicasting.",
    "**Gossip Protocol**: A procedure or process of computer-to-computer communication that is based on the way social networks spread information.",
    "**Epidemic Algorithm**: Another name for a gossip protocol.",
    "**Anti-entropy (Gossip)**: A mechanism for reconciling differences between nodes in a gossip network.",
    "**Rumor Spreading (Gossip)**: A mechanism for quickly disseminating new information through a network.",
    "**CRDT (Conflict-free Replicated Data Type)**: A data structure that can be replicated across multiple computers in a network, where the replicas can be updated independently and concurrently.",
    "**Operation-based CRDT vs State-based CRDT**: Two different approaches to implementing CRDTs.",
    "**G-Counter (Grow-only counter)**: A simple CRDT counter that only increases.",
    "**PN-Counter (Positive-Negative counter)**: A CRDT counter that can both increase and decrease.",
    "**G-Set (Grow-only set)**: A simple CRDT set where elements can only be added.",
    "**OR-Set (Observed-Remove set)**: A CRDT set where elements can be added and removed.",
    "**LWW-Element-Set (Last-Write-Wins element set)**: A CRDT set that uses timestamps to resolve conflicts.",
    "**Sequence CRDT (for Collaborative Editing)**: A CRDT designed for ordering elements in a sequence.",
    "**Automerge**: A JSON-like data structure (a CRDT) that can be modified concurrently by different users, and merged again.",
    "**Yjs**: A shared editing framework that uses a highly efficient CRDT implementation.",
    "**Logux**: A client-server framework for building reactive, real-time web apps with a focus on synchronization.",
    "**Gun (Database)**: An open source, cybersecurity and data synchronization framework for P2P web apps.",
    "**OrbitDB**: A serverless, distributed, peer-to-peer database.",
    "**Scuttlebutt (Protocol)**: A decentralized social network protocol.",
    "**ActivityPub**: An open, decentralized social networking protocol based on ActivityPump.",
    "**Mastodon (Social Network)**: A free, open-source self-hosted social networking service.",
    "**Matrix (Protocol)**: An open standard for real-time, interoperable, decentralized communication.",
    "**Session (Messaging App)**: An end-to-end encrypted messenger that minimizes sensitive metadata.",
    "**Briar (Messaging App)**: A messaging app designed for activists, journalists, and anyone else who needs a safe, easy and robust way to communicate.",
    "**Status (Messaging App)**: A private, secure communication tool that combines a messenger, crypto wallet, and Web3 browser.",
    "**Keet**: A peer-to-peer chat application built on top of the Hypercore protocol.",
    "**Hypercore (Protocol)**: A secure, distributed append-only log.",
    "**Dat (Protocol)**: A protocol for sharing data between computers.",
    "**Beaker Browser**: A peer-to-peer web browser with tools to create and host websites.",
    "**IPFS (InterPlanetary File System)**: A protocol and peer-to-peer network for storing and sharing data in a distributed file system.",
    "**Content Addressing (CID)**: Identifying data by its hash rather than its location.",
    "**Merkle DAG (Directed Acyclic Graph)**: A data structure used in IPFS to link content together.",
    "**IPNS (InterPlanetary Name System)**: A system for creating mutable pointers to IPFS content.",
    "**Filecoin**: A decentralized storage network based on IPFS.",
    "**Arweave**: A decentralized storage network that offers permanent data storage.",
    "**Storj**: A decentralized cloud storage platform.",
    "**Sia (SiaCoin)**: A decentralized storage platform secured by blockchain technology.",
    "**MaidSafe (Safe Network)**: An autonomous, decentralized, and serverless data network.",
    "**ZeroNet**: A decentralized, peer-to-peer network based on BitTorrent and Bitcoin technology.",
    "**Holochain**: An open-source framework for creating fully decentralized, peer-to-peer applications.",
    "**IOTA (Tangle)**: A distributed ledger designed to record and execute transactions between machines in the IoT.",
    "**DAG-based Ledgers**: Distributed ledgers that use directed acyclic graphs instead of blockchains.",
    "**Hashgraph**: A distributed ledger technology that uses a 'gossip about gossip' protocol.",
    "**Nano (Currency)**: A digital currency using a block-lattice architecture where every user has their own blockchain.",
    "**Polygon (Layer 2)**: A protocol and a framework for building and connecting Ethereum-compatible blockchain networks.",
    "**Optimistic Rollups**: A layered scaling solution for Ethereum.",
    "**ZK-Rollups**: A scaling solution for Ethereum based on zero-knowledge proofs.",
    "**The Graph (Protocol)**: An indexing protocol for querying networks like Ethereum and IPFS.",
    "**Chainlink (Oracle)**: A decentralized oracle network that provides real-world data to smart contracts on the blockchain.",
    "**ENS (Ethereum Name Service)**: A distributed, open, and extensible naming system based on the Ethereum blockchain.",
    "**NFT (Non-Fungible Token)**: A unique digital identifier that cannot be copied, substituted, or subdivided.",
    "**MetaMask**: A software cryptocurrency wallet used to interact with the Ethereum blockchain.",
    "**Web3.js & Ethers.js**: Libraries for interacting with the Ethereum blockchain.",
    "**Hardhat & Truffle**: Development environments for Ethereum software.",
    "**Solidity**: An object-oriented, high-level language for implementing smart contracts.",
    "**Vyper**: A contract-oriented, pythonic programming language for the Ethereum Virtual Machine (EVM).",
    "**Rust (for Blockchain)**: A language heavily used for building blockchains and smart contracts (e.g. Solana, Polkadot, Near).",
    "**Wasm (in Blockchain)**: Using WebAssembly as a runtime for smart contracts.",
    "**Solana**: A high-performance blockchain supporting builders around the world creating crypto apps that scale.",
    "**Polkadot**: A multi-chain interchange and shared security protocol.",
    "**Cosmos (The Hub)**: An ecosystem of blockchains that can scale and interoperate with each other.",
    "**Near Protocol**: A decentralized development platform where developers can host serverless applications and smart contracts.",
    "**Cardano**: A proof-of-stake blockchain platform that says its goal is to allow 'changemakers, innovators and visionaries' to bring about positive global change.",
    "**Stellar**: An open-source, decentralized network that connects world’s financial infrastructure.",
    "**Ripple (XRP)**: A technology that acts as both a cryptocurrency and a digital payment network for financial transactions.",
    "**Hyperledger Fabric**: A foundation for developing applications or solutions with a modular architecture.",
    "**Quorum (Blockchain)**: An enterprise-focused version of Ethereum.",
    "**Corda (R3)**: An open-source distributed ledger platform for business.",
    "**Enterprise Blockchain**: Any blockchain technology used for a private or consortium-based business application.",
    "**Tokenization**: The process of converting some asset into a digital unit that can be moved, recorded, or settled on a blockchain.",
    "**Stablecoins (USDT, USDC, DAI)**: Cryptocurrencies where the price is designed to be pegged to a cryptocurrency, fiat money, or to exchange-traded commodities.",
    "**DeFi (Decentralized Finance)**: An umbrella term for financial services on public blockchains.",
    "**DEX (Decentralized Exchange)**: A type of cryptocurrency exchange which allows for direct peer-to-peer cryptocurrency transactions to take place online.",
    "**AMM (Automated Market Maker)**: A type of decentralized exchange protocol that relies on a mathematical formula to price assets.",
    "**Liquidity Pools**: A collection of funds locked in a smart contract.",
    "**Yield Farming**: The practice of staking or lending crypto assets in order to generate high returns or rewards in the form of additional cryptocurrency.",
    "**Flash Loans**: A type of uncollateralized lending used in some decentralized finance (DeFi) protocols.",
    "**DAOs (Decentralized Autonomous Organizations)**: An organization represented by rules encoded as a computer program that is transparent, controlled by the organization members and not influenced by a central government.",
    "**On-chain vs Off-chain Governance**: Whether governance decisions are executed automatically via smart contracts or manually.",
    "**EIP (Ethereum Improvement Proposal)**: A design document providing information to the Ethereum community, or describing a new feature for Ethereum or its processes or environment.",
    "**BIP (Bitcoin Improvement Proposal)**: A design document providing information to the Bitcoin community, or describing a new feature for Bitcoin or its processes or environment.",
    "**Whales (Crypto)**: Entities that hold a large amount of a specific cryptocurrency.",
    "**HODL**: A term derived from a misspelling of 'hold' that refers to buy-and-hold strategies in the context of bitcoin and other cryptocurrencies.",
    "**Gas (Ethereum)**: The fee required to successfully conduct a transaction or execute a contract on the Ethereum blockchain platform.",
    "**Mempool**: A set of all transactions that have not yet been confirmed by the network and are waiting to be included in a block.",
    "**Mining vs Staking**: Two different mechanisms for validating transactions on a blockchain.",
    "**Proof of Work (PoW)**: A form of cryptographic zero-knowledge proof in which one party proves to others that a certain amount of a specific computational effort has been expended.",
    "**Proof of Stake (PoS)**: A cryptocurrency consensus mechanism for processing transactions and creating new blocks in a blockchain.",
    "**Delegated Proof of Stake (DPoS)**: A PoS consensus algorithm that uses a voting system to select validators.",
    "**Proof of Authority (PoA)**: A consensus mechanism in a blockchain which delivers comparatively fast transactions through a consensus mechanism based on identity as a stake.",
    "**Proof of History (PoH)**: A consensus mechanism used by Solana to create a historical record that proves that an event has occurred at a specific moment in time.",
    "**Proof of Burn (PoB)**: A method for distributed consensus and a way to bootstrap a new cryptocurrency by 'burning' existing tokens.",
    "**Proof of Capacity (PoC)**: A consensus mechanism that uses a computer's hard drive space for mining.",
    "**Proof of Elapsed Time (PoET)**: A consensus mechanism algorithm that is often used on the permissioned blockchain networks to decide the mining rights or the block winners on the network.",
    "**51% Attack**: A potential attack on a blockchain network, where a single entity or organization is able to control the majority of the hash rate, potentially causing a network disruption.",
    "**Double Spending**: A potential flaw in a digital cash scheme in which the same single digital token can be spent more than once.",
    "**Fork (Blockchain)**: A change in the protocol of a blockchain network.",
    "**Soft Fork**: A backwards-compatible change to a blockchain protocol.",
    "**Hard Fork**: A non-backwards-compatible change to a blockchain protocol.",
    "**Blockchain Interoperability**: The ability of different blockchain systems to communicate and interact with each other.",
    "**Atomic Swaps**: A smart contract technology that enables the exchange of one cryptocurrency for another without using a centralized intermediary.",
    "**Sidechains**: A separate blockchain that is attached to its parent blockchain using a two-way peg.",
    "**State Channels**: A technique for performing transactions and other state updates off-chain.",
    "**Payment Channels (Lightning Network)**: A specific type of state channel used for off-chain payments.",
    "**L2 (Layer 2) Scaling**: A collective term for solutions designed to help scale your application by handling transactions off the Ethereum Mainnet (Layer 1).",
    "**Zero-Knowledge Proofs (zk-SNARKs & zk-STARKs)**: Cryptographic proofs that allow one party to prove to another that they know a piece of information without revealing any details about that information.",
    "**On-chain Data Storage**: Storing data directly on the blockchain ledger.",
    "**Off-chain Data Storage (IPFS, Arweave)**: Storing larger amounts of data in a decentralized file system and only storing a hash on the blockchain.",
    "**Immutable Data**: Data that cannot be changed once it is written.",
    "**Verifiable Data**: Data that can be proven to be accurate and authentic.",
    "**Self-Describing Data**: Data that includes its own schema or metadata.",
    "**Causal Consistency**: A consistency model that ensures that operations that are causally related are seen by all processes in the same order.",
    "**Linearizability**: A consistency model where each operation appears to take place instantaneously at some point between its invocation and its response.",
    "**Sequential Consistency**: A consistency model that requires that the result of any execution be the same as if the operations of all the processors were executed in some sequential order.",
    "**Strict Consistency**: The strongest consistency model, where any read to a data item x returns the value stored by the most recent write operation on x.",
    "**Tunable Consistency (Cassandra)**: The ability to set the consistency level for each read or write operation.",
    "**Hotspot (Database)**: A specific data item or partition that receives significantly more traffic than others.",
    "**Thundering Herd Problem**: A phenomenon that occurs when a large number of processes waiting for an event are awoken when the event occurs, but only one process is able to handle the event.",
    "**Cache Stampede**: A type of cascading failure that can occur when massively parallel computing systems with caching layers come under very high load.",
    "**Negative Caching**: The practice of caching the absence of an item.",
    "**Warm-up (Cache)**: Pre-filling a cache with data that is likely to be requested.",
    "**Cache Invalidation**: The process of removing entries from a cache when the underlying data changes.",
    "**LRU (Least Recently Used)**: A cache eviction policy that removes the item that was least recently accessed.",
    "**LFU (Least Frequently Used)**: A cache eviction policy that removes the item that was least frequently accessed.",
    "**FIFO (First-In, First-Out) Cache**: A cache eviction policy that removes the item that was added first.",
    "**ARC (Adaptive Replacement Cache)**: A self-tuning cache eviction policy that balances between LRU and LFU.",
    "**Two-Q (2Q) Algorithm**: A cache eviction policy that uses two queues to achieve a performance similar to ARC but with less overhead.",
    "**TinyLFU**: A highly efficient cache admission and eviction policy.",
    "**Caffeine Cache**: A high-performance, near-optimal Java caching library based on TinyLFU.",
    "**Window TinyLFU (W-TinyLFU)**: The specific admission policy used by Caffeine.",
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 501 - 1000\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+501}. {entry}\n")
