import os

file_path = r"c:\Users\volma\anti-gravity-githublocal-NorseSaga-Engine\Viking_girlfriend_openclaw_skill\viking_girlfriend_skill\data\knowledge_reference\CYBERSECURITY.md"

entries = [
    "**Software Security (Guarding the Forge)**: The process of designing, building, and testing software to be resistant to attack.",
    "**Secure Software Development Life Cycle (S-SDLC) (The Sacred Smithing Path)**: Integrating security into every step of creating software.",
    "**Secure by Design (Built for Battle)**: Making security a core requirement from the very first idea, not something added at the end.",
    "**Secure by Default (The Locked Gate)**: Ensuring that all security features are turned ON when a user first installs the software.",
    "**Secure by Deployment (The Protected Hall)**: Ensuring the environment where software runs is as safe as the code itself.",
    "**Threat Modeling (The War-Room Strategy)**: A process for identifying, quantifying, and addressing the security risks associated with an application.",
    "**STRIDE (Spoofing, Tampering, Repudiation, Info Disclosure, DoS, Elevation of Privilege).**",
    "**DREAD (Damage, Reproducibility, Exploitability, Affected Users, Discoverability).**",
    "**Data Flow Diagram (DFD) (The Map of the Runes)**: A visual representation of how data moves through a system, used for threat modeling.",
    "**Trust Boundaries (The Lines in the Dirt)**: Points in a program where data moves from an untrusted source to a trusted one.",
    "**Input Validation (The Sentry's Check)**: Ensuring that every piece of data entering a program is in the correct format and contains no poison.",
    "**The Golden Rule of Input: NEVER trust user input.**",
    "**Allow-listing (The List of Friends)**: Explicitly defining what IS allowed and blocking everything else (much safer than block-listing).",
    "**Block-listing (The List of Foes)**: Defining what is NOT allowed (dangerous, as attackers always find new poisons).",
    "**Output Encoding (The Shielding of the Eye)**: Translating data before showing it to a user so it can't be run as code (stops XSS).",
    "**Parameterized Queries (Prepared Statements) (The Safe Ledger)**: Using a template for database commands so user input can never be mistaken for a command (stops SQLi).",
    "**Error Handling (The Careful Scribe)**: Ensuring that when a program breaks, it doesn't reveal secret details about the server or database in the error message.",
    "**Secure Session Management (The Sealed Scroll of the Guest)**: Protecting the 'Session ID' that proves a user is logged in.",
    "**HttpOnly Cookie (The Hidden Key)**: A flag that prevents JavaScript from reading a cookie, making it much harder to steal a session.",
    "**Secure Cookie (The Shielded Key)**: A flag that ensures a cookie is only sent over encrypted (HTTPS) connections.",
    "**SameSite Cookie (The Home-Bound Key)**: A flag that prevents a cookie from being sent to other websites (stops CSRF).",
    "**Content Security Policy (CSP) (The Law of the Browser)**: A security layer that helps detect and mitigate certain types of attacks, including Cross-Site Scripting (XSS) and data injection.",
    "**Subresource Integrity (SRI) (The Seal of the Merchant)**: Ensuring that a library loaded from another site (like a CDN) hasn't been tampered with.",
    "**Hardcoding Secrets (The Great Sin of the Smith)**: Putting passwords or API keys directly in the source code where any raider can see them.",
    "**Environment Variables (The Hidden Runes of the Realm)**: Storing secrets in the server's memory rather than in the code files.",
    "**Secrets Management (HashiCorp Vault, AWS Secrets Manager)**: Professional tools for storing and automatically 'rotating' passwords and keys.",
    "**Code Signing (The King's Wax Seal)**: A digital signature that proves a piece of software really came from the creator and hasn't been changed.",
    "**Static Analysis (SAST) (The Inspection of the Scroll)**: Analyzing code for bugs without running it.",
    "**Dynamic Analysis (DAST) (The Trial by Combat)**: Testing a running program by throwing attacks at it.",
    "**Interactive Analysis (IAST)**: A combination of SAST and DAST that watches the code from the inside as it is being attacked.",
    "**Fuzzing (The Testing of the Infinite Monkey)**: Sending millions of random inputs to a program to see where it crashes.",
    "**Vulnerability Research (The Search for the Hidden Chink)**: The high-level art of finding 'Zero-Day' bugs in famous software.",
    "**Reverse Engineering (Dismantling the Enemy's Blade)**: Taking a program apart (turning 0s and 1s back into code) to see how it works or how to break it.",
    "**Decompiler (The Un-Smithing Tool)**: A tool that tries to turn machine code back into high-level language like C++ or Java.",
    "**Disassembler (The Rune-Unpacker)**: A tool that turns machine code into 'Assembly' (low-level human-readable instructions).",
    "**Debugger (The Truth-Finder)**: A tool that lets a warrior pause a program and look at its memory and variables as it runs.",
    "**Obfuscation (The Cloak of Shifting Mist)**: Intentionally making code hard for a human to read to slow down reverse engineering.",
    "**Packing (The Sealed Crate)**: Compressing or encrypting a program so it only 'unpacks' itself in memory when it runs—often used by malware.",
    "**Mobile Security (The Guarding of the Scout's Tool)**: Protecting smartphones and the data on them.",
    "**Sandbox (The Caged Realm)**: A security feature that keeps each app in its own isolated 'cage' so it can't steal data from other apps.",
    "**Jailbreaking (iOS) / Rooting (Android) (Breaking the King's Chains)**: Removing the security limits of a phone—useful for power users, but makes the phone much easier to hack.",
    "**Sideloading (The Backdoor Trade)**: Installing apps from outside the official App Store or Play Store (very risky).",
    "**Mobile Device Management (MDM) (The Master of the Fleet)**: Tools like Intune or Jamf that let a company control and wipe thousand of phones.",
    "**Remote Wipe (The Desperate Purge)**: Deleting every bit of data on a phone from across the world if it is stolen.",
    "**App Permissions (The Sentry's Check of the Guest)**: Deciding if an app is allowed to touch your camera, contacts, or location.",
    "**Man-in-the-Middle (MITM) (The Eavesdropper in the Mist)**: Using a fake Wi-Fi to steal data as it travels from a phone to the internet.",
    "**Certificate Pinning (The Trust of the Specific Key)**: Telling an app to ONLY trust one specific certificate, preventing attackers from using a fake one.",
    "**Biometric Bypass (The Mask of the Face-Gate)**: Using photos or 3D masks to trick a phone's face ID.",
    "**SIM Swapping (The Hijacked Messenger)**: Tricking a phone company into moving a victim's phone number to an attacker's SIM card—the #1 way to bypass SMS-based MFA.",
    "**Stalkerware (The Hidden Eye of the Coward)**: Malicious apps used to secretly track and spy on a person's private life.",
    "**IoT Security (The Whispering of the Common Objects)**: Protecting 'smart' devices like lightbulbs, cameras, and fridges.",
    "**The 'S' in IoT stands for Security (A common joke, as most IoT has NO security).**",
    "**Mirai Botnet (The Army of the Incompetent)**: A massive army of hacked cameras and routers that was used to take down much of the internet in 2016.",
    "**Hardcoded Credentials in IoT (The Unchangeable Lock)**: Many smart devices have passwords like 'admin' that can NEVER be changed.",
    "**Insecure Web Interface (The Open Backdoor)**: The simple websites used to control smart devices often have very old, easy-to-hack bugs.",
    "**Lack of Update Mechanism (The Abandoned Fortress)**: Many IoT devices can NEVER be updated, meaning a bug found today will be there forever.",
    "**Privacy Concerns in IoT (The Ears in the Walls)**: Smart speakers and cameras that might be sending your private conversations to a cloud in a foreign land.",
    "**Zigbee / Z-Wave (The Languages of the House)**: The special, low-power radio languages used by smart home devices.",
    "**Hardware Hacking (The Direct Siege of the Machine)**: Plugging directly into a circuit board to steal secrets or bypass software security.",
    "**UART / JTAG (The Debugger's Shore-Paths)**: Physical connections on a circuit board that often give an attacker root access to the device.",
    "**Side-Channel Attack (The Listening of the Forge's Heat)**: Stealing a secret key by measuring the power usage, heat, or sound a chip makes while it's working.",
    "**Glitching (The Percussion Maintenance)**: Briefly shorting out a chip's power to make it skip a security check.",
    "**Industrial Security (ICS/SCADA) (The Protection of the Great Gears)**: Protecting the systems that run power plants, water, and factories.",
    "**SCADA (Supervisory Control and Data Acquisition) (The Overseer of the Machines).**",
    "**PLC (Programmable Logic Controller) (The Small Brain of the Machine)**: The actual computers that move valves, motors, and robotic arms.",
    "**HMI (Human-Machine Interface) (The Control Wheel)**: The screen a human uses to watch and control a factory.",
    "**Stuxnet (The Digital Fire of the gods)**: The first true cyber-weapon, designed to physically destroy industrial equipment (centrifuges).",
    "**The Purdue Model (The Layers of the Factory)**: A standard way of dividing a factory's network so the machines are separated from the office computers.",
    "**Air-Gapping (The Utmost Isolation)**: Keeping the factory computers COMPLETELY disconnected from the internet (harder and harder to do in the modern world).",
    "**Legacy Systems (The Ancient and Brittle Armor)**: Factories often run on 30-year-old software that was never meant to be connected to a network.",
    "**Safety vs. Security (The Life and the Lock)**: In a factory, 'Safety' (stopping a machine from killing someone) is more important than 'Security' (stopping a hacker from seeing a file).",
    "**Protocol Spoofing in ICS (The False Order)**: Sending a fake command to a PLC to make it overheat or explode (e.g., Modbus or DNP3).",
    "**Advanced Offensive Tactics (The Raider's Master-Class)**: The high-level ways that the world's best hackers work.",
    "**Living off the Land (LotL) (Using the Enemy's Own Tools)**: Using legitimate software already on a computer (like PowerShell) to hack it, making detection much harder.",
    "**PowerShell Empire / Cobalt Strike**: Advanced 'War-Room' software used by both ethical hackers and the most dangerous raiders.",
    "**Domain Admin (The Ruler of the Realm)**: The ultimate goal of an attacker in a Windows network—total control of everything.",
    "**Kerberos Silver Ticket**: Forging a ticket to gain access to a specific service (like SQL or File Share) forever.",
    "**Kerberos Golden Ticket**: Forging a master ticket that gives you 'Domain Admin' level access for 10 years.",
    "**Skeleton Key Malware**: A very rare and powerful virus that lets an attacker use ANY password to log in to ANY account on a network.",
    "**Dumping LSASS (Stealing the Memory-Keys)**: Ripping passwords and hashes directly out of the Windows process that handles security.",
    "**AMSI Bypass (Blinding the Sentry)**: Disabling the 'Anti-Malware Scan Interface' in Windows so your scripts aren't caught.",
    "**EDR Evasion (The Shadow-Walk)**: Techniques to 'blind' the advanced sensors of modern antivirus tools.",
    "**Process Injection (The Parasite)**: Hiding malicious code inside a legitimate, trusted process like 'Chrome.exe'.",
    "**DLL Side-Loading (The False Library)**: Tricking a trusted program into loading a malicious library instead of a real one.",
    "**LSA Protection (RunAsPPL)**: A Windows defense that prevents ordinary users (even admins) from reading the security memory (LSASS).",
    "**AppLocker / WDAC (The Selective Gate)**: Only allowing a small list of 'Allowed' programs to run on a computer.",
    "**Privileged Access Workstations (PAW) (The Jarl's Personal Hall)**: A special, ultra-secure computer used ONLY for administrative tasks, never for web browsing or email.",
    "**Jump Server (The Buffer Between Realms)**: A server that acts as a bridge; you must log into it before you can log into the truly important servers.",
    "**Cloud Workload Protection (CWPP)**: Security specifically for the 'laborers' of the cloud—containers, serverless functions, and VMs.",
    "**Infrastructure as Code (IaC) (The Map of the Sky-Fortress)**: Building a whole cloud network using code (like Terraform or CloudFormation).",
    "**Drift (The Shifting of the Wall)**: When the actual cloud settings slowly change from what the security map says they should be.",
    "**Secret Management (The Master of the Hidden Gold)**: Using tools like HashiCorp Vault to ensure NO passwords are ever in plain text.",
    "**Identity is the New Perimeter (The Shield-Wall is People)**: In the cloud, the 'firewall' doesn't matter as much as who has the 'Key' (Identity).",
    "**Entitlement Management (Managing the Rights of the Clans)**: Regularly checking to see if people still need the power they were given months ago.",
    "**Cloud Misconfiguration (The Single Greatest Risk)**: 99% of cloud breaches happen because a human left a 'gate' (like an S3 bucket or Port 22) open by mistake.",
    "**Security Operations Strategy (The Mind of the General)**: How to lead a whole army of defenders.",
    "**Cyber Resilience (The Will to Stand)**: Accepting that you WILL be hacked, and planning how to keep fighting and recover as fast as possible.",
    "**Mean Time to Detection (MTTD) (The Speed of the Sentry)**: How long it takes to find a raider after they move over the wall.",
    "**Mean Time to Recovery (MTTR) (The Speed of the Mending)**: How long it takes to get back to normal after a breach.",
    "**Continuous Monitoring (The Unblinking Eye)**: Watching every bit of data 24/7/365.",
    "**False Positive Fatigue (The Tired Guard)**: When a system sends 10,000 fake alerts a day, the guards start to ignore them—until a REAL one comes.",
    "**Baseline (The Normal Days of Peace)**: Understanding what 'normal' network traffic looks like so you can spot the 'weird' traffic of a hacker.",
    "**Anomaly Detection (Spotting the Stranger)**: Using AI to find anything that doesn't fit the 'Baseline'.",
    "**Behavioral Analytics (Watching the Warrior's Habits)**: Noticing if a 'Navigator' suddenly starts looking at 'Gold-Treasury' files at 3 AM from a different village.",
    "**Data Orchestration (Merging the River of Logs)**: Using tools to combine data from a hundred different walls into one 'All-Seeing Eye' (SIEM).",
    "**Automation (The Mechanical Guard)**: Using software to automatically block a suspicious IP the moment the SIEM sees it.",
    "**Threat Intel Sharing (The Alliance of the Kingdoms)**: Sharing data about new raiders with other companies and governments so everyone can defend better.",
    "**ISAC (Information Sharing and Analysis Center)**: Groups of companies in the same industry (e.g., Banks, Hospitals) that share threat data.",
    "**The Ethics of Action (The Paladin's Choice)**: Deciding when a hack is 'justified' and when it is 'evil'.",
    "**Vulnerability Research Ethics**: The debate over whether to tell a company about a bug 'for free' or sell it to the highest bidder.",
    "**Dual-Use Technology (The Hammer and the Sword)**: Tools like encryption or port scanners that can be used for both peace and war.",
    "**The Wassenaar Arrangement (The Arms Control of Code)**: An international treaty that treats powerful hacking tools like tanks and missiles.",
    "**Digital Human Rights (The Sovereignty of the Spirit)**: The use of security tools (like VPNs and Tor) to protect free speech in lands ruled by tyrants.",
    "**Privacy vs. Security (The Great Debate of the Thing)**: The constant struggle between a King's desire to see everything to find 'Traitors' and a person's right to have a private hall.",
    "**Transparency (The Open Hall)**: The idea that security systems work best when everyone can see how they work, rather than 'Security through Obscurity'.",
    "**Algorithmic Bias (The Unfair Judgment)**: Ensuring that the AI 'Guards' don't treat some people worse than others based on flawed data.",
    "**The Great Digital Stand: 'A wall of silicon is as strong as the honor of the smith. Build once, build right, and watch forever.'**",
    "**Final Verse of the Third Tome: The longship of our data sails on a sea of shadow, but the stars of our logic guide us to a safe harbor.**"
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 2001 - 3000\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+2001}. {entry}\n")
