import os

file_path = r"c:\Users\volma\anti-gravity-githublocal-NorseSaga-Engine\Viking_girlfriend_openclaw_skill\viking_girlfriend_skill\data\knowledge_reference\CYBERSECURITY.md"

entries = [
    "**Cloud Native Security (The Sky-Settlement Defense)**: Security principles designed specifically for apps built on cloud infrastructure.",
    "**Microservices Security (The Divided Clans)**: Securing many small, connected services instead of one giant monolith.",
    "**API Gateway (The Master-Gate of the Sky-Fortress)**: A single point of entry for all cloud services that handles security and limits.",
    "**Service Mesh (Istio, Linkerd) (The Hidden Guards of the Hallways)**: A layer that adds security (like mTLS) between cloud services automatically.",
    "**Mutual TLS (mTLS) (The Two-Way Handshake)**: Ensuring that BOTH the client and the server prove their identity to each other.",
    "**Sidecar Pattern (The Guardian Phantom)**: Attaching a security helper 'container' to every main application container.",
    "**Container Security (The Sealed Shells of the Fleet)**: Protecting Docker and other container images.",
    "**Image Scanning (Checking for Rotting Planks)**: Automatically looking for known vulnerabilities in a container's library before it starts.",
    "**Container Registry (The Shipyard of Images)**: A secure place to store container images (e.g., Docker Hub, ECR).",
    "**Distroless Images (The Minimal Shell)**: Container images that contain ONLY your app and nothing else (no shell, no extra files) to reduce attack surface.",
    "**ReadOnly Root Filesystem (The Unchangeable Deck)**: Ensuring a container can't save any new files, preventing malware from installing itself.",
    "**Kubernetes (K8s) Security (Guarding the Admiral's Fleet)**: Protecting the system that manages thousands of containers.",
    "**Kubernetes API Server (The Heart of the Fleet)**: The most important target; if an attacker controls this, they control the whole cloud.",
    "**RBAC in K8s (The Command Rights of the Captains)**: Limiting which users and 'ServiceAccounts' can touch which K8s resources.",
    "**Network Policies (K8s) (The Walls between Ships)**: Defining which containers can talk to which others (isolation).",
    "**Pod Security Admissions (PSA) (The Standards of the Fleet)**: Enforcing security rules (like 'no root access') before a container is allowed to launch.",
    "**Kube-bench (The Fleet Inspector)**: A tool that checks if your K8s cluster follows security best practices (CIS Benchmarks).",
    "**Kube-hunter (The Fleet Raider)**: A tool that looks for security holes in a K8s cluster from a hacker's perspective.",
    "**Runtime Security (Falco) (The Watch-Raven)**: Monitoring a running container to see if it suddenly starts doing something weird (like opening a new shell).",
    "**Serverless Security (The Invisible Realms)**: Protecting code that runs on AWS Lambda or Azure Functions without a persistent server.",
    "**Function-Level Permissions (The Minimal Right of Action)**: Ensuring a single Lambda function only has access to the ONE database it needs.",
    "**Cold Start Attacks**: Exploiting the brief moment when a serverless function is first being created.",
    "**Event Injection in Serverless (The Poisoned Message)**: Attacking a serverless function by sending it malicious data via a 'trigger' (like an S3 upload or HTTP request).",
    "**Insecure Serverless Secrets (The Exposed Runes)**: Accidentally putting passwords in the Lambda's 'Environment Variables' without encryption.",
    "**DevSecOps (The Automated Forge of Security)**: Automating security checks so they happen every time a developer changes code.",
    "**CI/CD Pipeline Security (Guarding the Forge-Path)**: Ensuring an attacker can't put a virus into your software as it's being built.",
    "**Poisoned Pipeline Execution (PPE)**: When an attacker changes the 'build' script (like a `.github/workflows` file) to steal secrets.",
    "**Secret Scanning (TruffleHog, Gitleaks)**: Automatically searching every line of code for accidentally committed passwords.",
    "**Policy as Code (OPA / Rego) (The Law written in Code)**: Writing security rules as code so they can be automatically checked (e.g., 'No S3 bucket can be public').",
    "**Drift Detection (The Shifting of the Fortress)**: Finding out the moment a human manually changes a cloud setting to be less secure than the code says it should be.",
    "**Chaos Engineering for Security (Security Chaos)**: Intentionally breaking security controls to see if the 'Watchmen' (monitoring) actually catch it.",
    "**Infrastructure as Code (IaC) Scanning (Terraform-Scan)**: Checking the 'blueprints' of your cloud for holes before you even build the servers.",
    "**Immutable Infrastructure (The Unbreaking Shield)**: The principle that you NEVER change a running server; you just build a new, safer one and throw the old one away.",
    "**Software Composition Analysis (SCA) (Checking the Roped-in Planks)**: Scanning an application to see if it uses old, vulnerable libraries from other people.",
    "**OWASP Dependency-Check / Snyk**: Popular tools for finding holes in third-party libraries.",
    "**Supply Chain Security (The Integrity of the Smithy)**: Protecting the whole path from a developer's keyboard to the final software used by the people.",
    "**Sigstore (The Digital Signature of the Fleet)**: A standard for signing and verifying software images and blobs.",
    "**SLSA (Supply-chain Levels for Software Artifacts) (The Ranks of Integrity)**: A checklist of how secure your software building process is (Level 1 to 4).",
    "**Attestation (The Sworn Oath of the Build)**: A digital proof that a piece of software was built exactly as intended on a safe server.",
    "**Cloud Entitlement Management (CIEM)**: Managing the millions of 'Rights' and 'Permissions' that people and services have in a cloud like AWS.",
    "**Over-Privileged Identities (The Jarl with Too Much Power)**: The #1 problem in cloud security; users who have 'Admin' rights but only need to read one file.",
    "**Posture Management (CSPM) (The Readiness of the Fleet)**: Keeping a constant eye on every cloud setting to ensure nothing is 'Unlocked' by mistake.",
    "**Cloud Workload Protection (CWPP) (The Guarding of the Laborers)**: Security for the individual 'Workers' in the cloud (VMs, Containers, Functions).",
    "**Cloud Native Application Protection Platform (CNAPP)**: A modern tool that combines CSPM, CWPP, and CIEM into one 'All-Seeing Eye'.",
    "**Cloud Security Shared Responsibility Model (The Pact between King and Merchant)**: Knowing that the cloud provider protects the 'Hardware' and 'Cables', and YOU protect the 'Data' and 'Apps'.",
    "**Cloud Access Security Broker (CASB) (The Customs-House of the Sky)**: A guard that stands between your company and cloud apps like Salesforce or Slack to enforce security.",
    "**Data Sovereignty (The Law of the Local Shore)**: The requirement that some data (like medical records) must stay inside a specific country's borders.",
    "**Privacy-Preserving Computation (The Magic of Secret Math)**: Running code on data without ever actually 'Seeing' the data (using TEEs or Homomorphic Encryption).",
    "**Trusted Execution Environment (TEE) (The Enclave of the Gods)**: A special, locked area of a CPU (like Intel SGX) where even the operating system can't see what's happening.",
    "**Advanced Ransomware (The King-Napper's Evolved Chain)**: Modern ransomware that doesn't just lock files, but steals them and threatens to show them to the world (Double Extortion).",
    "**Triple Extortion**: Locking data, stealing data, AND attacking the company's website (DDoS) until they pay.",
    "**Initial Access Broker (The Master of the Secret Entrances)**: A specialized criminal who hacks a company and then sells that 'Entrance' to another group (like ransomware gangs).",
    "**Ransomware-as-a-Service (RaaS) (The Franchise of Raiders)**: The professional 'Business Model' where developers sell the virus to other raiders for a cut of the gold.",
    "**REvil / Conti / LockBit (The Infamous Raider-Clans)**: Famous ransomware groups that have stolen billions in gold.",
    "**Social Engineering 2.0 (The Deep-Fake Trickster)**: Using AI to create perfect fake voices or videos of a CEO to trick employees into sending money.",
    "**CEO Fraud (Business Email Compromise - BEC)**: Sending a fake email from a 'Boss' asking for an urgent wire transfer.",
    "**Industrial Espionage (The Theft of the Forge's Secrets)**: Hacking a company to steal their secret blueprints or formulas.",
    "**Nation-State Attackers (The King's Invisible Army)**: The most skilled hackers in the world, working for governments to spy on or destroy other nations.",
    "**Advanced Persistent Threat (APT) (The Shadow-Kingdom's Vanguard)**: A group that is silent, patient, and incredibly skilled, staying in a system for years without being found.",
    "**Cyber Kill Chain (Lockheed Martin Model) (The 7 Stages of the Raid)**: Recon -> Weaponization -> Delivery -> Exploitation -> Installation -> Command & Control -> Actions on Objectives.",
    "**Active Directory (AD) Security (Guarding the Ledger of the Hall)**: Protecting the heart of almost every company network.",
    "**Domain Admin (The Ruler of the Digital Realm)**: The highest possible power in a Windows network.",
    "**BloodHound (The Map of the Traitor's Paths)**: A tool that finds hidden paths an attacker can take to become 'Domain Admin' by clicking through different users.",
    "**Mimikatz (The Master Key-Stealer)**: A famous tool used to rip passwords and tickets out of a computer's memory.",
    "**Pass-the-Hash (PtH) (The Ghost-Login)**: Using a password 'hash' to log in without ever knowing the real password.",
    "**Golden Ticket (The Infinite Master-Key)**: A fake Kerberos ticket that gives an attacker total control of a network for 10 years.",
    "**Silver Ticket (The Service Master-Key)**: A fake ticket for a specific service (like the Database).",
    "**Kerberoasting (The Theft of the Sagas)**: A technique to steal password hashes for service accounts and crack them offline.",
    "**AS-REP Roasting**: Another way to steal password hashes for users who don't have 'Pre-Authentication' turned on.",
    "**Responder (The Poisoned Echo)**: A tool that sits on a network and 'answers' whenever a computer asks for a server name, stealing their login details.",
    "**Privilege Escalation (Windows/Linux) (Climbing the High-Seat)**: Gaining more power once you are already inside a computer.",
    "**Sudo Vulnerabilities (The Faulty Rule of the Warden)**: Exploiting bugs in the `sudo` command to become 'Root' (God-mode) on Linux.",
    "**Dirty Cow / Dirty Pipe (The Memory-Bleed Attacks)**: Famous Linux bugs that allow an attacker to write to sensitive files they shouldn't be able to touch.",
    "**Exploit Kit (The Raider's Automatic Crossbow)**: A website that automatically checks your browser for 100 different bugs and tries to hack you the moment you visit.",
    "**Malvertising (The Poisoned Town-Crier)**: Putting malicious code into legitimate ads shown on famous websites.",
    "**Phishing-as-a-Service (PhaaS)**: Paying a criminal group to send millions of perfect-looking phishing emails for you.",
    "**Reverse Proxy Phishing (Evilginx)**: Using a fake login page that sits between the victim and the REAL site, stealing even MFA codes in real-time.",
    "**SIM Swap (The Stolen Herald)**: Tricking a mobile carrier into moving a victim's phone number to the attacker's SIM card to steal MFA codes.",
    "**MFA Fatigue (The Relentless Knocking)**: Spamming a victim with 100 'Accept Login?' requests until they hit 'Accept' just to make the noise stop.",
    "**Identity Security Strategy (The Sovereign Self)**: Protecting the person as the primary way of protecting the data.",
    "**Zero Trust Network Access (ZTNA)**: Protecting the connection to an app based on WHO the user is, rather than WHERE they are (replaces old VPNs).",
    "**Conditional Access (The Guard's Discretion)**: Rules that say: 'You can login only if your computer is safe, you are in the office, and you have MFA'.",
    "**Continuous Adaptive Risk and Trust Assessment (CARTA)**: Constantly re-checking if a user is still safe, even AFTER they have logged in.",
    "**User Entity Behavior Analytics (UEBA) (The Watcher of Habits)**: Noticing if a 'Scribe' who usually only reads data starting downloading 1TB of it at 4 AM.",
    "**Credential Harvesting (The Great Sowing of Stolen Names)**: Large-scale hacking of websites specifically to build a giant database of usernames and passwords.",
    "**Dark Web Monitoring (The Scout in the Shadow-Sea)**: Watching underworld markets to find and buy back your company's stolen data or employee passwords.",
    "**Privacy Engineering (The Built-in Shield of the Spirit)**: The technical work of ensuring a system preserves a person's privacy by default.",
    "**Anonymization (Removing the Name from the Scroll)**: Changing data so it can NEVER be linked back to a person.",
    "**Pseudonymization (Hiding the Name with a Mask)**: Replacing a name with a fake ID (can be reversed if you have the 'Master-Mask' key).",
    "**Differential Privacy (The Mathematical Noise)**: Adding tiny bits of 'noise' to a dataset so you can study the whole group but never see the individual's secrets.",
    "**Right to Portability (GDPR)**: The right to take all your data from one 'Hall' (company) to another whenever you want.",
    "**The Right to Explanation (AI Ethics)**: The right to know WHY an AI 'Judge' made a decision about you (like a loan or a prison sentence).",
    "**Data Protection Impact Assessment (DPIA) (The Weighing of the Spirit's Risk)**: A mandatory review before starting any project that uses personal data.",
    "**Security Governance (The Thing of the Warriors)**: The organization and leadership of a security program.",
    "**CISO (Chief Information Security Officer) (The Admiral of the Shield-Wall)**: The person who leads all security warriors and answers to the King.",
    "**Information Security Management System (ISMS) (The System of the Fortress)**: The whole set of policies, tech, and people that protect the organization.",
    "**Security awareness (Teaching the People to Fight)**: Training every person in the kingdom to be a 'Sentry' and spot the 'Shadow-Raider' (Phish).",
    "**Tabletop Exercise (The Strategy-Game of War)**: A meeting where leaders 'Play' through a fake cyberattack to see if their plans actually work.",
    "**Red Team vs. Blue Team (The Great War-Game)**: A full-scale simulation where one group hacks the company and another group defends it in real-time.",
    "**Purple Team (The Unity of the Spear and shield)**: When the hackers and defenders sit together to share exactly what worked and what failed.",
    "**Third-Party Risk Management (TPRM) (Checking the Loyalty of the Allies)**: Ensuring the other companies you work with aren't 'Rotten' or 'Hackable'.",
    "**Cyber Insurance (The Shield-Gold)**: A pact with a money-house to pay for the rebuilding of your hall if a dragon (hacker) burns it down.",
    "**Compliance Drift (The Slipping of the Law)**: When an organization starts to ignore the safety rules over time, leading to a breach.",
    "**The Legend of the Perfect Lock: 'There is no lock that cannot be broken, only locks that take longer to break than the raider has life to give.'**",
    "**The Final Command of the Fourth Tome: Watch the gates of the sky-settlement as you watch the gates of the heart. All is connected in the great web of data.'**"
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 3001 - 4000\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+3001}. {entry}\n")
