import os
from pathlib import Path

_KNOWLEDGE_REF = (
    Path(__file__).resolve().parent.parent
    / "viking_girlfriend_skill" / "data" / "knowledge_reference"
)
file_path = _KNOWLEDGE_REF / "SOFTWARE_ENGINEERING.md"

entries = [
    "**Event Sourcing**: A design pattern in which changes to the application state are stored as a sequence of events.",
    "**CQRS (Command Query Responsibility Segregation)**: A pattern that separates read and update operations for a data store.",
    "**Saga Pattern**: A failure management pattern for distributed systems that provides atomicity through a series of local transactions.",
    "**Circuit Breaker Pattern**: A design pattern used in software development to detect failures and encapsulate the logic of preventing a failure from constantly recurring.",
    "**Bulkhead Pattern**: A type of application design that is tolerant of failure.",
    "**Retry Pattern**: Enables an application to handle temporary failures when it tries to connect to a service or network resource.",
    "**Sidecar Pattern**: Deploy components of an application into a separate process or container to provide isolation and encapsulation.",
    "**Ambassador Pattern**: Create helper services that send network requests on behalf of a consumer service or application.",
    "**Anti-Corruption Layer**: A layer that translates between two subsystems to prevent one from 'corrupting' the other's domain model.",
    "**Backends for Frontends (BFF)**: Create separate backend services to be consumed by specific frontend applications or interfaces.",
    "**Strangler Fig Pattern**: A popular design pattern to incrementally transform a monolithic application into microservices.",
    "**Database-per-Service**: A pattern where each microservice has its own private database that can only be accessed by that service.",
    "**Shared Database Pattern**: A pattern where multiple microservices share the same database (often considered an anti-pattern in pure microservices).",
    "**API Gateway**: A server that is the single entry point into the system.",
    "**Service Mesh**: A dedicated infrastructure layer for facilitating service-to-service communications.",
    "**Blue-Green Deployment**: A technique that reduces downtime and risk by running two identical production environments.",
    "**Canary Deployment**: A pattern for rolling out releases to a subset of users or servers.",
    "**Shadow Deployment**: Releasing a new version of a service alongside the current version without routing user traffic to it.",
    "**A/B Testing**: A randomized experimentation process wherein two or more versions of a variable are shown to different segments of website visitors.",
    "**Feature Toggles (Feature Flags)**: A technique in software development that attempts to provide an alternative to maintaining multiple branches in source code.",
    "**Chaos Engineering**: The discipline of experimenting on a system in order to build confidence in the system's capability to withstand turbulent conditions in production.",
    "**Observability**: A measure of how well internal states of a system can be inferred from knowledge of its external outputs.",
    "**Distributed Tracing**: A method used to profile and monitor applications, especially those built using a microservices architecture.",
    "**Structured Logging**: A technique for logging that involves providing logs in a consistent, machine-readable format.",
    "**Metrics**: Quantitative measurements of a system's state or behavior.",
    "**Alerting**: The process of notifying operators when a system's state deviates from the norm.",
    "**Health Checks (Liveness/Readiness)**: Mechanisms to determine if an application is running and if it is ready to receive traffic.",
    "**Log Aggregation**: The process of collecting logs from various sources and storing them in a centralized location.",
    "**Infrastructure as Code (IaC)**: The process of managing and provisioning computer data centers through machine-readable definition files.",
    "**Terraform**: An open-source infrastructure as code software tool created by HashiCorp.",
    "**Ansible**: An open-source software provisioning, configuration management, and application-deployment tool.",
    "**Cloud-Native**: An approach to building and running applications that exploits the advantages of the cloud computing delivery model.",
    "**Twelve-Factor App**: A methodology for building software-as-a-service apps.",
    "**Immutable Infrastructure**: An approach where servers are never modified after they're deployed.",
    "**Stateless Applications**: Applications that do not store client data from one session to use in the next.",
    "**Stateful Applications**: Applications that remember previous interactions and store data about them.",
    "**Data Sovereignty**: The idea that data is subject to the laws and governance structures within the nation it is collected.",
    "**GDPR (General Data Protection Regulation)**: A regulation in EU law on data protection and privacy.",
    "**Compliance as Code**: The practice of codifying compliance requirements into automated tests.",
    "**Shift-Left Security**: The practice of integrating security early in the software development lifecycle.",
    "**DevSecOps**: The integration of security practices into the DevOps process.",
    "**SRE (Site Reliability Engineering)**: A discipline that incorporates aspects of software engineering and applies them to infrastructure and operations problems.",
    "**Error Budget**: The amount of error that a service can tolerate without violating its SLO.",
    "**SLI (Service Level Indicator)**: A quantitative measure of some aspect of the level of service that is provided.",
    "**SLO (Service Level Objective)**: A target value or range of values for a service level that is measured by an SLI.",
    "**SLA (Service Level Agreement)**: A contract between a service provider and its customers that documents what services the provider will furnish.",
    "**Incident Management**: The process of identifying, analyzing, and correcting hazards to prevent a future re-occurrence.",
    "**Post-Mortem (Blameless)**: A written record of an incident, its impact, the actions taken to mitigate or resolve it, and the root cause.",
    "**On-Call Rotation**: A schedule that ensures someone is available 24/7 to respond to incidents.",
    "**Capacity Planning**: The process of determining the production capacity needed by an organization to meet changing demands for its products.",
    "**Scalability (Vertical vs Horizontal)**: Increasing capacity by adding resources to a single node (vertical) or adding more nodes (horizontal).",
    "**Elasticity**: The ability of a system to grow or shrink in response to demand.",
    "**Availability (High Availability)**: A characteristic of a system which aims to ensure an agreed level of operational performance.",
    "**Reliability**: The probability that a system will perform its intended function without failure for a specified period.",
    "**Durability**: The ability of a system to keep data intact over time.",
    "**Latency**: The time it takes for a data packet to travel from one point to another.",
    "**Throughput**: The amount of data that can be processed by a system in a given period.",
    "**Cold Start**: The latency experienced when a serverless function is invoked for the first time or after a period of inactivity.",
    "**Warm-up Strategy**: Techniques to mitigate cold starts by keeping instances active.",
    "**Vendor Lock-in**: A situation in which a customer is dependent on a vendor for products and services and cannot switch to another vendor without substantial costs.",
    "**Multi-Cloud Strategy**: The use of two or more cloud computing services from different vendors.",
    "**Hybrid Cloud**: A computing environment that combines a public cloud and a private cloud.",
    "**Edge Computing**: A distributed computing paradigm that brings computation and data storage closer to the sources of data.",
    "**Internet of Things (IoT)**: The network of physical objects that are embedded with sensors, software, and other technologies.",
    "**Big Data**: Extremely large data sets that may be analyzed computationally to reveal patterns, trends, and associations.",
    "**Data Lake**: A centralized repository that allows you to store all your structured and unstructured data at any scale.",
    "**Data Warehouse**: A system used for reporting and data analysis.",
    "**Data Pipeline**: A set of data processing elements connected in series.",
    "**ETL (Extract, Transform, Load)**: A three-step process in which data is extracted from source systems, transformed, and loaded into a destination.",
    "**ELT (Extract, Load, Transform)**: An alternative to ETL where data is loaded into the destination before being transformed.",
    "**Data Mesh**: A decentralized architectural pattern for data management.",
    "**Apache Kafka**: An open-source distributed event streaming platform.",
    "**Message Queueing**: A form of asynchronous service-to-service communication.",
    "**Pub/Sub (Publish-Subscribe)**: A messaging pattern where senders (publishers) do not program the messages to be sent directly to specific receivers (subscribers).",
    "**Point-to-Point Messaging**: A messaging pattern where each message is addressed to one specific consumer.",
    "**Event-Driven Architecture (EDA)**: A software architecture paradigm promoting the production, detection, consumption of, and reaction to events.",
    "**Reactive Programming**: A declarative programming paradigm concerned with data streams and the propagation of change.",
    "**WebAssembly (Wasm)**: A binary instruction format for a stack-based virtual machine.",
    "**Progressive Web Apps (PWA)**: Web applications that use modern web capabilities to deliver an app-like experience to users.",
    "**Single Page Application (SPA)**: A web application or website that interacts with the user by dynamically rewriting the current web page.",
    "**Server-Side Rendering (SSR)**: The ability of an application to contribute to the display of the web page on the server instead of in the browser.",
    "**Static Site Generation (SSG)**: The process of generating a full static HTML website based on raw data and a set of templates.",
    "**Hydration (Web Development)**: The process of attaching event listeners to the DOM nodes and making the page interactive on the client side.",
    "**Code Splitting**: A feature that allows you to split your code into various bundles which can then be loaded on demand.",
    "**Tree Shaking**: A term commonly used in the JavaScript context for dead-code elimination.",
    "**Responsive Design**: An approach to web design that makes web pages render well on a variety of devices and window or screen sizes.",
    "**Mobile-First Design**: A design philosophy that prioritizes the mobile experience over the desktop.",
    "**Accessibility (a11y)**: The practice of making your websites usable by as many people as possible.",
    "**SEO (Search Engine Optimization)**: The process of improving the quality and quantity of website traffic to a website or a web page from search engines.",
    "**Web Vitals**: A set of metrics that Google believes are important for the overall user experience on the web.",
    "**DOM (Document Object Model)**: A cross-platform and language-independent interface that treats an XML or HTML document as a tree structure.",
    "**Shadow DOM**: A web standard that allows for the encapsulation of CSS and HTML.",
    "**Virtual DOM**: A programming concept where an ideal, or 'virtual', representation of a UI is kept in memory and synced with the 'real' DOM.",
    "**State Management (Frontend)**: The process of managing the data that an application needs to render its UI.",
    "**Redux**: A predictable state container for JavaScript apps.",
    "**React Hooks**: Functions that let you “hook into” React state and lifecycle features from function components.",
    "**Composition (Frontend UI)**: Building complex UIs by combining smaller, reusable components.",
    "**Design Systems**: A collection of reusable components, guided by clear standards, that can be assembled together to build any number of applications.",
    "**BEM (Block, Element, Modifier)**: A popular naming convention for classes in HTML and CSS.",
    "**CSS-in-JS**: A styling approach where JavaScript is used to style components.",
    # ... Entries 301-500 ...
    "**Web Security**: Protecting websites and online services from various cyber threats.",
    "**OWASP Top 10**: A standard awareness document for developers and web application security.",
    "**Injection Attacks**: Attacks where an attacker supplies untrusted input to a program.",
    "**Broken Authentication**: Issues with how an application handles user authentication and session management.",
    "**Sensitive Data Exposure**: When an application doesn't adequately protect sensitive information.",
    "**XML External Entities (XXE)**: An attack against an application that parses XML input.",
    "**Broken Access Control**: Failures in enforcing restrictions on what authenticated users are allowed to do.",
    "**Security Misconfiguration**: The most common security issue, often resulting from default configurations or incomplete setups.",
    "**Cross-Site Scripting (XSS)**: Injecting malicious scripts into trusted websites.",
    "**Insecure Deserialization**: When an application deserializes untrusted data, potentially leading to remote code execution.",
    "**Using Components with Known Vulnerabilities**: Software components (libraries, frameworks) that have known security flaws.",
    "**Insufficient Logging & Monitoring**: Failure to detect and respond to active breaches.",
    "**OAuth 2.0 Security Best Practices**: Using PKCE, state parameters, and secure redirect URIs.",
    "**CORS Security**: Properly configuring allowed origins and methods.",
    "**Content Security Policy (CSP)**: An added layer of security that helps to detect and mitigate certain types of attacks, including XSS and data injection.",
    "**Clickjacking**: A malicious technique of tricking a user into clicking on something different from what the user perceives.",
    "**Man-in-the-Middle (MITM) Attack**: An attack where the attacker secretly relays and possibly alters the communications between two parties.",
    "**Denial of Service (DoS)**: An attack meant to shut down a machine or network, making it inaccessible to its intended users.",
    "**Distributed Denial of Service (DDoS)**: A DoS attack that originates from many different sources.",
    "**Phishing**: A type of social engineering attack often used to steal user data.",
    "**Social Engineering**: The psychological manipulation of people into performing actions or divulging confidential information.",
    "**Brute Force Attack**: A trial-and-error method used to obtain information such as a user password or personal identification number.",
    "**Dictionary Attack**: A systematic way to crack a password-protected computer or server by entering every word in a dictionary as a password.",
    "**Rainbow Tables**: A precomputed table for reversing cryptographic hash functions, usually for cracking password hashes.",
    "**Salting & Peppering**: Techniques to protect password hashes from rainbow table attacks.",
    "**Multi-Factor Authentication (MFA)**: An authentication method in which a computer user is granted access only after successfully presenting two or more pieces of evidence.",
    "**Passwordless Authentication**: Verifying a user's identity without requiring a password (e.g., magic links, biometrics).",
    "**Biometric Authentication**: Using unique biological characteristics for identification.",
    "**Single Sign-On (SSO)**: An authentication scheme that allows a user to log in with a single ID to any of several related, but independent, software systems.",
    "**Least Privilege Principle**: The principle that a user should be given only those privileges needed for it to complete its task.",
    "**Separation of Duties**: The concept of having more than one person required to complete a task.",
    "**Air Gapping**: A network security measure employed on one or more computers to ensure that a secure computer network is physically isolated from unsecured networks.",
    "**Honeypot**: A computer security mechanism set to detect, deflect, or, in some manner, counteract attempts at unauthorized use of information systems.",
    "**Intrusion Detection System (IDS)**: A device or software application that monitors a network or systems for malicious activity or policy violations.",
    "**Intrusion Prevention System (IPS)**: A network security/threat prevention technology that examines network traffic flows to detect and prevent vulnerability exploits.",
    "**Firewall**: A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules.",
    "**VPN (Virtual Private Network)**: Extends a private network across a public network.",
    "**Tunneling Protocols**: Protocols that allow for the secure movement of data from one network to another.",
    "**SSL/TLS Handshake**: The process of establishing a secure connection between a client and a server.",
    "**Certificate Authority (CA)**: An entity that issues digital certificates.",
    "**Public Key Infrastructure (PKI)**: A set of roles, policies, hardware, software and procedures needed to create, manage, distribute, use, store and revoke digital certificates.",
    "**Diffie-Hellman Key Exchange**: A method of securely exchanging cryptographic keys over a public channel.",
    "**RSA Algorithm**: One of the first public-key cryptosystems and is widely used for secure data transmission.",
    "**AES (Advanced Encryption Standard)**: A specification for the encryption of electronic data established by the U.S. NIST.",
    "**Elliptic Curve Cryptography (ECC)**: An approach to public-key cryptography based on the algebraic structure of elliptic curves over finite fields.",
    "**Zero-Knowledge Proofs**: A method by which one party can prove to another party that they know a value x, without conveying any information apart from the fact that they know the value x.",
    "**Homomorphic Encryption**: A form of encryption that allows computations to be carried out on ciphertext, generating an encrypted result which, when decrypted, matches the result of operations performed on the plaintext.",
    "**Post-Quantum Cryptography**: Cryptographic algorithms that are thought to be secure against a cryptanalytic attack by a quantum computer.",
    "**Blockchain Security**: Techniques for securing distributed ledgers.",
    "**Smart Contract Auditing**: Reviewing the code of a smart contract for security vulnerabilities.",
    "**Formal Verification**: The act of proving or disproving the correctness of intended algorithms underlying a system with respect to a certain formal specification or property.",
    "**Logic Bomb**: A piece of code intentionally inserted into a software system that will set off a malicious function when specified conditions are met.",
    "**Trojan Horse**: Any malware which misleads users of its true intent.",
    "**Worm**: A standalone malware computer program that replicates itself in order to spread to other computers.",
    "**Rootkit**: A collection of computer software, typically malicious, designed to enable access to a computer or an area of its software that is not otherwise allowed.",
    "**Spyware**: Software that aims to gather information about a person or organization, sometimes without their knowledge.",
    "**Adware**: Software that generates revenue for its developer by automatically generating online advertisements in the user interface.",
    "**Ransomware**: A type of malware from cryptovirology that threatens to publish the victim's personal data or perpetually block access to it unless a ransom is paid.",
    "**Botnet**: A number of Internet-connected devices, each of which is running one or more bots.",
    "**Zero-Day Vulnerability**: A vulnerability that is known to the software vendor but has not yet been patched.",
    "**CVE (Common Vulnerabilities and Exposures)**: A list of publicly disclosed computer security flaws.",
    "**CVSS (Common Vulnerability Scoring System)**: A free and open industry standard for assessing the severity of computer system security vulnerabilities.",
    "**NIST Cybersecurity Framework**: A set of guidelines for mitigating organizational cybersecurity risks.",
    "**ISO/IEC 27001**: An international standard on how to manage information security.",
    "**SOC 2 (Service Organization Control 2)**: An auditing procedure that ensures your service providers securely manage your data.",
    "**PCI DSS (Payment Card Industry Data Security Standard)**: A set of security standards designed to ensure that all companies that accept, process, store or transmit credit card information maintain a secure environment.",
    "**Hipaa (Health Insurance Portability and Accountability Act)**: A US law designed to provide privacy standards to protect patients' medical records.",
    "**COPPA (Children's Online Privacy Protection Act)**: A US law that imposes certain requirements on operators of websites or online services directed to children.",
    "**Data Masking**: The process of hiding original data with modified content.",
    "**Data Anonymization**: The process of either encrypting or removing personally identifiable information from data sets.",
    "**Differential Privacy**: A system for publicly sharing information about a dataset by describing the patterns of groups within the dataset while withholding information about individuals in the dataset.",
    "**Privacy-Preserving Computation**: Techniques that allow computation to be performed on data while keeping the data private.",
    "**Secure Multi-Party Computation (SMPC)**: A subfield of cryptography with the goal of creating methods for parties to jointly compute a function over their inputs while keeping those inputs private.",
    "**Trusted Execution Environment (TEE)**: A secure area of a main processor.",
    "**Secure Enclave**: A hardware-based key manager that’s isolated from the main processor to provide an extra layer of security.",
    "**End-to-End Encryption (E2EE)**: A system of communication where only the communicating users can read the messages.",
    "**Perfect Forward Secrecy (PFS)**: A feature of specific key agreement protocols that gives assurances that session keys will not be compromised even if long-term secrets are compromised.",
    "**Steganography**: The practice of concealing a file, message, image, or video within another file, message, image, or video.",
    "**Side-Channel Attack**: Any attack based on information gained from the implementation of a computer system, rather than weaknesses in the implemented algorithm itself.",
    "**Timing Attack**: A side-channel attack in which the attacker attempts to compromise a cryptosystem by analyzing the time taken to execute cryptographic algorithms.",
    "**Power Analysis Attack**: An attack that involves measuring the power consumption of a hardware device during cryptographic operations.",
    "**Electromagnetic Attack**: An attack based on the electromagnetic radiation emitted by a device.",
    "**Fault Injection Attack**: An attack that involves introducing faults into a system to change its behavior or reveal secrets.",
    "**Cold Boot Attack**: A type of side-channel attack in which an attacker with physical access to a computer is able to retrieve encryption keys from a running operating system after using a hard reset to restart the machine.",
    "**Rowhammer**: A security exploit that takes advantage of an unintended and undesirable side effect in dynamic random-access memory (DRAM).",
    "**Spectre & Meltdown**: Critical vulnerabilities in modern processors that allow unauthorized access to sensitive data.",
    "**Supply Chain Attack**: A cyberattack that seeks to damage an organization by targeting less-secure elements in the supply chain.",
    "**Software Bill of Materials (SBOM)**: A nesting inventory of all software components used in a script or program.",
    "**Dependabot**: A tool that helps you keep your dependencies up to date.",
    "**SCA (Software Composition Analysis)**: The process of automating the visibility into open source software (OSS) inventory.",
    "**DAST (Dynamic Application Security Testing)**: Testing an application from the outside in.",
    "**SAST (Static Application Security Testing)**: Testing the source code, byte code or binaries of an application for security vulnerabilities.",
    "**IAST (Interactive Application Security Testing)**: Combines DAST and SAST to provide more accurate results.",
    "**RASP (Runtime Application Self-Protection)**: A security technology that uses runtime instrumentation to detect and block computer attacks by taking advantage of information from inside the running software.",
    "**WAF (Web Application Firewall)**: A specific type of application firewall that filters, monitors, and blocks HTTP traffic to and from a web application.",
    "**DDoS Protection (Scrubbing Centers)**: Specialized data centers that filter out malicious traffic during a DDoS attack.",
    "**Security Operations Center (SOC)**: A centralized unit that deals with security issues on an organizational and technical level.",
    "**SIEM (Security Information and Event Management)**: A field within the field of computer security, where software products and services combine security information management (SIM) and security event management (SEM).",
    "**SOAR (Security Orchestration, Automation and Response)**: Technologies that enable organizations to collect inputs monitored by the security operations team.",
    "**Blue Team (Defense)**: A group of individuals who perform an analysis of information systems to ensure security.",
    "**Red Team (Offense)**: A group that plays the role of an enemy or competitor to provide feedback from the outside.",
    "**Purple Team (Collaboration)**: A security methodology where red and blue teams work together to improve organizational security.",
    "**White Hat Hacker**: An ethical computer hacker, or a computer security expert, who specializes in penetration testing and in other testing methodologies that ensures the security of an organization's information systems.",
    "**Black Hat Hacker**: A hacker who violates computer security for little reason beyond maliciousness or for personal gain.",
    "**Grey Hat Hacker**: A computer hacker or computer security expert who may sometimes violate laws or typical ethical standards, but does not have the malicious intent typical of a black hat hacker.",
    "**Bug Bounty Program**: A deal offered by many websites, organizations and software developers by which individuals can receive recognition and compensation for reporting bugs, especially those pertaining to security exploits and vulnerabilities.",
    "**Responsible Disclosure**: A model where a vulnerability is reported privately to the vendor, allowing them to fix it before it is disclosed publicly.",
    "**Responsible AI**: A framework for the fair, transparent, and accountable development and use of AI technology.",
    "**AI Safety**: A field of research that aims to ensure that AI systems behave in ways that are safe and beneficial to humans.",
    "**Alignment Problem**: The challenge of ensuring that AI systems' goals and behaviors are aligned with human values.",
    "**Algorithmic Bias**: Systematic and repeatable errors in a computer system that create unfair outcomes.",
    "**Explainable AI (XAI)**: AI in which the results of the solution can be understood by humans.",
    "**Adversarial Machine Learning**: A machine learning technique that attempts to fool models by supplying deceptive input.",
    "**Model Poisoning**: An attack where the attacker pushes malicious data into a machine learning model's training set.",
    "**Model Inversion Attack**: An attack where the attacker tries to reconstruct the training data from the model's outputs.",
    "**Deepfake Security**: Tools and techniques to detect and mitigate the impact of synthetic media.",
    "**Digital Forensics**: The branch of forensic science encompassing the recovery and investigation of material found in digital devices.",
    "**Chain of Custody**: The chronological documentation or paper trail that records the sequence of custody, control, transfer, analysis, and disposition of physical or electronic evidence.",
    "**Hashing (Forensics)**: Using hash functions to verify the integrity of digital evidence.",
    "**Steganalysis**: The study of detecting messages concealed using steganography.",
    "**Malware Analysis**: The process of determining the functionality, origin and potential impact of a given malware sample.",
    "**Static Malware Analysis**: Examining the malware without executing it.",
    "**Dynamic Malware Analysis (Sandboxing)**: Executing the malware in a controlled, isolated environment to observe its behavior.",
    "**Reverse Engineering (Malware)**: Decompiling or disassembling the malware to understand its inner workings.",
    "**Threat Intelligence**: Information used by an organization to understand the threats that have, will, or are currently targeting the organization.",
    "**OSINT (Open Source Intelligence)**: The collection and analysis of data which is gathered from open sources.",
    "**Indicators of Compromise (IoC)**: Pieces of forensic data, such as data found in system log entries or files, that identify potentially malicious activity on a system or network.",
    "**TTPs (Tactics, Techniques, and Procedures)**: The patterns of activities or methods associated with a specific threat actor or group.",
    "**APT (Advanced Persistent Threat)**: A stealthy threat actor, typically a nation state or state-sponsored group, which gains unauthorized access to a computer network and remains undetected for an extended period.",
    "**Script Kiddie**: An unskilled individual who uses scripts or programs developed by others to attack computer systems and networks.",
    "**Hacktivism**: The use of computer-based techniques such as hacking as a form of civil disobedience to promote a political agenda or social change.",
    "**Cyber Warfare**: The use of digital attacks to attack a nation, causing comparable harm to actual warfare.",
    "**Cyber Terrorism**: The use of the Internet to conduct violent acts that result in, or threaten, loss of life or significant bodily harm, in order to achieve political or ideological gains through intimidation.",
    "**Cyber Espionage**: The act or practice of obtaining secrets without the permission of the holder of the information.",
    "**Industrial Control Systems (ICS) Security**: Protecting the hardware and software used to control industrial processes.",
    "**SCADA (Supervisory Control and Data Acquisition) Security**: Protecting the systems used for high-level process supervisory management.",
    "**Critical Infrastructure Protection (CIP)**: Protecting the assets, systems, and networks, whether physical or virtual, so vital that their incapacitation or destruction would have a debilitating effect on security.",
    "**Smart Grid Security**: Protecting the modernized electrical grid.",
    "**Autonomous Vehicle Security**: Protecting the systems and sensors used by self-driving cars.",
    "**Medical Device Security**: Ensuring the safety and security of internet-connected medical devices.",
    "**Wearable Technology Security**: Protecting the personal and health data collected by wearable devices.",
    "**Cloud Security (Shared Responsibility Model)**: The understanding of which security tasks are handled by the cloud provider and which are handled by the customer.",
    "**IAM (Identity and Access Management)**: A framework of policies and technologies for ensuring that the right people in an enterprise have the appropriate access to technology resources.",
    "**Privileged Access Management (PAM)**: Specialized IAM for high-level administrative accounts.",
    "**Single-Tenant vs Multi-Tenant Security**: The security implications of dedicated vs shared cloud environments.",
    "**Data Exfiltration**: The unauthorized transfer of data from a computer.",
    "**Shadow IT**: Information technology systems and solutions built and used within an organization without explicit organizational approval.",
    "**Bring Your Own Device (BYOD) Policy**: A policy that allows employees to use their personal devices for work.",
    "**MDM (Mobile Device Management)**: Software that allows IT administrators to control, secure and enforce policies on smartphones, tablets and other endpoints.",
    "**Container Security (Image Scanning)**: Checking container images for vulnerabilities before deployment.",
    "**Kubernetes Network Policies**: Controlling the traffic between pods in a Kubernetes cluster.",
    "**Service Mesh Security (mTLS)**: Using mutual TLS for all service-to-service communication.",
    "**GitOps Security**: Ensuring the security of the Git repository as a source of truth for infrastructure and application configuration.",
    "**Policy as Code (OPA)**: Codifying security policies so they can be enforced automatically.",
    "**Serverless Security (Function Isolation)**: Ensuring that individual functions in a serverless environment are securely isolated.",
    "**API Security (Rate Limiting & Scopes)**: Protecting APIs from abuse and unauthorized access.",
    "**Third-Party Risk Management (TPRM)**: The process of identifying, assessing, and mitigating risks associated with using third-party vendors and service providers.",
    "**Cyber Insurance**: An insurance product used to protect businesses and individual users from Internet-based risks.",
    "**Security Awareness Training**: Educating employees about security threats and best practices.",
    "**Incident Response Plan (IRP)**: A set of instructions to help IT staff detect, respond to, and recover from network security incidents.",
    "**Business Continuity Planning (BCP)**: The process of creating systems of prevention and recovery to deal with potential threats to a company.",
    "**Disaster Recovery (DR)**: A set of policies, tools and procedures to enable the recovery or continuation of vital technology infrastructure and systems following a natural or human-induced disaster.",
    "**RPO (Recovery Point Objective)**: The maximum age of files that an organization must recover from backup storage for normal operations to resume after a disaster.",
    "**RTO (Recovery Time Objective)**: The amount of time that an organization has to restore its business processes after a disaster.",
    "**Air-Gapped Backups**: Backups that are physically isolated from any network.",
    "**Cold, Warm, and Hot Sites**: Different levels of disaster recovery facilities.",
    "**Redundancy (N+1, 2N)**: Building extra capacity into a system to ensure availability in case of failure.",
    "**Failover**: A backup operational mode in which the functions of a system component are assumed by secondary system components when the primary component becomes unavailable.",
    "**Failback**: The process of restoring a workload to its original primary location after a failover.",
    "**Load Testing**: Testing the system's performance under expected load.",
    "**Stress Testing**: Testing the system's performance under extreme load.",
    "**Soak Testing**: Testing the system's performance over an extended period.",
    "**Spike Testing**: Testing the system's reaction to sudden, large increases in load.",
    "**Scalability Testing**: Testing the system's ability to scale up or down.",
    "**End-to-End Testing (E2E)**: Testing the entire flow of an application from start to finish.",
    "**Automated Testing (Benefits vs Costs)**: Evaluating when to automate and when to use manual testing.",
    "**Continuous Testing**: The process of executing automated tests as part of the software delivery pipeline.",
    "**Test Pyramid**: A metaphorical way of grouping software tests into buckets of different granularity.",
    "**Left-To-Right Testing**: Integrating testing across the entire pipeline.",
    "**Contract Testing**: A way to test that two services (such as a provider and a consumer) can communicate with each other.",
    "**Visual Regression Testing**: Checking for visual changes in the UI.",
    "**Performance Profiling**: Using tools to identify bottlenecks in the code.",
    "**Flame Graphs**: A visualization of profiled software, used to identify hot paths in the code.",
    "**Heap Dumps**: A snapshot of all the objects in the memory of a Java process at a certain moment.",
    "**Thread Dumps**: A snapshot of the state of all threads of a Java process at a certain moment.",
    "**Core Dumps**: A recorded state of the working memory of a computer program at a specific time, generally when the program has crashed or otherwise terminated abnormally.",
    "**GDB (GNU Debugger)**: The standard debugger for the GNU operating system.",
    "**Valgrind**: An instrumentation framework for building dynamic analysis tools.",
    "**Wireshark**: A free and open-source packet analyzer.",
    "**Tcpdump**: A common packet analyzer that runs under the command line.",
    "**Postman**: An API platform for developers to design, build, test and iterate their APIs.",
    "**Swagger/OpenAPI**: A specification for machine-readable interface files for describing, producing, consuming, and visualizing RESTful web services.",
    "**Jira**: A proprietary issue tracking product developed by Atlassian that allows bug tracking and agile project management.",
    "**Confluence**: A web-based corporate wiki developed by Atlassian.",
    "**Slack (for DevOps)**: Using Slack as a central hub for communication and alerts.",
    "**GitHub Actions**: A CI/CD platform that allows you to automate your build, test, and deployment pipeline.",
    "**Jenkins**: An open-source automation server which enables developers around the world to reliably build, test, and deploy their software.",
    "**GitLab CI/CD**: A tool built into GitLab for software development using the continuous methodologies.",
    "**CircleCI**: A modern CI/CD platform that automates software build, test, and deployment.",
    "**Travis CI**: A hosted continuous integration service used to build and test software projects hosted at GitHub and Bitbucket.",
    "**SonarQube**: An open-source platform developed by SonarSource for continuous inspection of code quality.",
    "**Artifactory**: A repository manager that supports various software package formats.",
    "**Nexus Repository Manager**: A repository manager that organizes, stores and distributes artifacts needed for software development.",
    "**Prometheus**: An open-source systems monitoring and alerting toolkit.",
    "**Grafana**: A multi-platform open-source analytics and interactive visualization web application.",
    "**ELK Stack (Elasticsearch, Logstash, Kibana)**: A collection of three open-source products used for log analysis.",
    "**Datadog**: A monitoring service for cloud-scale applications.",
    "**New Relic**: A software-as-a-service for monitoring the performance of web and mobile applications.",
    "**Splunk**: A software platform to search, monitor, and analyze machine-generated big data.",
    "**PagerDuty**: An incident response platform for IT departments.",
    "**VictorOps**: A real-time incident management platform.",
    "**OpsGenie**: A modern incident management platform for operating always-on services.",
    "**LaunchDarkly**: A feature management platform.",
    "**Optimizely**: A digital experience platform that provides A/B testing and multivariate testing tools.",
    "**Nginx**: A web server that can also be used as a reverse proxy, load balancer, mail proxy and HTTP cache.",
    "**Apache HTTP Server**: A free and open-source cross-platform web server software.",
    "**HAProxy**: A high-availability load balancer and proxy server for TCP and HTTP-based applications.",
    "**Envoy Proxy**: An open-source edge and service proxy, designed for cloud-native applications.",
    "**Istio**: An open-source service mesh that provides a uniform way to integrate, manage, and secure microservices.",
    "**Linkerd**: A service mesh for Kubernetes and other frameworks.",
    "**Consul**: A service mesh solution providing a full-featured control plane with service discovery, configuration, and segmentation functionality.",
    "**Etcd**: A strongly consistent, distributed key-value store.",
    "**Zookeeper**: An open-source server which enables highly reliable distributed coordination.",
    "**Redis**: An open-source, in-memory data structure store, used as a database, cache, and message broker.",
    "**Memcached**: A general-purpose distributed memory-caching system.",
    "**RabbitMQ**: An open-source message-broker software.",
    "**ActiveMQ**: An open-source message broker written in Java together with a full Java Message Service client.",
    "**AWS (Amazon Web Services)**: The world's most comprehensive and broadly adopted cloud platform.",
    "**Azure**: Microsoft's cloud computing platform.",
    "**GCP (Google Cloud Platform)**: A suite of cloud computing services that runs on the same infrastructure that Google uses internally.",
    "**DigitalOcean**: An American cloud infrastructure provider.",
    "**Heroku**: A platform as a service (PaaS) that enables developers to build, run, and operate applications entirely in the cloud.",
    "**Vercel**: A cloud platform for static sites and Serverless Functions.",
    "**Netlify**: A cloud computing company that offers a development platform that includes build, deploy, and serverless backend services.",
    "**Firebase**: A platform developed by Google for creating mobile and web applications.",
    "**Supabase**: An open-source Firebase alternative.",
    "**Appwrite**: An open-source backend server for web, mobile, and flutter developers.",
    "**Hasura**: An open-source engine that connects to your databases & microservices and auto-generates a production-ready GraphQL API.",
    "**Strapi**: An open-source, Node.js based, Headless CMS that saves developers a lot of time while giving them the freedom to use their favorite tools and frameworks.",
    "**Sanity.io**: A cloud-based headless CMS.",
    "**Contentful**: A cloud-based headless CMS.",
    "**Ghost**: A free and open-source blogging platform written in JavaScript.",
    "**WordPress**: A free and open-source content management system written in Hypertext Preprocessor.",
    "**Shopify**: An e-commerce platform for online stores and retail point-of-sale systems.",
    "**Magento**: An open-source e-commerce platform written in PHP.",
    "**WooCommerce**: An open-source e-commerce plugin for WordPress.",
    "**BigCommerce**: An e-commerce platform for fast-growing businesses.",
    "**Salesforce**: A cloud-based software company which provides customer relationship management service.",
    "**HubSpot**: An American developer and marketer of software products for inbound marketing, sales, and customer service.",
    "**Zendesk**: A customer service software and support ticket system.",
    "**Intercom**: A conversational relationship platform.",
    "**Mailchimp**: An American marketing automation platform and email marketing service.",
    "**Twilio**: A cloud communications platform as a service.",
    "**SendGrid**: A customer communication platform for transactional and marketing email.",
    "**Stripe**: A suite of payment APIs that powers commerce for online businesses of all sizes.",
    "**PayPal**: An American multinational financial technology company operating an online payments system.",
    "**Adyen**: A global payment company that allows businesses to accept e-commerce, mobile, and point-of-sale payments.",
    "**Braintree**: A Chicago-based company that specializes in mobile and web payment systems for e-commerce companies.",
    "**Square**: A financial services and digital payments company.",
    "**Plaid**: A financial services company which builds a data transfer network that powers fintech and digital finance products.",
    "**Algolia**: A proprietary search-as-a-service platform.",
    "**Elasticsearch**: A search engine based on the Lucene library.",
    "**Solr**: An open-source enterprise search platform, written in Java.",
    "**Meilisearch**: An open-source, lightning-fast, and hyper-relevant search engine.",
    "**Typesense**: An open-source, typo-tolerant search engine.",
    "**Cloudinary**: A software-as-a-service technology company that provides a cloud-based image and video management primary.",
    "**Imgix**: A real-time image processing and delivery service.",
    "**Mux**: A video infrastructure platform for developers.",
    "**Sentry**: An application monitoring platform that helps developers identify, diagnose, and fix errors in real-time.",
    "**Rollbar**: An error tracking and monitoring tool.",
    "**LogRocket**: A frontend monitoring tool that records everything users do on your site.",
    "**Hotjar**: A product experience insights tool.",
    "**FullStory**: A digital experience intelligence platform.",
    "**Mixpanel**: A business analytics service company.",
    "**Amplitude**: A product intelligence platform.",
    "**Segment**: A customer data platform.",
    "**PostHog**: An open-source product analytics platform.",
    "**Airtable**: A cloud-based software company that offers an online platform for creating and sharing relational databases.",
    "**Notion**: A project management and note-taking software.",
    "**Trello**: A web-based, Kanban-style, list-making application.",
    "**Asana**: A web and mobile application designed to help teams organize, track, and manage their work.",
    "**ClickUp**: A cloud-based collaboration and project management tool.",
    "**Monday.com**: A cloud-based platform that allows users to create their own applications and project management software.",
    "**Basecamp**: A project management and team communication software.",
    "**Linear**: A task-tracking and project management tool for high-performance software teams.",
    "**Figma**: A collaborative web application for interface design.",
    "**Adobe XD**: A vector-based user experience design tool for web apps and mobile apps.",
    "**Sketch**: A vector graphics editor for MacOS.",
    "**InVision**: A prototyping tool for digital products.",
    "**Zeplin**: A collaboration tool for designers and developers.",
    "**Storybook**: An open source tool for building UI components and pages in isolation.",
    "**Bit.dev**: A cloud platform for component-driven development.",
    "**Nx**: A smart, fast and extensible build system.",
    "**Turborepo**: A high-performance build system for JavaScript and TypeScript codebases.",
    "**Lerna**: A tool for managing JavaScript projects with multiple packages.",
    "**Yarn Workspaces**: A feature that allows you to setup multiple packages in such a way that you only need to run yarn install once to install all of them in a single pass.",
    "**Pnpm Workspaces**: A feature that allows you to manage multiple packages within a single repository using pnpm.",
    "**Monorepo**: A software development strategy where code for many projects is stored in the same repository.",
    "**Polyrepo**: The traditional way of managing multiple projects by storing each of them in a separate repository.",
    "**Microfrontends**: An architectural style where a frontend app is composed of a set of independent, loosely coupled features.",
    "**Module Federation**: A JavaScript architecture invented by Zack Jackson, which allows a JavaScript application to dynamically load code from another application.",
    "**Edge Functions**: Serverless functions that run at the network edge, closer to users.",
    "**Web Streams**: A set of APIs that allow you to programmatically access streams of data.",
    "**Fetch API**: A modern, promise-based API for making network requests in the browser.",
    "**AbortController**: A Web API that allows you to abort one or more Web requests as and when desired.",
    "**Intersection Observer**: A Web API that provides a way to asynchronously observe changes in the intersection of a target element with an ancestor element or with a top-level document's viewport.",
    "**Mutation Observer**: A Web API that provides the ability to watch for changes being made to the DOM tree.",
    "**Resize Observer**: A Web API that reports changes to the dimensions of an Element's content or border-box.",
    "**Service Workers**: Scripts that your browser runs in the background, separate from a web page, opening the door to features that don't need a web page or user interaction.",
    "**Web Workers**: A simple means for web content to run scripts in background threads.",
    "**Shared Workers**: A type of web worker that can be accessed from several browsing contexts.",
    "**Broadcast Channel API**: Allows simple communication between browsing contexts on the same origin.",
    "**Web Storage (LocalStorage & SessionStorage)**: Mechanisms for storing key-value pairs in the web browser.",
    "**IndexedDB**: A low-level API for client-side storage of significant amounts of structured data.",
    "**Cache API**: A mechanism for storing network requests and their responses.",
    "**Push API**: Gives web applications the ability to receive messages pushed to them from a server.",
    "**Notifications API**: Used to configure and display desktop notifications to the user.",
    "**Web Share API**: Allows web apps to share text, links, and other content to other apps on the device.",
    "**Fullboard API**: Allows you to check whether it's possible to share a URL directly to the user's primary social feed.",
    "**Payment Request API**: A non-proprietary web standard that allows users to easily make payments on the web.",
    "**Web Authentication (WebAuthn)**: A web standard that allows servers to register and authenticate users using public key cryptography instead of a password.",
    "**Web Bluetooth API**: Allows web sites to communicate over GATT with nearby Bluetooth Low Energy devices.",
    "**Web USB API**: Provides a way to expose non-standard USB device services to the web.",
    "**Web Serial API**: Provides a way for websites to read from and write to serial devices.",
    "**Web NFC API**: Provides a way to read and write to NFC tags.",
    "**Geolocation API**: Used to get the geographical position of a user.",
    "**Media Capture and Streams API**: Allows a web page to access the user's camera and microphone.",
    "**Screen Capture API**: Allows a user to select a screen, window, or tab to capture as a media stream.",
    "**Picture-in-Picture API**: Allows websites to create a floating video window always on top of other windows.",
    "**Web Audio API**: A high-level JavaScript API for processing and synthesizing audio in web applications.",
    "**Web Speech API**: Enables you to incorporate speech data into web apps.",
    "**Gamepad API**: Provides a way for developers to access and respond to signals from gamepads.",
    "**Vibration API**: Provides a way to vibrate a device.",
    "**Device Orientation & Motion API**: Provides information about the physical orientation and motion of the device.",
    "**Page Visibility API**: Provides events that allow you to know when a document is being viewed or hidden.",
    "**Screen Orientation API**: Provides the ability to read the screen orientation state and to be informed when this state changes.",
    "**Battery Status API**: Provides information about the system's battery charge level.",
    "**Network Information API**: Provides information about the system's connection type and current bandwidth.",
    "**Performance API**: Provides access to performance-related information for the current page.",
    "**User Timing API**: Allows high-precision timestamps for performance measurement.",
    "**Long Tasks API**: Useful for identifying tasks that run for longer than 50 milliseconds.",
    "**Navigation Timing API**: Provides data that can be used to measure the performance of a website.",
    "**Resource Timing API**: Allows you to collect complete performance metrics for every resource on your page.",
    "**Server Timing API**: Allows a server to communicate performance metrics to the browser.",
    "**Reporting API**: Provides a generic reporting mechanism for web applications to use for reporting various issues.",
    "**Security Policy Violation API**: Provides information about Content Security Policy (CSP) violations.",
    "**Network Error Logging (NEL)**: Provides a mechanism for web applications to collect and analyze network errors.",
    "**Client Hints**: A set of HTTP request headers that allow a server to proactively request information about the user's device or network.",
    "**User-Agent Client Hints (UA-CH)**: A privacy-preserving alternative to the User-Agent string.",
    "**CHIPS (Cookies Having Independent Partitioned State)**: A mechanism to allow developers to opt-in a cookie to partitioned storage.",
    "**Storage Access API**: Provides a way for cross-site content to request access to its own storage.",
    "**Trust Tokens API**: A privacy-preserving way to convey trust in a user from one context to another.",
    "**Fenced Frames API**: A way to embed content while maintaining privacy isolation.",
    "**Topics API**: A privacy-preserving mechanism for interest-based advertising.",
    "**Protected Audience API (FLEDGE)**: A privacy-preserving mechanism for remarketing and custom audience use cases.",
    "**Attribution Reporting API**: A privacy-preserving mechanism for measuring ad conversions.",
    "**Shared Storage API**: A privacy-preserving mechanism for cross-site storage and processing.",
    "**Private Aggregation API**: A way to aggregate data from multiple sites or sources while preserving privacy.",
    "**Federated Credential Management (FedCM)**: A privacy-preserving API for identity federation.",
    "**Permissions Policy**: A mechanism for web developers to selectively enable, disable, and modify the behavior of certain APIs and web features.",
    "**Content Security Policy (CSP) Levels**: Evolution of the CSP standard (Level 1, 2, 3).",
    "**Subresource Integrity (SRI)**: A security feature that enables browsers to verify that resources they fetch are delivered without unexpected manipulation.",
    "**Sandboxing iframes**: Restricting the capabilities of content embedded in an iframe.",
    "**Secure Contexts**: A mechanism that ensures that certain web features are only available when the page is served over a secure connection.",
    "**HSTS (HTTP Strict Transport Security)**: A web security policy mechanism that helps to protect websites against protocol downgrade attacks and cookie hijacking.",
    "**HPKP (HTTP Public Key Pinning)**: A deprecated security feature that allowed web servers to tell browsers to 'pin' certain public keys.",
    "**Clear-Site-Data**: An HTTP response header that allows a server to clear a user's browser data.",
    "**Cross-Origin Opener Policy (COOP)**: Helps to protect a site from cross-origin attacks by ensuring it stays in its own browsing context group.",
    "**Cross-Origin Embedder Policy (COEP)**: Helps to protect a site from cross-origin attacks by ensuring that all embedded resources opt-in to being loaded.",
    "**Cross-Origin Resource Policy (CORP)**: Allows a server to declare that a resource shouldn't be loaded across origins.",
    "**SameSite Cookie Attribute**: A way to declare if your cookie should be restricted to a first-party or same-site context.",
    "**Domain and Path Attributes (Cookies)**: Controlling the scope of a cookie.",
    "**HttpOnly Attribute (Cookies)**: Preventing client-side scripts from accessing a cookie.",
    "**Secure Attribute (Cookies)**: Ensuring that a cookie is only sent over a secure connection.",
    "**Third-Party Cookies (Phase out)**: The ongoing process of removing support for third-party cookies in browsers.",
    "**Privacy Sandbox**: A multi-year initiative by Google to create technologies that both protect people's privacy online and give companies and developers tools to build thriving digital businesses.",
    "**Web Standards Process (W3C, WHATWG)**: How web standards are developed and formalized.",
    "**RFC (Request for Comments)**: A formal document from the IETF that is the result of committee drafting and subsequent review by interested parties.",
    "**SemVer (Semantic Versioning)**: A three-part version number system: major, minor, patch.",
    "**Lockfiles (package-lock.json, yarn.lock)**: Files that pin the exact versions of dependencies used in a project.",
    "**Transpiling Babel**: Using Babel to convert modern JavaScript into a version that is compatible with older browsers.",
    "**Minification**: The process of removing all unnecessary characters from source code without changing its functionality.",
    "**Bundling (Webpack, Rollup, Vite)**: The process of combining multiple JavaScript files into a single bundle for use in the browser.",
    "**Hot Module Replacement (HMR)**: A feature that allows you to update modules in a running application without a full reload.",
    "**Source Maps**: Files that map your minified/compiled code back to your original source code.",
    "**ESLint**: A static code analysis tool for identifying problematic patterns found in JavaScript code.",
    "**Prettier**: An opinionated code formatter.",
    "**Husky**: A tool for managing Git hooks.",
    "**Lint-Staged**: A tool that allows you to run linters on git staged files.",
    "**Conventional Commits**: A lightweight convention on top of commit messages.",
    "**Semantic Release**: A tool that automates the whole package release workflow.",
    "**Polyfills**: A piece of code used to provide modern functionality on older browsers that do not natively support it.",
    "**Ponyfills**: Similar to a polyfill, but doesn't modify the global environment.",
    "**Feature Detection (Modernizr)**: The practice of checking if a browser supports a particular feature before using it.",
    "**Graceful Degradation**: The practice of building your web functionality so that it provides a good user experience in modern browsers, but degrades gracefully in older browsers.",
    "**Progressive Enhancement**: A strategy for web design that emphasizes core webpage content first, and then progressively adds more nuanced and technically rigorous layers of user interface.",
    "**Critical CSS**: The minimum set of CSS required to render the above-the-fold content of a page.",
    "**Lazy Loading Images & Iframes**: Using the loading='lazy' attribute to defer loading of off-screen resources.",
    "**Preload, Prefetch, Preconnect**: Resource hints that tell the browser to start fetching or connecting to resources early.",
    "**HTTP/2 Multiplexing**: Allowing multiple requests and responses to be sent simultaneously over a single connection.",
    "**HTTP/2 Server Push**: Allowing a server to proactively send resources to a client before the client requests them.",
    "**HTTP/3 (QUIC)**: The third major version of the Hypertext Transfer Protocol, which uses QUIC instead of TCP.",
    "**Brotli Compression**: A generic-purpose lossless compression algorithm that compresses data using a combination of a modern variant of the LZ77 algorithm, Huffman coding and 2nd order context modeling.",
    "**Gzip Compression**: A file format and a software application used for file compression and decompression.",
    "**WebP & AVIF Image Formats**: Modern image formats that provide superior lossless and lossy compression for images on the web.",
    "**Responsive Images (srcset, sizes)**: Providing multiple versions of an image to the browser so it can choose the best one for the current device.",
    "**SVG (Scalable Vector Graphics)**: An XML-based vector image format for two-dimensional graphics.",
    "**Web Fonts (WOFF, WOFF2)**: Font formats optimized for use on the web.",
    "**Font Display (font-display)**: A CSS property that determines how a font face is displayed based on whether and when it is downloaded and ready to use.",
    "**Variable Fonts**: An evolution of the OpenType font specification that enables many variations of a typeface to be incorporated into a single file.",
    "**Dark Mode (prefers-color-scheme)**: A CSS media feature used to detect if the user has requested the system use a light or dark color theme.",
    "**Reduced Motion (prefers-reduced-motion)**: A CSS media feature used to detect if the user has requested that the system minimize the amount of non-essential motion it uses.",
    "**CSS Grid Layout**: A two-dimensional layout system for the web.",
    "**CSS Flexbox Layout**: A one-dimensional layout method for laying out items in rows or columns.",
    "**CSS Custom Properties (Variables)**: Entities defined by software authors that contain specific values to be reused throughout a document.",
    "**CSS Modules**: A CSS file in which all class names and animation names are scoped locally by default.",
    "**Styled Components**: A library for React and React Native that allows you to use component-level styles in your application.",
    "**Tailwind CSS**: A utility-first CSS framework for rapidly building custom user interfaces.",
    "**Atomic CSS**: A methodology of using many small, single-purpose classes to style elements.",
    "**Sass/SCSS**: A mature, stable, and powerful professional grade CSS extension language.",
    "**Less**: A backwards-compatible language extension for CSS.",
    "**PostCSS**: A tool for transforming CSS with JavaScript.",
    "**Autoprefixer**: A PostCSS plugin which parses your CSS and adds vendor prefixes to CSS rules using values from Can I Use.",
    "**Polymer**: An open-source JavaScript library for building web applications using Web Components.",
    "**Lit (LitElement, LitHtml)**: A simple library for building fast, lightweight web components.",
    "**Stencil**: A compiler that generates Web Components.",
    "**Blaze**: The reactive UI library used by Meteor.",
    "**Angular**: A TypeScript-based open-source web application framework led by the Angular Team at Google.",
    "**Vue.js**: An open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications.",
    "**Svelte**: A radical new approach to building user interfaces that shifts as much of the work as possible to compile-time.",
    "**SolidJS**: A declarative, efficient, and flexible JavaScript library for building user interfaces.",
    "**Preact**: A fast 3kB alternative to React with the same modern API.",
    "**Alpine.js**: A rugged, minimal tool for composing behavior directly in your markup.",
    "**Qwik**: A new kind of web framework that can deliver instant-on applications at any scale or complexity.",
    "**Fresh (Deno)**: A next generation web framework for Deno.",
    "**Remix**: A full stack web framework that lets you focus on the user interface and work back through web standards.",
    "**Next.js**: An open-source web development framework created by Vercel providing React-based web applications with server-side rendering and static site generation.",
    "**Nuxt.js**: A free and open source framework based on Vue.js, Node.js, Webpack and Babel.js.",
    "**SvelteKit**: A framework for building web applications using Svelte.",
    "**Astro**: An all-in-one web framework for building fast, content-focused websites.",
    "**Eleventy (11ty)**: A simpler static site generator.",
    "**Hugo**: One of the most popular open-source static site generators.",
    "**Gatsby**: A free and open source framework based on React that helps developers build blazing fast websites and apps.",
    "**Jekyll**: A simple, blog-aware, static site generator perfect for personal, project, or organization sites.",
    "**Docusaurus**: A project for easily building, deploying, and maintaining open source project documentation websites.",
    "**Vitest**: A blazing fast unit test framework powered by Vite.",
    "**Jest**: A delightful JavaScript Testing Framework with a focus on simplicity.",
    "**Mocha**: A feature-rich JavaScript test framework running on Node.js and in the browser.",
    "**Chai**: A BDD / TDD assertion library for node and the browser that can be delightfully paired with any javascript testing framework.",
    "**Cypress**: A next generation front end testing tool built for the modern web.",
    "**Playwright**: A framework for Web-browser testing and automation.",
    "**Puppeteer**: A Node library which provides a high-level API to control Chrome or Chromium over the DevTools Protocol.",
    "**Selenium**: An open-source project for browser automation.",
    "**Testing Library (TL)**: A family of packages that help you test UI components in a user-centric way.",
    "**Enzyme**: A JavaScript Testing utility for React that makes it easier to test your React Components' output.",
    "**Storybook Interaction Testing**: Using Storybook to test how components behave when users interact with them.",
    "**Chromatic**: A visual testing tool for Storybook.",
    "**Lighthouse**: An open-source, automated tool for improving the quality of web pages.",
    "**Pa11y**: An automated accessibility testing tool.",
    "**axe-core**: An accessibility testing engine for websites and other HTML-based user interfaces.",
    "**WebPageTest**: An open-source tool for measuring and analyzing the performance of web pages.",
    "**Bundlephobia**: A tool for finding the cost of adding a npm package to your bundle.",
    "**Packagephobia**: A tool for finding the size of a package and its dependencies after installation.",
    "**NPM (Node Package Manager)**: The default package manager for the JavaScript runtime environment Node.js.",
    "**Yarn (Package Manager)**: A package manager that doubles as a project manager.",
    "**Pnpm (Package Manager)**: A fast, disk space efficient package manager.",
    "**Bun (Runtime & Package Manager)**: A fast all-in-one JavaScript runtime.",
    "**Deno**: A simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.",
    "**Node.js**: An open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine.",
    "**Express.js**: A back end web application framework for Node.js.",
    "**Fastify**: An efficient and low overhead web framework, for Node.js.",
    "**Koa.js**: A new web framework designed by the team behind Express, which aims to be a smaller, more expressive, and more robust foundation for web applications and APIs.",
    "**NestJS**: A progressive Node.js framework for building efficient, reliable and scalable server-side applications.",
    "**Hapi.js**: A rich framework for building applications and services.",
    "**AdonisJS**: A fully featured web framework for Node.js.",
    "**Sails.js**: A realtime, MVC framework for Node.js.",
    "**Meteor.js**: An open-source isomorphic JavaScript web framework.",
    "**Feathers.js**: A framework for real-time applications and REST APIs.",
    "**Socket.io**: A library that enables real-time, bidirectional and event-based communication between the browser and the server.",
    "**Pusher**: A hosted service that makes it easy to add real-time data and functionality to web and mobile applications.",
    "**Ably**: A platform for real-time data synchronization.",
    "**Centrifugo**: A real-time messaging server.",
    "**Nats**: A simple, secure and high performance open source messaging system for cloud native applications, IoT messaging and microservices architectures."
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 201 - 500\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+201}. {entry}\n")
