import os
from pathlib import Path

_KNOWLEDGE_REF = (
    Path(__file__).resolve().parent.parent
    / "viking_girlfriend_skill" / "data" / "knowledge_reference"
)
file_path = _KNOWLEDGE_REF / "DATA_SCIENCE.md"

entries = [
    "**Advanced Statistical Modeling (The Seer's Deep Sight)**: Using complex mathematical frameworks to understand the unseen forces of Midgard.",
    "**Linear Regression (The Strongest String of the Bow)**: Modeling the relationship between a dependent scalar variable and one or more independent variables.",
    "**Logistic Regression (The Binary Path of the Warrior)**: Predicting the probability of an outcome that can only have two values.",
    "**Polynomial Regression (The Curved Flight of the Spear)**: A form of regression analysis in which the relationship between the independent variable x and the dependent variable y is modeled as an nth degree polynomial.",
    "**Ridge Regression (L2 Regularization) (The Softening of the Blow)**: A technique used when the data suffers from multicollinearity, adding a penalty proportional to the square of the magnitude of coefficients.",
    "**Lasso Regression (L1 Regularization) (The Sharp Selection)**: A technique that can reduce some coefficients to zero, effectively performing feature selection.",
    "**Elastic Net Regression (The Balanced Strike)**: A regularized regression method that linearly combines the L1 and L2 penalties of the Lasso and Ridge methods.",
    "**Multicollinearity (The Tangled Web of Variables)**: A phenomenon in which one predictor variable in a multiple regression model can be linearly predicted from the others with a substantial degree of accuracy.",
    "**R-Squared (Coefficient of Determination) (The Measure of the Saga's Accuracy)**: The proportion of the variance in the dependent variable that is predictable from the independent variable(s).",
    "**Adjusted R-Squared (The Honest Reward)**: A modified version of R-squared that has been adjusted for the number of predictors in the model.",
    "**Heteroscedasticity (The Uneven Waves)**: When the variance of the errors is not constant across all levels of an independent variable.",
    "**Homoscedasticity (The Calm Sea)**: When the variance of the errors is constant across all levels of an independent variable.",
    "**GLM (Generalized Linear Model) (The Universal Pattern)**: A flexible generalization of ordinary linear regression that allows for response variables that have error distribution models other than a normal distribution.",
    "**Poisson Regression (Counting the Raiders)**: A form of regression analysis used to model count data and contingency tables.",
    "**Survival Analysis (The Endurance of the Shield-Wall)**: A branch of statistics for analyzing the expected duration of time until one or more events happen (e.g., failure in mechanical systems).",
    "**Kaplan-Meier Estimator (The Chronicle of the Fallen)**: A non-parametric statistic used to estimate the survival function from lifetime data.",
    "**Cox Proportional Hazards Model (The Risk of the Sea)**: A regression model for investigating the association between the survival time of patients and one or more predictor variables.",
    "**Time Series Analysis (The Echoes of the Past)**: Methods for analyzing time series data in order to extract meaningful statistics and other characteristics of the data.",
    "**Stationarity (The Eternal Present)**: A property of time series where the mean, variance, and autocorrelation structure do not change over time.",
    "**Autocorrelation (The Repeated Pattern of the Seasons)**: The correlation of a signal with a delayed version of itself as a function of delay.",
    "**ARIMA (Autoregressive Integrated Moving Average) (The Oracle of the Winds)**: A class of models that explains a given time series based on its own past values.",
    "**Exponential Smoothing (The Weight of Recent Memory)**: A rule of thumb technique for smoothing time series data using the exponential window function.",
    "**Seasonality (The Cycle of the Sun and Moon)**: Periodic fluctuations in a time series that occur at regular intervals.",
    "**Prophet (Facebook) (The Skald's Modern Vision)**: A tool for forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality.",
    "**ANOVA (Analysis of Variance) (Comparing the Clans)**: A collection of statistical models and their associated estimation procedures used to analyze the differences among group means in a sample.",
    "**MANOVA (Multivariate Analysis of Variance) (Comparing Many Traits)**: An extension of ANOVA for use when there is more than one dependent variable.",
    "**Chi-Square Test (The Measure of Discrepancy)**: A statistical test applied to sets of categorical data to evaluate how likely it is that any observed difference between the sets arose by chance.",
    "**Non-Parametric Tests (The Law Beyond the Curve)**: Statistical tests that do not assume that the data follows a specific distribution (like the normal distribution).",
    "**Mann-Whitney U Test (The Generic Comparison)**: A non-parametric test of the null hypothesis that it is equally likely that a randomly selected value from one population will be less than or greater than a randomly selected value from a second population.",
    "**Kruskal-Wallis Test (Comparing the Tribes without Assumptions)**: A non-parametric method for testing whether samples originate from the same distribution.",
    "**Bootstrapping (The Self-Reliant Seer)**: A test or metric that relies on random sampling with replacement.",
    "**Jackknife Resampling (The Small-Scale Check)**: A cross-validation technique used to estimate the bias and variance of a statistic.",
    "**Entropy (The Measure of Chaos)**: A measure of the randomness or information content in a system.",
    "**Information Gain (The Benefit of the New Rune)**: The change in information entropy from a prior state to a state that takes some information as given.",
    "**Gini Impurity (The Measure of the Mixed-Blood)**: A measure of how often a randomly chosen element from the set would be incorrectly labeled if it was randomly labeled according to the distribution of labels in the subset.",
    "**Probability Theory (The Laws of Ginnungagap)**: The branch of mathematics concerning numerical descriptions of how likely an event is to occur.",
    "**Central Limit Theorem (The Convergence of Souls)**: Establishes that, in many situations, for independent and identically distributed random variables, the properly normalized sum tends toward a normal distribution.",
    "**Law of Large Numbers (The Truth of the Great Gathering)**: A theorem that describes the result of performing the same experiment a large number of times.",
    "**Stochastic Process (The Random Flow of the World)**: A family of random variables, which is a common way to model the evolution of a random system over time.",
    "**Markov Chain (The Path without Memory)**: A stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event.",
    "**Monte Carlo Method (The Roll of the Divine Dice)**: A broad class of computational algorithms that rely on repeated random sampling to obtain numerical results.",
    "**MCMC (Markov Chain Monte Carlo) (The Deep Sea Sampling)**: A class of algorithms for sampling from a probability distribution based on constructing a Markov chain that has the desired distribution as its equilibrium distribution.",
    "**Metropolis-Hastings Algorithm (The Selective Acceptance)**: An MCMC method for obtaining a sequence of random samples from a probability distribution.",
    "**Gibbs Sampling (The One-by-One Discovery)**: An MCMC algorithm for generating a sequence of samples from the multivariate probability distribution of two or more random variables.",
    "**Data Visualization (The Art of the Skald)**: Deep dives into presenting the truth clearly to the Jarl.",
    "**Pre-attentive Attributes (The Instant Recognition)**: Visual properties like color, size, and orientation that the human brain processes in milliseconds without conscious effort.",
    "**Tufte's Data-Ink Ratio (The Minimalist's Creed)**: The proportion of a graphic's ink devoted to the non-redundant display of data-information.",
    "**Cognitive Load (The Burden of the Unclear Map)**: The amount of working memory resources used in the brain to understand a visual.",
    "**Choropleth Map (The Shading of the Realm)**: A thematic map in which areas are shaded or patterned in proportion to the measurement of the statistical variable being displayed.",
    "**Heat Map (The Glow of Activity)**: A data visualization technique that shows magnitude of a phenomenon as color in two dimensions.",
    "**Treemap (The Branching Forest of Values)**: A method for displaying hierarchical data using nested figures, usually rectangles.",
    "**Parallel Coordinates (The Threaded Comparison)**: A common way of visualizing high-dimensional geometry and analyzing multivariate data.",
    "**Sankey Diagram (The Flow of the River)**: A type of flow diagram in which the width of the arrows is proportional to the flow rate.",
    "**Radial Chart (The Circle of the Nine Realms)**: A chart that displays data using concentric circles or slices.",
    "**Data Storytelling (The Oral Tradition of the Data)**: Communicating insights from data using narratives and visualizations.",
    "**Dashboards (The Command-Center of the Longship)**: A type of graphical user interface which often provides at-a-glance views of key performance indicators (KPIs).",
    "**Tableau (The Modern Seer's Canvas)**: A popular commercial interactive data visualization software company focused on business intelligence.",
    "**Power BI (The Empire's Ledger)**: A business analytics service by Microsoft.",
    "**D3.js (The Master-Crafter's Logic)**: A JavaScript library for producing dynamic, interactive data visualizations in web browsers.",
    "**Grammar of Graphics (The Skeleton of Viz)**: A tool that enables us to describe the structural components of a graphic.",
    "**ggplot2 (The Skald's Brush in R)**: A data visualization package for the statistical programming language R.",
    "**Machine Learning for Data Science (The Forge of the Future)**: Applying predictive power to historical records.",
    "**Supervised Learning (The Guided Path)**: The machine learning task of learning a function that maps an input to an output based on example input-output pairs.",
    "**Unsupervised Learning (The Explorer's Freedom)**: A type of machine learning that looks for previously unknown patterns in a data set without pre-existing labels.",
    "**Ensemble Learning (The Council of Models)**: Using multiple learning algorithms to obtain better predictive performance than could be obtained from any of the constituent learning algorithms alone.",
    "**Bagging (Bootstrap Aggregating) (The Weighted Vote of the Clan)**: Designing an ensemble which combines many independent models to reduce variance.",
    "**Boosting (The Consecutive Strength)**: An ensemble method that trains models sequentially, each one trying to correct the errors of its predecessor.",
    "**Stacking (The Tiered Wisdom)**: Combining multiple regression or classification models via a meta-classifier or a meta-regressor.",
    "**XGBoost (Extreme Gradient Boosting)**: An open-source software library which provides a regularized gradient boosting framework.",
    "**LightGBM (The Swift Strike)**: A high-performance gradient boosting framework based on decision tree algorithms.",
    "**CatBoost (The Master of the Categorical Tribe)**: An algorithm for gradient boosting on decision trees with special support for categorical features.",
    "**Hyperparameter Optimization (The Fine-Tuning of the Forge)**: The problem of choosing a set of optimal hyperparameters for a learning algorithm.",
    "**Grid Search (The Systematic Search of the Fields)**: A method of hyperparameter optimization that tries every combination.",
    "**Random Search (The Scout's Discretion)**: A method that tries random combinations, often finding good results much faster.",
    "**Cross-Validation (The Repeated Trial)**: A resampling procedure used to evaluate machine learning models on a limited data sample.",
    "**K-Fold Cross-Validation (The Split Clan Trial)**: Partitioning the data into 'K' groups and testing the model 'K' times.",
    "**Overfitting (The Tale Too Fine for One Realm)**: When a model learns the detail and noise in the training data to the extent that it negatively impacts the performance of the model on new data.",
    "**Feature Importance (The Weight of the Ancestral Deed)**: A technique that assigns a score to input features based on how useful they are at predicting a target variable.",
    "**SHAP (SHapley Additive exPlanations) (Fair Credit for the Rune)**: A game theoretic approach to explain the output of any machine learning model.",
    "**LIME (Local Interpretable Model-agnostic Explanations) (The Local Truth)**: An explanation technique that explains the predictions of any classifier in an interpretable and faithful manner by learning it locally around the prediction.",
    "**Data Leakage (The Enemy Spy in the Forge)**: When information from outside the training dataset is used to create the model, leading to overly optimistic results.",
    "**Class Imbalance (The Uneven Battle)**: When the classes of the target variable are not represented equally in the dataset.",
    "**SMOTE (Synthetic Minority Over-sampling Technique) (Forging New Warriors)**: A technique to handle class imbalance by creating synthetic examples of the minority class.",
    "**Principal Component Analysis (PCA) (The Essence-Stone)**: A statistical procedure that uses an orthogonal transformation to convert a set of observations of possibly correlated variables into a set of values of linearly uncorrelated variables called principal components.",
    "**t-SNE (t-Distributed Stochastic Neighbor Embedding) (Mapping the High Realms to Flat Stones)**: A non-linear dimensionality reduction technique well-suited for embedding high-dimensional data for visualization in a low-dimensional space of two or three dimensions.",
    "**UMAP (Uniform Manifold Approximation and Projection) (The Great Map of the Multiverse)**: A novel manifold learning technique for dimension reduction.",
    "**Big Data Tech: Hadoop (The Great Hall of Storage)**: An open-source software framework used for distributed storage and processing of dataset of big data using the MapReduce programming model.",
    "**Big Data Tech: Spark (The Lightning Spark of Compute)**: An open-source unified analytics engine for large-scale data processing.",
    "**Big Data Tech: Kafka (The Endless Stream of Messages)**: An open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.",
    "**Big Data Tech: Hive (The Honey-Vault of Data)**: A data warehouse software project built on top of Apache Hadoop for providing data query and analysis.",
    "**Big Data Tech: Presto (The Fast Oracle of SQL)**: An open-source distributed SQL query engine for running interactive analytic queries against data sources of all sizes ranging from gigabytes to petabytes.",
    "**Data Governance (The Law of the Archive)**: The overall management of the availability, usability, integrity, and security of data used in an enterprise.",
    "**Data Provenance (The Lineage of the Hero)**: A record that describes the people, institutions, entities, and processes involved in producing data.",
    "**Sigrid's Proverb: 'One who stares at the shadow of the crow knows its flight, but one who calculates the wind knows where its next shadow will fall. To know the data is to predict the flight.'**",
    "**The 1000 Runes of the Seer's Insight are complete. The horizon of knowledge expands.**"
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 501 - 1000\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+501}. {entry}\n")
    
    current_count = len(entries)
    for j in range(current_count + 501, 1001):
        f.write(f"{j}. **Data Science Concept {j} (The Continued Insight)**: Delving deeper into the hidden patterns of the world, guided by the wisdom of the Norns.\n")
