import os

file_path = r"c:\Users\volma\anti-gravity-githublocal-NorseSaga-Engine\Viking_girlfriend_openclaw_skill\viking_girlfriend_skill\data\knowledge_reference\SOFTWARE_ENGINEERING.md"

entries = [
    "**Programming Language Theory (PLT) (The Lore of the Runes)**: A branch of computer science that deals with the design, implementation, analysis, characterization, and classification of programming languages.",
    "**Abstract Syntax Tree (AST) (The Branching Tree of Code)**: A tree representation of the abstract syntactic structure of source code written in a programming language.",
    "**Intermediate Representation (IR)**: The data structure or code used internally by a compiler or virtual machine to represent source code.",
    "**Bytecode (The Compact Runes)**: Computer object code that is processed by a program, usually referred to as a virtual machine, rather than by the 'real' computer machine, the hardware processor.",
    "**Just-In-Time (JIT) Compilation (The Instant Forging)**: A way of executing computer code that involves compilation during execution of a program (at run time) rather than before execution.",
    "**Ahead-Of-Time (AOT) Compilation**: The act of compiling a higher-level programming language into a lower-level language before execution of a program.",
    "**Static vs Dynamic Typing (The Fixed vs Flowing Law)**: Whether types are checked at compile-time or run-time.",
    "**Strong vs Weak Typing**: How strictly types are enforced by the language.",
    "**Duck Typing (The Shape-Shifter's Rule)**: An application of the duck test in dynamic languages: 'If it walks like a duck and it quacks like a duck, then it must be a duck'.",
    "**Structural vs Nominal Typing**: Typing based on the structure of the data vs the name of its type.",
    "**Type Inference (The Seer's Deduction)**: Automatically detecting the data type of an expression in a programming language.",
    "**Generics (Polymorphism)**: Using a single symbol to represent multiple types.",
    "**Parametric Polymorphism**: A way to make a language more expressive, while still maintaining full static type-safety.",
    "**Ad-hoc Polymorphism (Function Overloading)**: Allowing functions with the same name to act differently based on the types of their arguments.",
    "**Subtype Polymorphism (Inheritance)**: Allowing a variable of a specific type to also hold a variable of its subtypes.",
    "**Metaprogramming (Code that Writes Code)**: A programming technique in which computer programs have the ability to treat other programs as their data.",
    "**Macros (Macro-Expansion)**: A rule or pattern that specifies how a certain input sequence should be mapped to a replacement output sequence.",
    "**Reflection (The Mirroring Rune)**: The ability of a process to examine, introspect, and modify its own structure and behavior.",
    "**Introspection (Programming)**: The ability of a program to examine the type or properties of an object at runtime.",
    "**Garbage Collection (GC) (The Digital Cleansing)**: A form of automatic memory management.",
    "**Reference Counting (The Soul-Counter)**: A technique of storing the number of references, pointers, or handles to a resource, such as an object, a block of memory, disk space, and others.",
    "**Tracing Garbage Collection (The Search for the Lost)**: A type of garbage collection that identifies 'live' objects by tracing which objects are reachable by a chain of references from certain 'root' objects.",
    "**Mark-and-Sweep**: A two-phase tracing garbage collection algorithm.",
    "**Stop-the-World GC**: A garbage collection event that pauses the execution of the entire application.",
    "**Concurrent Garbage Collection**: Garbage collection that happens while the application is still running.",
    "**Generational Garbage Collection**: An optimization of tracing garbage collectors that categorizes objects by their age.",
    "**Young Generation (Eden, Survivors)**: The area of memory where newly created objects are placed.",
    "**Old Generation (Tenured)**: The area of memory where long-lived objects are moved.",
    "**Finalizer (The Vessel-Purger)**: A method that is called by the garbage collector before an object is reclaimed.",
    "**Memory Leak (The Slow Leak of Urd's Well)**: A failure in a program to release discarded memory, causing performance to deteriorate and eventually leading to failure.",
    "**Memory Fragmentation**: A phenomenon in which storage space is used inefficiently, reducing capacity and performance.",
    "**Internal vs External Fragmentation**: Fragmentation within a single block vs fragmentation between blocks.",
    "**Memory Layout (Stack, Heap, Data Segment, Code Segment)**: How memory is organized within a process.",
    "**Stack Memory (Fixed & Fast)**: Memory used for local variables and function call management.",
    "**Heap Memory (Dynamic & Large)**: Memory used for long-lived objects and dynamic allocations.",
    "**Virtual Memory (Mapping the Realm)**: A memory management technique that provides an 'idealized' abstraction of the storage resources that are actually available on a given machine.",
    "**Page (Memory Management)**: A fixed-length contiguous block of virtual memory.",
    "**Frame (Memory Management)**: A fixed-length contiguous block of physical memory.",
    "**Page Table (The Great Map)**: The data structure used by a virtual memory system in a computer operating system to store the mapping between virtual addresses and physical addresses.",
    "**TLB (Translation Lookaside Buffer)**: A memory cache that is used to reduce the time taken to access a user memory location.",
    "**Page Fault (The Missing Link)**: An exception that occurs when a program attempts to access data that is not currently in physical memory.",
    "**Thrashing (Memory)**: When a computer's virtual memory resources are overused, leading to a constant state of paging and page faults.",
    "**Memory Overcommit**: A situation where an operating system allows more memory to be allocated to processes than is actually available in physical RAM and swap space.",
    "**OOM (Out-of-Memory) Killer**: A process in Linux that kills one or more processes to free up memory when the system is dangerously low on RAM.",
    "**Direct Memory Access (DMA)**: A feature of computer systems that allows certain hardware subsystems to access main system memory (RAM) independently of the central processing unit (CPU).",
    "**Caches (L1, L2, L3)**: Small, fast memory buffers located close to the CPU.",
    "**Cache Locality (Temporal & Spatial)**: The principle that data accessed together in time or space should be stored together in cache.",
    "**False Sharing (Cache Performance)**: A performance-degrading usage pattern that can arise in systems with distributed, coherent caches.",
    "**Memory Barrier / Fence (The Iron Wall)**: A type of barrier instruction that causes a central processing unit (CPU) or compiler to enforce an ordering constraint on memory operations.",
    "**Memory Consistency Models (TSO, Weak)**: Rules that specify how memory operations appear to other processors.",
    "**Atomicity (Memory Operations)**: An operation is atomic if it appears to happen instantaneously to the rest of the system.",
    "**Compare-and-Swap (CAS)**: An atomic instruction used in multithreading to achieve synchronization.",
    "**Lock-Free Programming**: A programming technique that avoids the use of locks to achieve synchronization.",
    "**Wait-Free Programming**: A stronger guarantee than lock-free, where every thread is guaranteed to make progress.",
    "**Obstruction-Free Programming**: A weaker guarantee than lock-free, where a thread makes progress only if no other threads are interfering.",
    "**Mutex (Mutual Exclusion)**: A synchronization primitive that prevents multiple threads from accessing a shared resource simultaneously.",
    "**Semaphore (Counting & Binary)**: A synchronization primitive that controls access to a common resource by multiple processes in a concurrent system.",
    "**Condition Variable**: A synchronization primitive that allows threads to wait until a specific condition is met.",
    "**Monitor (Synchronization)**: A high-level synchronization construct that combines data and synchronization primitives.",
    "**Deadlock (The Eternal Standoff)**: A situation where two or more threads are blocked forever, each waiting for the other.",
    "**Livelock**: A situation where two or more threads continually change their state in response to each other without making any progress.",
    "**Starvation (Thread Scheduling)**: A situation where a thread is perpetually denied the resources it needs to make progress.",
    "**Priority Inversion**: A situation where a low-priority thread holds a resource needed by a high-priority thread, effectively delaying the high-priority thread.",
    "**Priority Inheritance**: A technique for solving priority inversion by temporarily increasing the priority of the thread holding the resource.",
    "**Coroutines (The Cooperative Runners)**: Computer program components that generalize subroutines for non-preemptive multitasking, by allowing execution to be suspended and resumed.",
    "**Green Threads**: Threads that are scheduled by a runtime library or VM instead of by the operating system.",
    "**Fibers (Programming)**: A lightweight thread that uses cooperative multitasking.",
    "**CSP (Communicating Sequential Processes)**: A formal language for describing patterns of interaction in concurrent systems, and the basis for Go's concurrency model.",
    "**Channels (Go / CSP)**: A synchronization primitive used for communication between concurrent processes.",
    "**Select Statement (Go Concurrency)**: A control structure that allows a goroutine to wait on multiple communication operations.",
    "**Actors (Actor Model)**: A mathematical model of concurrent computation that treats 'actor' as the universal primitive of concurrent computation.",
    "**Erlang / Elixir (The Actor Specialists)**: Programming languages designed specifically for distributed, fault-tolerant systems using the actor model.",
    "**BEAM (Erlang Virtual Machine)**: The virtual machine that runs Erlang and Elixir code.",
    "**OTP (Open Telecom Platform)**: A set of Erlang libraries and design principles for building robust systems.",
    "**Supervision Tree (OTP)**: A hierarchical structure for managing the lifecycle and failure recovery of actors.",
    "**Hot Code Loading (The Living Update)**: The ability to change the code of a running program without stopping it.",
    "**Software Transactional Memory (STM)**: A concurrency control mechanism analogous to database transactions for controlling access to shared memory.",
    "**RAII (Resource Acquisition Is Initialization) (The Vessel-Duty)**: A C++ programming technique which binds the lifecycle of a resource to the lifetime of an object.",
    "**Smart Pointers (unique_ptr, shared_ptr, weak_ptr)**: Objects that manage the lifetime of a pointer and ensure proper cleanup.",
    "**Move Semantics**: A C++11 feature that allows the efficient transfer of resources between objects.",
    "**Copy-on-Write (COW)**: A resource-management technique used in computer programming to efficiently implement a 'duplicate' or 'copy' operation on modifiable resources.",
    "**Ownership and Borrowing (Rust Model)**: A memory management system that guarantees memory safety without a garbage collector.",
    "**Lifetimes (Rust)**: A concept used by the Rust compiler to ensure that references are always valid.",
    "**Trait (Rust / Scala)**: A way to define shared behavior in a generic way.",
    "**Pattern Matching (The Rune-Recognition)**: A mechanism for checking a value against a pattern.",
    "**Algebraic Data Types (ADTs)**: A type of composite type, i.e., a type formed by combining other types.",
    "**Sum Types vs Product Types**: Unions (Enums) vs Structs (Records).",
    "**Options & Results (Error Handling)**: Expressing the possibility of absence or failure using the type system.",
    "**Monadic Error Handling**: Using monads (like Option or Result) to handle errors in a functional way.",
    "**Exception Handling (Try-Catch-Finally)**: A programming language construct designed to handle the occurrence of exceptions.",
    "**Checked vs Unchecked Exceptions**: Whether exceptions must be declared in the function signature.",
    "**Error Codes vs Exceptions**: Comparing different approaches to handling error states.",
    "**Stack Unwinding**: The process of removing entries from the call stack until an exception handler is found.",
    "**Zero-Cost Abstractions**: A principle in systems programming where you don't pay for what you don't use.",
    "**Standard Template Library (STL)**: A software library for the C++ programming language that influenced many parts of the C++ Standard Library.",
    "**Expression Templates**: A C++ technique that uses templates to represent expressions as objects.",
    "**CRTP (Curiously Recurring Template Pattern)**: A C++ idiom where a class X derives from a class template instantiation using X itself as a template argument.",
    "**SFINAE (Substitution Failure Is Not An Error)**: A C++ template metaprogramming technique.",
    "**RAII for Locks & Files**: Automatically releasing resources when they go out of scope.",
    "**The C++ Object Model**: The way that C++ represents objects and their relationships in memory.",
    "**Virtual Method Table (vtable)**: A mechanism used in programming languages to support dynamic dispatch (or run-time method binding).",
    "**Dynamic Dispatch (The Late Binding)**: The process of selecting which implementation of a polymorphic operation to call at run time.",
    "**Static Dispatch (The Early Binding)**: The process of selecting which implementation of a polymorphic operation to call at compile time.",
    "**Inline Functions**: A request to the compiler to insert the code of a function directly at the call site.",
    "**Link-Time Optimization (LTO)**: An optimization performed by the linker that can see across different source files.",
    "**Profile-Guided Optimization (PGO)**: An optimization technique that uses data from actual program execution to guide the compiler.",
    "**Instruction Set Architecture (ISA)**: An abstract model of a computer.",
    "**CISC vs RISC (Complex vs Reduced Instruction Set Computer)**: Two different philosophies for designing CPUs.",
    "**x86-64 (The Giant's Language)**: The 64-bit version of the x86 instruction set.",
    "**ARM (AArch64)**: A family of reduced instruction set computer (RISC) architectures for computer processors.",
    "**MIPS & PowerPC**: Other notable CPU architectures.",
    "**RISC-V (The Open Rune)**: An open-standard instruction set architecture (ISA) based on established reduced instruction set computer (RISC) principles.",
    "**GPU Architecture (SIMT - Single Instruction Multiple Threads)**: Specialized hardware for parallel processing.",
    "**CUDA (NVIDIA)**: A parallel computing platform and application programming interface (API) model created by Nvidia.",
    "**OpenCL**: A framework for writing programs that execute across heterogeneous platforms.",
    "**Vulkan & Metal (High Performance Graphics APIs)**: Next-generation graphics and compute APIs with low overhead.",
    "**DirectX 12**: A collection of application programming interfaces (APIs) for handling tasks related to multimedia, especially game programming and video, on Microsoft platforms.",
    "**Shaders (Vertex, Fragment/Pixel, Compute)**: Programs that run on the GPU.",
    "**HLSL & GLSL**: High-level shading languages for DirectX and OpenGL/Vulkan.",
    "**Compute Shaders**: Shaders used for general-purpose computing on the GPU.",
    "**GPGPU (General-Purpose computing on Graphics Processing Units)**: Using a GPU to perform computation in applications traditionally handled by the CPU.",
    "**Ray Tracing (Hardware-Accelerated)**: A rendering technique that simulates the physical behavior of light.",
    "**DLSS (Deep Learning Super Sampling)**: An NVIDIA technology that uses AI to upscale images in real-time.",
    "**FSR (FidelityFX Super Resolution)**: AMD's open-source upscaling technology.",
    "**Latency vs Throughput (The Fast vs The Many)**: Comparing how quickly a single task can be completed vs how many tasks can be completed in a given time.",
    "**Branch Prediction (The Scholar's Guess)**: A feature of modern CPUs that attempts to guess which way a conditional jump will go.",
    "**Speculative Execution**: The process by which a computer system performs some task that may not be needed.",
    "**Out-of-Order Execution**: A paradigm used in most high-performance microprocessors to make use of instruction cycles that would otherwise be wasted.",
    "**Superscalar Architecture**: A CPU that can execute more than one instruction per clock cycle.",
    "**Vectorization (SIMD - Single Instruction Multiple Data)**: Performing the same operation on multiple data points simultaneously.",
    "**AVX-512**: An extension to the x86 instruction set architecture for vector processing.",
    "**NEON (ARM)**: The SIMD instruction set for ARM processors.",
    "**Endianness (Little-Endian vs Big-Endian) (The Byte-Order Law)**: The order or sequence in which bytes of a multi-byte digital data are stored in computer memory.",
    "**Alignment (Memory)**: The requirement that certain data types must be stored at memory addresses that are multiples of their size.",
    "**Padding (Structs)**: Extra bytes added to a structure to ensure proper alignment of its members.",
    "**Packing (Structs)**: Removing padding from a structure to save memory, often at the cost of performance.",
    "**Inter-Process Communication (IPC)**: Methods for processes to communicate and synchronize their actions.",
    "**Pipes & Named Pipes**: Unidirectional or bidirectional communication channels between processes.",
    "**Message Queues (IPC)**: A communication method where processes send messages to a queue.",
    "**Shared Memory (The Common Well)**: A method where multiple processes can access the same physical memory segment.",
    "**Memory-Mapped Files (mmap)**: Mapping the contents of a file directly into the address space of a process.",
    "**Unix Domain Sockets**: A data communications endpoint for exchanging data between processes executing on the same host operating system.",
    "**Signals (Unix)**: A limited form of inter-process communication used in Unix-like operating systems to notify processes of events.",
    "**Wait & Exit Codes**: How a parent process learns about the termination of its child process.",
    "**Zombie Process (The Unburied Spirit)**: A process that has completed execution but still has an entry in the process table.",
    "**Orphan Process**: A process whose parent process has finished or terminated.",
    "**Daemon Process**: A computer program that runs as a background process, rather than being under the direct control of an interactive user.",
    "**Init System (PID 1)**: The first process started during booting of the computer system.",
    "**Systemd**: A software suite that provides fundamental building blocks for a Linux operating system, including an init system.",
    "**Kernel (The Realm-Heart)**: The core of an operating system, with complete control over everything in the system.",
    "**Monolithic Kernel**: A kernel architecture where the entire operating system is working in kernel space.",
    "**Microkernel (The Lean Ruler)**: A kernel architecture where the kernel is kept as small as possible and most services run in user space.",
    "**Hybrid Kernel**: A kernel architecture that combines aspects of monolithic and microkernel designs.",
    "**Exokernel**: An operating system kernel that provides as few abstractions as possible, allowing applications to manage their own resources.",
    "**Nanokernel**: An even smaller version of a microkernel.",
    "**Unikernel**: Specialized, single-address-space machine images constructed by using library operating systems.",
    "**Library Operating System**: An operating system where the OS is a library that is linked with the application.",
    "**Hypervisor (Type 1 & Type 2)**: Software that creates and runs virtual machines.",
    "**Native Hypervisor (Type 1 - Bare Metal)**: Runs directly on the host's hardware.",
    "**Hosted Hypervisor (Type 2)**: Runs as an application on an existing operating system.",
    "**Paravirtualization**: A virtualization technique where the guest OS is aware that it's running in a virtual environment.",
    "**Full Virtualization**: A virtualization technique where the guest OS is completely unaware that it's running in a virtual environment.",
    "**Hardware-Assisted Virtualization (VT-x, AMD-V)**: CPU features that improve the performance of virtual machines.",
    "**IOMMU (Input-Output Memory Management Unit)**: A memory management unit (MMU) that connects a DMA-capable I/O bus to the main memory.",
    "**SR-IOV (Single Root I/O Virtualization)**: A specification that allows a single PCIe physical device to appear as multiple separate logical devices.",
    "**VirtIO**: A virtualization standard for network and disk device drivers where just the guest's device driver 'knows' it is running in a virtual environment.",
    "**Snapshotting (VM)**: Saving the current state of a virtual machine.",
    "**Live Migration (VM)**: Moving a running virtual machine from one physical host to another with minimal downtime.",
    "**Vagrant (VM Orchestration)**: A tool for building and managing virtual machine environments.",
    "**Docker (Containerization) (The Sealed Vessel)**: A set of platform as a service products that use OS-level virtualization to deliver software in packages called containers.",
    "**Container vs VM**: Explaining why containers are lighter and faster than virtual machines.",
    "**Namespaces (Linux)**: A feature of the Linux kernel that isolates and virtualizes system resources for a collection of processes.",
    "**Cgroups (Control Groups)**: A Linux kernel feature that limits, accounts for, and isolates the resource usage of a collection of processes.",
    "**Union File System (UnionFS)**: A file system service which implements a union mount for other file systems.",
    "**Docker Image (The Blueprint of the Vessel)**: A read-only template used to create Docker containers.",
    "**Docker Container (The Active Vessel)**: A runnable instance of a Docker image.",
    "**Docker Registry (The Port of Call)**: A place to store and distribute Docker images.",
    "**Dockerfile**: A text document that contains all the commands a user could call on the command line to assemble an image.",
    "**Multi-stage Builds (Docker)**: An optimization technique for creating small and secure Docker images.",
    "**Layer Caching (Docker)**: Speeds up the build process by reusing layers from previous builds.",
    "**Docker Compose**: A tool for defining and running multi-container Docker applications.",
    "**Podman (Daemonless Docker Alternative)**: A daemonless, open source, Linux native tool for deployed applications using Open Container Initiative (OCI) Containers.",
    "**Buildah**: A tool that facilitates building OCI images.",
    "**Skopeo**: A command line utility that performs various operations on container images and image repositories.",
    "**Kaniko**: A tool to build container images from a Dockerfile, inside a container or Kubernetes cluster.",
    "**Rootless Containers**: Running containers without root privileges for improved security.",
    "**Singularity (Apptainer)**: A container platform designed for HPC (High Performance Computing).",
    "**LXC (Linux Containers)**: An OS-level virtualization method for running multiple isolated Linux systems on a single control host.",
    "**LXD**: A next-generation system container manager.",
    "**Kata Containers**: A project for building lightweight virtual machines that feel and perform like containers but provide the workload isolation of VMs.",
    "**Firecracker (AWS)**: An open source virtualization technology that is purpose-built for creating and managing secure, multi-tenant container and function-based services.",
    "**Gvisor (Google)**: A user-space kernel for containers that provides a strong security boundary.",
    "**Runtime Specification (OCI)**: A standard for container runtimes.",
    "**Image Specification (OCI)**: A standard for container images.",
    "**CRI (Container Runtime Interface)**: A plugin interface which enables kubelet to use a wide variety of container runtimes.",
    "**Containerd**: An industry-standard container runtime with an emphasis on simplicity, robustness and portability.",
    "**CRI-O**: A lightweight container runtime for Kubernetes.",
    "**Docker Swarm (Obsolete)**: A clustering and scheduling tool for Docker containers.",
    "**Nomad (HashiCorp) (The Wanderer)**: A simple and flexible work orchestrator to deploy and manage containers and non-containerized applications across on-prem and clouds.",
    "**Mesos / Marathon (Classic)**: A cluster manager that provides efficient resource isolation and sharing across distributed applications.",
    "**High Performance Computing (HPC)**: The use of parallel processing for running complex application programs efficiently, reliably and quickly.",
    "**Beowulf Cluster**: A multi-computer architecture which can be used for parallel computations.",
    "**MPI (Message Passing Interface)**: A standardized and portable message-passing system designed to function on a wide variety of parallel computing architectures.",
    "**Slurm (Workload Manager)**: A free open-source job scheduler for Linux and Unix-like kernels, used by many of the world's supercomputers and computer clusters.",
    "**Lustre & BeeGFS**: High-performance parallel file systems used in HPC.",
    "**Infiniband**: A computer-networking communications standard used in high-performance computing that features very high throughput and very low latency.",
    "**RDMA (Remote Direct Memory Access)**: A feature that allows a computer to access the memory of another computer without involving either computer's operating system.",
    "**Distributed Computing (The Gathering of the Thing)**: A field of computer science that studies distributed systems.",
    "**The Eight Fallacies of Distributed Computing**: A set of false assumptions made by programmed who are new to distributed applications.",
    "**Fallacy 1: The network is reliable.**",
    "**Fallacy 2: Latency is zero.**",
    "**Fallacy 3: Bandwidth is infinite.**",
    "**Fallacy 4: The network is secure.**",
    "**Fallacy 5: Topology doesn't change.**",
    "**Fallacy 6: There is one administrator.**",
    "**Fallacy 7: Transport cost is zero.**",
    "**Fallacy 8: The network is homogeneous.**",
    "**CAP Theorem (Consistency, Availability, Partition Tolerance)**: States that it is impossible for a distributed data store to simultaneously provide more than two out of the three guarantees.",
    "**PACELC Theorem**: An extension to the CAP theorem that also considers the trade-off between latency and consistency during normal execution.",
    "**BASE (Basically Available, Soft state, Eventual consistency)**: An alternative to ACID for distributed systems.",
    "**Replicated State Machines**: A general method for implementing a fault-tolerant service by replicating servers and coordinating client interactions with server replicas.",
    "**Byzantine Fault Tolerance (BFT) (The Traitor's Problem)**: The resistance of a distributed computer system to the 'Byzantine Generals Problem'.",
    "**Practical Byzantine Fault Tolerance (PBFT)**: An algorithm for state machine replication that provides BFT.",
    "**Quorum (Distributed Systems)**: The minimum number of votes that a distributed transaction has to obtain in order to be allowed to perform an operation in a distributed system.",
    "**Leader Election (Choosing the Jarl)**: The process of designating a single process as the organizer of some task distributed among several computers.",
    "**Chubby (Google)**: A lock service for loosely coupled distributed systems.",
    "**ZooKeeper (Apache) (The Beast-Keeper)**: A centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.",
    "**Etcd (The Store of the World)**: A strongly consistent, distributed key-value store that provides a reliable way to store data that needs to be accessed by a distributed system or cluster of machines.",
    "**Hashicorp Consul (The Messenger of Information)**: A service networking solution to connect and secure services across any runtime platform and public or private cloud.",
    "**Service Discovery (Locating the Settlement)**: The process of automatically detecting devices and services on a computer network.",
    "**Dynamic Service Discovery**: Service discovery that handles nodes joining and leaving the network automatically.",
    "**Health Checks (The Pulse of the Warrior)**: A way to determine if a service instance is healthy and capable of handling traffic.",
    "**Liveness Probe vs Readiness Probe (K8s)**: Checking if a container is running vs checking if it is ready to serve traffic.",
    "**Startup Probe (K8s)**: Checking if an application has finished starting up.",
    "**Graceful Shutdown (The Honorable Departure)**: Allowing a process to finish its current work and clean up resources before terminating.",
    "**Side-Channel Attack Mitigation (Constant Time)**: Making sure an algorithm's execution time doesn't depend on its inputs.",
    "**Air Gapping (The Deepest Shield)**: Physical isolation of a system.",
    "**Data Exfiltration (The Hidden Raid)**: The unauthorized transfer of data from a computer.",
    "**Infiltration (Cyber)**: The process of gaining clandestine access to a target system or network.",
    "**Kill Chain (Analysis)**: Using the kill chain model to identify points where an attack can be disrupted.",
    "**Security Posture**: The overall security status of an organization.",
    "**Risk Assessment**: The process of identifying, analyzing, and evaluating risks.",
    "**Risk Mitigation**: The process of reducing the impact or probability of a risk.",
    "**Risk Acceptance**: Choosing to accept a risk rather than mitigating it.",
    "**Risk Transference**: Moving a risk to another party (e.g. through insurance).",
    "**Business Continuity Planning (BCP)**: The process of creating systems of prevention and recovery to deal with potential threats to a company.",
    "**Disaster Recovery (DR) (The Great Restoration)**: The part of BCP that deals with the recovery of IT infrastructure and systems.",
    "**Recovery Point Objective (RPO) (Data Loss Boundary)**: The maximum age of files that an organization must recover from backup storage for its operations to resume after a disaster.",
    "**Recovery Time Objective (RTO) (Downtime Boundary)**: The targeted duration of time and a service level within which a business process must be restored after a disaster.",
    "**Failover (The Backup Plan)**: A procedure by which a system automatically transfers control to a duplicate system when it detects a fault or failure.",
    "**Failback**: The process of restoring a service to its original primary system after it was failed over.",
    "**High Availability (HA) (The Unshakeable Fortress)**: A characteristic of a system which aims to ensure an agreed level of operational performance, usually uptime, for a higher than normal period.",
    "**Redundancy (N+1, 2N)**: The duplication of critical components or functions of a system with the intention of increasing reliability of the system.",
    "**Single Point of Failure (SPOF)**: A part of a system that, if it fails, will stop the entire system from working.",
    "**Chaos Engineering (Testing the Ragnarok)**: The discipline of experimenting on a software system in production in order to build confidence in the system's capability to withstand turbulent and unexpected conditions.",
    "**Chaos Monkey (Netflix)**: A tool that randomly disables production instances to test for resilience.",
    "**Game Day (Chaos Engineering)**: A coordinated event where an engineering team practices responding to a simulated failure.",
    "**Fault Injection (Failure Testing)**: Intentionally introducing faults into a system to test its behavior.",
    "**Error Injection (Failure Testing)**: Intentionally introducing errors into a system to test its error handling.",
    "**Observability (The All-Seeing Eye)**: The ability to measure the internal states of a system by examining its outputs.",
    "**Monitoring vs Observability**: Reactive tracking vs Proactive understanding.",
    "**The Three Pillars of Observability: Logs, Metrics, and Traces.**",
    "**Golden Signals of Monitoring (LATENCY, TRAFFIC, ERRORS, SATURATION)**: The four key metrics for monitoring user-facing systems.",
    "**USE Method (Utilization, Saturation, Errors)**: A methodology for analyzing the performance of any system.",
    "**RED Method (Rate, Errors, Duration)**: A methodology for monitoring request-based services.",
    "**Contextual Logging**: Including relevant contextual information (e.g. user ID, request ID) in log messages.",
    "**Structured Logging (JSON Logging)**: Logging in a machine-readable format.",
    "**Log Correlation**: The process of linking related log messages from different sources.",
    "**Semantic Logging**: A logging approach where the meaning of the log message is formally defined.",
    "**Anomaly Detection (The Unnatural Sign)**: Identifying patterns in data that do not conform to expected behavior.",
    "**Outlier Detection (Statistical)**: Identifying observations that are distant from other observations.",
    "**Profiling (Performance)**: The process of analyzing a program's execution to identify performance bottlenecks.",
    "**CPU Profiling (Where is the time spent?)**",
    "**Memory Profiling (Where is the memory used?)**",
    "**I/O Profiling (Where is the bottleneck in disk/network?)**",
    "**Flame Graphs (The Visual Heatmap)**: A visualization technique for profiled software, showing which code paths are consuming resources.",
    "**Benchmark (The Test of Strength)**: The act of running a computer program, a set of programs, or other operations, in order to assess the relative performance of an object, normally by running a number of standard tests and trials against it.",
    "**Microbenchmarks (Testing the Small Things)**: Benchmarks that test a very specific, small part of a system.",
    "**Macrobenchmarks (Testing the Big Picture)**: Benchmarks that test the performance of a whole system or application.",
    "**End-to-End Performance Testing**: Measuring the performance of a system from the user's perspective.",
    "**A/B Testing (Split Testing)**: A randomized experiment with two variants, A and B.",
    "**Multivariate Testing**: A technique for testing a hypothesis in which multiple variables are modified.",
    "**Canary Release (The Bird in the Cave Deploy)**: A technique to reduce the risk of introducing a new software version in production by slowly rolling out the change to a small subset of users.",
    "**Blue-Green Deployment**: A technique that reduces downtime and risk by running two identical production environments.",
    "**Rolling Update**: A deployment strategy that replaces old instances of an application with new instances, one at a time.",
    "**Shadow Deployment (Mirroring)**: Deploying a new version of an application and mirroring production traffic to it without affecting users.",
    "**Feature Toggles / Feature Flags (The Switch of Fate)**: A technique in software development that attempts to provide an alternative to maintaining multiple branches in source code.",
    "**Dark Launching**: Releasing a new feature to a production environment without making it visible to users.",
    "**Continuous Integration (CI) (The Iron-Link of Building)**: The practice of merging all developers' working copies to a shared mainline several times a day.",
    "**Continuous Delivery (CD) (The Path to the Settlement)**: An approach in which teams produce software in short cycles, ensuring that the software can be reliably released at any time.",
    "**Continuous Deployment**: A higher level of CD where every change that passes the automated tests is automatically deployed to production.",
    "**Build Pipeline (The Smelting-Works)**: A set of automated processes that allow developers to reliably and efficiently build, test, and deploy their software.",
    "**Artifact (Software Build)**: A deployable component that is produced by the build process (e.g. a JAR file, an executable, a Docker image).",
    "**Artifact Repository (The Great Warehouse)**: A place to store and manage build artifacts (e.g. Nexus, Artifactory, Docker Hub).",
    "**Binary Repository Manager**: Another name for an artifact repository.",
    "**CI/CD Tools (Jenkins, GitHub Actions, GitLab CI, CircleCI)**: Platforms that provide the infrastructure for automation.",
    "**Jenkins (The Ancient Butler)**: One of the oldest and most popular open-source automation servers.",
    "**GitHub Actions (Modern Workflow)**: An automation platform integrated directly into GitHub.",
    "**GitLab CI/CD**: An integrated CI/CD tool within the GitLab platform.",
    "**Tekton (CI/CD on K8s)**: A powerful and flexible open-source framework for creating CI/CD systems for Kubernetes.",
    "**Dagger (CI/CD as Code)**: A portable dev engine that allows you to run your CI/CD pipelines as code.",
    "**BuildMatrix**: A feature of CI/CD systems that allows you to run tests against multiple versions of a language or library.",
    "**Self-Hosted Runners vs Managed Runners**: Where the build jobs actually execute.",
    "**Pipeline as Code**: Defining your build and deployment pipelines using machine-readable definition files (e.g. YAML).",
    "**Static Application Security Testing (SAST) (The Pre-Build Inspection)**: Analyzing source code for security vulnerabilities without executing it.",
    "**Dynamic Application Security Testing (DAST) (The Active Siege)**: Testing a running application for security vulnerabilities from the outside.",
    "**Software Composition Analysis (SCA) (Checking the Rations)**: Identifying and analyzing the third-party components and libraries used in an application.",
    "**Interactive Application Security Testing (IAST)**: A hybrid approach that combines SAST and DAST.",
    "**Dependency Scanning**: Automatically checking for known vulnerabilities in your project's dependencies.",
    "**Secret Scanning**: Automatically searching for secrets (e.g. API keys, passwords) in your source code and history.",
    "**Security Gates (CI/CD)**: Automated checks that prevent a build or deployment from proceeding if specific security criteria are not met.",
    "**DevSecOps (The Shielded Path)**: The integration of security practices into the DevOps process.",
    "**Shift Left Security**: Integrating security earlier in the software development lifecycle.",
    "**Shift Right Testing (Testing in Prod)**: Performing testing and monitoring in the production environment.",
    "**Post-Mortem (The Analysis of the Slain)**: A process used to evaluate a project or incident after it has been completed or resolved.",
    "**Blameless Post-Mortem**: A post-mortem that focuses on identifying systemic issues rather than pointing fingers at individuals.",
    "**Root Cause Analysis (RCA) (Finding the Deep Rot)**: A method of problem-solving used for identifying the root causes of faults or problems.",
    "**The 5 Whys**: An iterative interrogative technique used to explore the cause-and-effect relationships underlying a particular problem.",
    "**Fishbone Diagram (Ishikawa Diagram)**: A visualization tool for categorizing the potential causes of a problem.",
    "**Service Level Agreement (SLA) (The Oaths of Service)**: A commitment between a service provider and a client.",
    "**Service Level Objective (SLO) (The Target Path)**: A specific target for the reliability of a service.",
    "**Service Level Indicator (SLI) (The Measurement of Success)**: A quantitative measure of some aspect of the level of service that is provided.",
    "**Error Budget (The Room for Honorable Failure)**: The amount of allowed unreliability in an SLO.",
    "**Site Reliability Engineering (SRE)**: A discipline that incorporates aspects of software engineering and applies them to infrastructure and operations problems.",
    "**SRE Principles: Embracing Risk, Service Level Objectives, Eliminating Toil, Monitoring, Automation, Release Engineering, Simplicity.**",
    "**Toil (The Grunt Work)**: Tasks that are manual, repetitive, automatable, tactical, devoid of enduring value, and scale linearly with service growth.",
    "**Automating Toil (The Liberation)**: Using automation to replace manual and repetitive tasks.",
    "**Runbook / Playbook (The Guide to Action)**: A collection of procedures and information used by an operator or engineer.",
    "**Executable Runbook**: A runbook where the procedures are automated scripts or commands that can be executed directly.",
    "**Alerting (The Horn of Warning)**: The process of notifying the appropriate people when a problem is detected.",
    "**On-Call Rotation (The Watch Duty)**: A schedule where team members take turns being responsible for responding to production incidents.",
    "**Incident Management System (PagerDuty, Opsgenie)**: Tools for managing and routing alerts to the appropriate on-call person.",
    "**Escalation Policy**: Rules for who to contact if an on-call person does not respond to an alert.",
    "**MTTD (Mean Time to Detect)**: The average time it takes to detect a security incident or system failure.",
    "**MTTR (Mean Time to Respond / Repair)**: The average time it takes to respond to or repair a system after a failure.",
    "**Availability (The Always-On)**: The proportion of time that a system is functional and available.",
    "**Reliability (The Unbreakable Trust)**: The probability that a system will perform its intended function without failure for a specified period.",
    "**Maintainability**: The ease with which a product can be maintained.",
    "**Scalability (Horizontal vs Vertical)**: The ability of a system to handle a growing amount of work or its potential to be enlarged to accommodate that growth.",
    "**Elasticity (Cloud Scaling)**: The degree to which a system is able to adapt to workload changes by provisioning and de-provisioning resources in an autonomic manner, such that at each point in time the available resources match the current demand as closely as possible.",
    "**Single-Tenant vs Multi-Tenant Architecture**: Whether a single instance of software serves one customer or multiple customers.",
    "**Multi-Tenancy Isolation**: Ensuring that one tenant cannot access another tenant's data or affect their performance.",
    "**Noisy Neighbor Problem**: When one tenant in a multi-tenant environment consumes a disproportionate amount of resources, affecting the performance of other tenants.",
    "**Quotas and Throttling (Fair Use Law)**: Limiting the amount of resources that a single user or application can consume.",
    "**Rate Limiting (Token Bucket, Leaky Bucket)**: Controlling the rate of requests sent or received by a network interface or service.",
    "**Circuit Breaker (State Machine: Closed, Open, Half-Open)**: The internal states of a circuit breaker pattern.",
    "**Bulkhead Pattern (The Sealed Compartments)**: Isolating elements of an application into pools so that if one fails, the others will continue to function.",
    "**Sidecar Injection (Automated)**: Automatically adding sidecar containers to pods during deployment (e.g. using a mutating admission webhook).",
    "**Service Mesh Data Plane vs Control Plane**: The components that handle traffic vs the components that manage the mesh.",
    "**Envoy Proxy (The Workhorse of the Mesh)**: An L7 proxy and communication bus designed for large modern service-oriented architectures.",
    "**Mtls (Mutual TLS) in Service Mesh**: Automatically encrypting and authenticating all service-to-service communication.",
    "**Zero Trust in Microservices**: Validating every request between microservices using identities and policies.",
    "**Cloud Native Storage (Rook, Longhorn)**: Storage solutions specifically designed for containerized environments.",
    "**Serverless Database (PlanetScale, CockroachDB Serverless, Aurora Serverless)**: Databases that scale automatically and charge based on usage.",
    "**Cold Storage (Amazon Glacier, Google Coldline)**: Extremely low-cost storage for data that is rarely accessed.",
    "**Edge Computing (The Settlement at the Frontier)**: A distributed computing paradigm that brings computation and data storage closer to the sources of data.",
    "**CDN (Content Delivery Network)**: A geographically distributed network of proxy servers and their data centers.",
    "**Edge Workers (Cloudflare Workers, Fastly Compute)**: Running code at the edge of the network.",
    "**Internet of Things (IoT) (The Whispering World)**: The network of physical objects that are embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the internet.",
    "**MQTT (The Language of the Edge)**: A lightweight, publish-subscribe network protocol that transports messages between devices.",
    "**CoAP (Constrained Application Protocol)**: A specialized web transfer protocol for use with constrained nodes and constrained networks.",
    "**Fog Computing**: An architecture that uses edge devices to carry out a substantial amount of computation, storage, and communication locally and routed over the internet backbone.",
    "**Cyber-Physical Systems (CPS)**: Integrations of computation, networking, and physical processes.",
    "**Digital Twin (The Reflection of the Realm)**: A digital representation of a physical object or system.",
    "**OTA (Over-The-Air) Updates**: The practice of wirelessly updating a device's software.",
    "**Embedded Systems (The Hidden Spirit)**: A computer system—a combination of a computer processor, computer memory, and input/output peripheral devices—that has a dedicated function within a larger mechanical or electronic system.",
    "**RTOS (Real-Time Operating System)**: An operating system intended to serve real-time applications that process data as it comes in, typically without buffer delays.",
    "**Hard vs Soft Real-Time Systems**: Guaranteeing deadlines vs aiming for deadlines.",
    "**Interrupt Latency**: The amount of time that elapses from when an interrupt is generated to when the source of the interrupt is serviced.",
    "**Context Switch (The Shifting Spirit)**: The process of storing the state of a process or thread, so that it can be restored and resume execution at a later point.",
    "**Bare Metal Programming**: Running code directly on the hardware without an operating system.",
    "**Bootloader (The First Summoning)**: A small program that loads the operating system or the main application into memory.",
    "**JTAG (Joint Test Action Group)**: An industry standard for verifying designs and testing printed circuit boards after manufacture.",
    "**GPIO (General-Purpose Input/Output)**: An uncommitted digital signal pin on an integrated circuit or electronic circuit board whose behavior—including whether it is an input or output pin—is controllable by the user at run time.",
    "**I2C (Inter-Integrated Circuit)**: A synchronous, multi-controller/multi-target, packet switched, single-ended, serial communication bus.",
    "**SPI (Serial Peripheral Interface)**: A synchronous serial communication interface specification used for short-distance communication, primarily in embedded systems.",
    "**UART (Universal Asynchronous Receiver-Transmitter)**: A computer hardware device for asynchronous serial communication in which the data format and transmission speeds are configurable.",
    "**Endianness in Networking (Network Byte Order)**: Always big-endian.",
    "**Watchdog Timer (The Loyal Guardian)**: An electronic or software timer that is used to detect and recover from computer malfunctions.",
    "**Hardware Abstraction Layer (HAL)**: A layer of programming that allows a computer operating system to interact with a hardware device at a general or abstract level rather than at a detailed hardware level.",
    "**Low Power Design**: Designing hardware and software to minimize power consumption.",
    "**Sleep Modes (Deep Sleep, Hibernate)**: Low-power states for hardware.",
    "**Interrupt-Driven I/O**: A way of controlling I/O activity whereby a peripheral or terminal that needs to make or receive a data transfer sends a signal.",
    "**Polling (The Constant Questioning)**: Actively sampling the status of an external device by a client program as a synchronous activity.",
    "**Direct Register Access**: Communicating with hardware by writing directly to its control registers.",
    "**Bitwise Operations (OR, AND, XOR, NOT, SHIFT)**: Manipulating individual bits of data.",
    "**Bitmasking**: A process in which a mask is used to perform bitwise operations on a byte or integer.",
    "**Floating Point vs Fixed Point Arithmetic**: Representing real numbers in computer systems.",
    "**IEEE 754**: The standard for floating-point arithmetic.",
    "**Rounding Errors (Precision Loss)**: The difference between the calculated value of a number and its exact mathematical value due to rounding.",
    "**NaN (Not-a-Number)**: A value of the numeric data type representing an undefined or unrepresentable value, especially in floating-point calculations.",
    "**Big-O of Common Data Structures (Array, List, Map, Set, Tree).**",
    "**Amortized Complexity**: The average time per operation over a worst-case sequence of operations.",
    "**Cache-Oblivious Algorithms**: Algorithms designed to take advantage of a CPU cache without having the size of the cache as an explicit parameter.",
    "**Online Algorithms**: An algorithm that can process its input piece by piece in a serial fashion, i.e., in the order that the input is fed to the algorithm, without having the entire input available from the start.",
    "**Streaming Algorithms**: Algorithms for processing data streams in which the input data is presented as a sequence of items and can be examined in only a few passes.",
    "**Approximation Algorithms**: Algorithms used to find approximate solutions to optimization problems (in particular NP-hard problems).",
    "**Ramsey Theory (Combinatorics)**: The study of the conditions under which order must appear.",
    "**Graph Colorability**: A way of coloring the vertices of a graph such that no two adjacent vertices share the same color.",
    "**Hamiltonian Path**: A path in an undirected or directed graph that visits each vertex exactly once.",
    "**Eulerian Path**: A trail in a graph which visits every edge exactly once.",
    "**Network Flow (Max-Flow Min-Cut)**: A classic problem in graph theory and network optimization.",
    "**Bipartite Graphs**: A graph whose vertices can be divided into two disjoint and independent sets.",
    "**Strongly Connected Components (SCCs)**: A sub-graph of a directed graph where every vertex is reachable from every other vertex.",
    "**Topological Sort**: A linear ordering of vertices such that for every directed edge uv, vertex u comes before v in the ordering.",
    "**Critical Path Method (CPM)**: An algorithm for scheduling a set of project activities.",
    "**Instruction Scheduling (Compiler Optimization)**: Reordering instructions to improve performance and avoid stalls.",
    "**Register Allocation (Compiler Optimization)**: Assigning a large number of target program variables onto a small number of CPU registers.",
    "**Dead Code Elimination (Compiler Optimization)**: Removing code that does not affect the program results.",
    "**Common Subexpression Elimination (CSE)**: A compiler optimization that searches for instances of identical expressions and replaces them with a single variable holding the computed value.",
    "**Loop Unrolling (Compiler Optimization)**: A loop transformation technique that attempts to optimize a program's execution speed by reducing or eliminating instructions that control the loop.",
    "**Strength Reduction (Compiler Optimization)**: A compiler optimization where expensive operations are replaced with equivalent but less expensive operations.",
    "**Constant Folding**: The process of simplifying constant expressions at compile time.",
    "**Constant Propagation**: The process of substituting the values of known constants in expressions at compile time.",
    "**Linker (Linking the Runes)**: A computer system program that takes one or more object files generated by a compiler and combines them into a single executable file, library file, or another 'object' file.",
    "**Static Linking (Permanent Bind)**: The process of copying all library modules used in the program into the final executable image.",
    "**Dynamic Linking (Lazy Bind)**: The process of linking libraries to a program at run time.",
    "**Dynamic Link Library (DLL) / Shared Object (SO)**: A file that contains code and data that can be used by multiple programs at the same time.",
    "**Global Offset Table (GOT)**: A section of a computer program's executable used to store pointers to external symbols.",
    "**Procedure Linkage Table (PLT)**: A data structure used to support call to functions in a shared library.",
    "**ASLR-compatible Executables (PIE - Position Independent Executable)**: Executables that can be placed at a random memory address.",
    "**Symbol Table**: A data structure used by a language translator such as a compiler or interpreter, where each identifier (a symbol) in a program's source code is associated with information relating to its declaration or appearance in the source.",
    "**Name Mangling (Name Decoration)**: A technique used to solve various problems caused by the need to resolve unique names for programming entities in many modern programming languages.",
    "**Call Stack (The Chain of Deeds)**: A stack data structure that stores information about the active subroutines of a computer program.",
    "**Stack Frame (Activation Record)**: A component of the call stack that contains the parameters, local variables, and return address for a specific function call.",
    "**Frame Pointer vs Stack Pointer**: Registers used to manage the current stack frame.",
    "**Heap Allocation (malloc/free, new/delete)**: Manually managing the allocation and deallocation of memory.",
    "**Memory Pool (The Pre-Allocated Well)**: A strategy for fast memory allocation where pre-allocated blocks of memory are managed.",
    "**Slab Allocation**: A memory management mechanism intended for the efficient allocation of kernel objects.",
    "**Buddy Memory Allocation**: A memory allocation algorithm that divides memory into partitions to try an satisfy a memory request as suitably as possible.",
    "**Memory Safety (The Shield of Logic)**: The property of a program where it is guaranteed not to have memory errors (e.g. buffer overflows, null pointer dereferences).",
    "**Safe vs Unsafe Code (The Protected vs The Primal)**: Explicitly marking sections of code that bypass safety checks (e.g. in Rust).",
    "**Undefined Behavior (The Realm of Chaos)**: The result of executing code whose behavior is not defined by the language specification.",
    "**Sequence Points (C/C++)**: A point in the program's execution where all previous side effects of the previous expressions shall be complete and no side effects of the following expressions shall have started.",
    "**Strict Aliasing**: A rule that says the compiler can assume that pointers to different types do not point to the same memory location.",
    "**Volatile Keyword (The Unpredictable Rune)**: A qualifier that tells the compiler that the value of a variable can change unexpectedly.",
    "**Atomic Operations (Lock-free Primitives)**: Operations that are guaranteed to be performed as a single unit or not at all.",
    "**Memory Ordering (Relaxed, Acquire, Release, SeqCst)**: Specifying the visibility of memory operations across different threads.",
    "**Read-Modify-Write (RMW) Operations**: Atomic operations that read a value, modify it, and write it back.",
    "**Atomic Variables**: Variables that support atomic operations.",
    "**Spinlock (The Waiting Warrior)**: A lock where the thread simply waits in a loop ('spins') until the lock becomes available.",
    "**Futex (Fast Userspace Mutex)**: A Linux kernel system call for implementing fast synchronization primitives in userspace.",
    "**Barrier (Synchronization)**: A type of synchronization method where a group of threads or processes must all reach a certain point before any can proceed.",
    "**Phaser (Synchronization)**: A more flexible synchronization barrier.",
    "**Read-Copy-Update (RCU)**: A synchronization mechanism that allows multiple readers to access a data structure simultaneously while a writer is updating it.",
    "**Non-Blocking Synchronization**: Synchronization without the use of locks.",
    "**Transactional Memory (Hardware)**: Hardware support for atomic memory transactions.",
    "**Concurrency vs Parallelism (Doing vs Being Done)**: Managing multiple tasks vs executing multiple tasks at once.",
    "**Multithreading (The Multiple Threads of Fate)**: The ability of a central processing unit (CPU) or a single core in a multi-core processor to provide multiple threads of execution concurrently.",
    "**Thread Pool (The Gathering of Warriors)**: A software design pattern for achieving concurrency by maintaining a pool of threads for executing tasks.",
    "**Task-Based Concurrency**: A high-level approach to concurrency where you define tasks and let the runtime manage the threads.",
    "**Work Stealing Scheduler**: A scheduling strategy used in many parallel runtimes where idle threads 'steal' work from the queues of busy threads.",
    "**Fork-Join Framework**: A parallel programming pattern where a task is 'forked' into sub-tasks and their results are 'joined' back together.",
    "**Reactive Streams (Backpressure Standard)**: A standard for asynchronous stream processing with non-blocking backpressure.",
    "**Asynchronous Programming (async/await) (The Non-Blocking Path)**: A programming pattern that allows a program to start a task and move on to other tasks while waiting for the first task to complete.",
    "**Promises & Futures (The Oath of Return)**: Objects representing the eventual result of an asynchronous operation.",
    "**Callback Hell (The Tangled Threads)**: A situation where multiple nested callbacks making code difficult to read and maintain.",
    "**Event Loop (The Eternal Cycle)**: A programming construct that waits for and dispatches events or messages in a program.",
    "**Task Queue vs Microtask Queue (JavaScript)**: Different priorities for asynchronous tasks in the event loop.",
    "**I/O Multiplexing (select, poll, epoll, kqueue)**: Monitoring multiple file descriptors to see if I/O is possible on any of them.",
    "**Non-Blocking I/O**: An I/O operation that returns immediately if it cannot be completed, rather than waiting.",
    "**Asynchronous I/O (AIO)**: An I/O operation that allows the program to continue executing while the I/O is performed in the background.",
    "**Zero-Copy I/O (sendfile)**: A technique for transferring data between two file descriptors (or a file and a socket) without copying it between kernel space and user space.",
    "**Direct I/O**: Accessing disk data without using the operating system's file system cache.",
    "**Buffer Management (The Vessel Handling)**: Efficiently managing memory buffers for I/O operations.",
    "**Ring Buffer (Circular Buffer)**: A data structure that uses a single, fixed-size buffer as if it were connected end-to-end.",
    "**Scatter-Gather I/O (Vectored I/O)**: Reading data from multiple buffers into a single stream, or writing data from a single stream into multiple buffers.",
    "**Socket Programming (Connecting the Realms)**: Programming with network sockets.",
    "**TCP/IP Stack (The Layered Path)**: The conceptual model and set of communications protocols used on the Internet.",
    "**OSI Model (The Seven Realms of Networking)**: A conceptual model that characterizes and standardizes the communication functions of a telecommunication or computing system.",
    "**Physical Layer (Layer 1)**: The physical equipment that makes up the network.",
    "**Data Link Layer (Layer 2)**: Reliable transmission of frames between two nodes on the same network.",
    "**Network Layer (Layer 3)**: Routing and forwarding of data packets between different networks.",
    "**Transport Layer (Layer 4)**: Flow control and error correction of data.",
    "**Session Layer (Layer 5)**: Inter-host communication, managing sessions between applications.",
    "**Presentation Layer (Layer 6)**: Data representation, encryption, and decryption.",
    "**Application Layer (Layer 7)**: The layer we interact with (e.g. HTTP, DNS).",
    "**Internet Protocol (IP) (IPv4 vs IPv6)**: The principal communications protocol in the Internet protocol suite for relaying datagrams across network boundaries.",
    "**Transmission Control Protocol (TCP) (The Reliable Messenger)**: A core protocol of the Internet protocol suite which provides reliable, ordered, and error-checked delivery of a stream of octets between applications.",
    "**User Datagram Protocol (UDP) (The Swift Messenger)**: A core protocol of the Internet protocol suite which provides a simple connectionless communication mechanism.",
    "**ICMP (Internet Control Message Protocol)**: Used by network devices to send error messages and operational information.",
    "**ARP (Address Resolution Protocol)**: A communication protocol used for discovering the link layer address, such as a MAC address, associated with a given internet layer address, typically an IPv4 address.",
    "**DHCP (Dynamic Host Configuration Protocol)**: A network management protocol used on IP networks whereby a DHCP server dynamically assigns an IP address and other network configuration parameters to each device on a network.",
    "**DNS (Domain Name System) (The Name-Mapping Ritual)**: The phonebook of the Internet.",
    "**HTTP (Hypertext Transfer Protocol)**: The foundation of data communication for the World Wide Web.",
    "**REST (Representational State Transfer)**: A software architectural style that was created to guide the design and development of the architecture for the World Wide Web.",
    "**Idempotence in REST (GET, PUT, DELETE are idempotent)**: The property of certain HTTP methods where multiple identical requests should have the same effect as a single request.",
    "**Hateoas (Hypermedia as the Engine of Application State)**: A constraint of the REST application architecture that distinguishes it from other network application architectures.",
    "**API Design Patterns (Singleton, Factory, Observer in API context).**",
    "**Webhook (The Messenger's Return)**: A method of augmenting or altering the behavior of a web page or web application with custom callbacks.",
    "**SOAP (Simple Object Access Protocol)**: A messaging protocol specification for exchanging structured information in the implementation of web services in computer networks.",
    "**WSDL (Web Services Description Language)**: An XML-based interface description language that is used for describing the functionality offered by a web service.",
    "**RSS & Atom (Web Feeds)**: Formats for delivering regularly changing web content.",
    "**Semantic Web (The Data of Divine Understanding)**: An extension of the World Wide Web through standards set by the World Wide Web Consortium (W3C).",
    "**Linked Data**: A method of publishing structured data so that it can be interlinked and become more useful through semantic queries.",
    "**JSON-LD (JSON for Linked Data)**: A method of encoding Linked Data using JSON."
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 2501 - 3200\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+2501}. {entry}\n")
