import os
from pathlib import Path

_KNOWLEDGE_REF = (
    Path(__file__).resolve().parent.parent
    / "viking_girlfriend_skill" / "data" / "knowledge_reference"
)
file_path = _KNOWLEDGE_REF / "SOFTWARE_ENGINEERING.md"

entries = [
    "**MLOps (Machine Learning Operations)**: The practice of automating and simplifying machine learning workflows.",
    "**Data Engineering**: The process of designing and building systems for collecting, storing, and analyzing data at scale.",
    "**Feature Store**: A centralized repository for storing and managing machine learning features.",
    "**Model Registry**: A central hub for managing the lifecycle of machine learning models.",
    "**Model Monitoring (Drift Detection)**: The process of monitoring machine learning models for changes in their performance over time.",
    "**Inference (ML)**: The process of using a trained machine learning model to make predictions on new data.",
    "**Training (ML)**: The process of teaching a machine learning model to recognize patterns in data.",
    "**Hyperparameter Tuning**: The process of optimizing the parameters of a machine learning model that are not learned during training.",
    "**AutoML (Automated Machine Learning)**: The process of automating the end-to-end process of applying machine learning to real-world problems.",
    "**Deep Learning**: A subfield of machine learning based on artificial neural networks with multiple layers.",
    "**Neural Networks**: A computing system inspired by the biological neural networks that constitute animal brains.",
    "**Convolutional Neural Networks (CNNs)**: A type of deep neural network most commonly applied to analyzing visual imagery.",
    "**Recurrent Neural Networks (RNNs)**: A type of artificial neural network where connections between nodes form a directed graph along a temporal sequence.",
    "**Transformers (Machine Learning Architecture)**: A deep learning model that adopts the mechanism of attention, differentially weighting the significance of each part of the input data.",
    "**Attention Mechanism**: A technique that allows a model to focus on specific parts of the input data.",
    "**BERT (Bidirectional Encoder Representations from Transformers)**: A Transformer-based machine learning technique for natural language processing (NLP) pre-training developed by Google.",
    "**GPT (Generative Pre-trained Transformer)**: A type of large language model (LLM) developed by OpenAI.",
    "**Large Language Models (LLMs)**: AI systems trained on massive amounts of text data to understand and generate human-like language.",
    "**Reinforcement Learning (RL)**: A type of machine learning where an agent learns to make decisions by performing actions in an environment to maximize a reward.",
    "**Supervised Learning**: A type of machine learning where the model is trained on labeled data.",
    "**Unsupervised Learning**: A type of machine learning where the model is trained on unlabeled data to find hidden patterns.",
    "**Semi-Supervised Learning**: A type of machine learning that uses a small amount of labeled data and a large amount of unlabeled data.",
    "**Self-Supervised Learning**: A type of machine learning where the model learns from the data itself by creating its own labels.",
    "**Transfer Learning**: A machine learning technique where a model developed for a task is reused as the starting point for a model on a second task.",
    "**Federated Learning**: A machine learning technique that trains an algorithm across multiple decentralized edge devices or servers holding local data samples, without exchanging them.",
    "**Edge AI**: The deployment of AI algorithms directly on edge devices, such as smartphones, IoT devices, and sensors.",
    "**On-device Inference**: Running machine learning models directly on the user's device rather than on a server.",
    "**Quantization (ML Model Compression)**: Reducing the precision of the numbers used to represent the weights and activations of a neural network.",
    "**Pruning (ML Model Compression)**: Removing unnecessary connections or neurons from a neural network to reduce its size and complexity.",
    "**Knowledge Distillation**: A technique where a smaller model (student) is trained to mimic the behavior of a larger, more complex model (teacher).",
    "**Bias in AI**: Systematic and repeatable errors in a computer system that create unfair outcomes.",
    "**Explainable AI (XAI)**: A set of processes and methods that allows human users to comprehend and trust the results and output created by machine learning algorithms.",
    "**Fairness in AI**: The ethical principle of ensuring that AI systems do not discriminate against individuals or groups based on protected characteristics.",
    "**AI Governance**: The framework of rules, practices, and processes used to ensure that AI systems are developed and used responsibly.",
    "**Data Privacy in AI**: The practice of protecting personal data used in machine learning workflows.",
    "**Synthetic Data**: Data that is generated artificially rather than being collected from real-world events.",
    "**Data Labeling (Data Annotation)**: The process of identifying raw data (images, text files, videos, etc.) and adding one or more relevant and informative labels to provide context so that a machine learning model can learn from it.",
    "**Crowdsourcing for Data Labeling**: Using a large number of people to label data.",
    "**Active Learning**: A machine learning technique where the model identifies the most informative data points to be labeled by a human expert.",
    "**Weak Supervision**: Using noisier, higher-level sources of supervision to label data.",
    "**Data Hub & Spoke Architecture**: A centralized model for data management and distribution.",
    "**Data Lakehouse**: A new architectural pattern that combines the best features of data lakes and data warehouses.",
    "**Medallion Architecture (Bronze, Silver, Gold Layers)**: A data design pattern used to logically organize data in a lakehouse.",
    "**Delta Lake**: An open-source storage layer that brings ACID transactions to Apache Spark and big data workloads.",
    "**Apache Spark**: An open-source unified analytics engine for large-scale data processing.",
    "**Apache Flink**: An open-source, unified stream-processing and batch-processing framework.",
    "**Apache Beam**: An open-source unified programming model for defining and executing data processing pipelines.",
    "**Apache Airflow**: An open-source platform to programmatically author, schedule and monitor workflows.",
    "**Prefect**: A modern workflow orchestration tool for data intensive applications.",
    "**Dagster**: A data orchestrator for machine learning, analytics, and ETL.",
    "**Luigi**: A Python package that helps you build complex pipelines of batch jobs.",
    "**Kubeflow**: A machine learning platform for Kubernetes.",
    "**MLflow**: An open-source platform for managing the end-to-end machine learning lifecycle.",
    "**DVC (Data Version Control)**: An open-source version control system for machine learning projects.",
    "**TFX (TensorFlow Extended)**: An end-to-end platform for deploying production ML pipelines.",
    "**PyTorch ecosystem**: A widely used open-source machine learning library based on the Torch library.",
    "**JAX**: A Python library for high-performance numerical computing, especially for machine learning research.",
    "**Scikit-learn**: A free software machine learning library for the Python programming language.",
    "**Pandas**: A software library written for the Python programming language for data manipulation and analysis.",
    "**NumPy**: A library for the Python programming language, adding support for large, multi-dimensional arrays and matrices.",
    "**Matplotlib & Seaborn**: Libraries for data visualization in Python.",
    "**Jupyter Notebooks**: An open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text.",
    "**Streamlit**: An open-source Python library that makes it easy to create and share custom web apps for machine learning and data science.",
    "**Gradio**: An open-source Python library that allows you to quickly create UIs for your machine learning models.",
    "**Weights & Biases (W&B)**: A platform for experiment tracking, dataset versioning, and model management.",
    "**Comet ML**: An experiment tracking platform for machine learning.",
    "**Neptune.ai**: A metadata store for MLOps, used for experiment tracking and model registry.",
    "**Great Expectations**: A Python-based open-source library for automating data testing, documentation, and profiling.",
    "**Dbt (data build tool)**: A command-line tool that enables data analysts and engineers to transform data in their warehouse using SQL.",
    "**Hadoop Distributed File System (HDFS)**: A distributed file system designed to run on commodity hardware.",
    "**MapReduce**: A programming model and an associated implementation for processing and generating big data sets with a parallel, distributed algorithm on a cluster.",
    "**Hive (Apache)**: A data warehouse software project built on top of Apache Hadoop for providing data query and analysis.",
    "**Presto & Trino**: Highly performant distributed SQL query engines for big data.",
    "**Apache Druid**: A real-time analytics database designed for fast slice-and-dice analytics on large data sets.",
    "**Apache Pinot**: A real-time distributed OLAP datastore.",
    "**ClickHouse**: An open-source column-oriented DBMS for online analytical processing.",
    "**Vector Databases (Pinecone, Milvus, Weaviate)**: Databases optimized for storing and searching high-dimensional vectors (embeddings).",
    "**Embeddings**: A way to represent words, images, or other data as vectors in a high-dimensional space.",
    "**Vector Search (Nearest Neighbor Search)**: The process of finding the vectors in a database that are most similar to a given query vector.",
    "**Cosine Similarity**: A measure of similarity between two non-zero vectors of an inner product space.",
    "**Euclidean Distance**: The ordinary straight-line distance between two points in Euclidean space.",
    "**Approximate Nearest Neighbors (ANN)**: Algorithms that find nearly-optimal nearest neighbors much faster than exact search.",
    "**HNSW (Hierarchical Navigable Small World)**: A popular graph-based algorithm for approximate nearest neighbor search.",
    "**Product Quantization (PQ)**: A quantization technique used for efficient vector search.",
    "**Locality Sensitive Hashing (LSH)**: An algorithmic technique that hashes similar input items into the same 'buckets' with high probability.",
    "**RAG (Retrieval-Augmented Generation)**: A technique that provides large language models with access to external knowledge to improve their performance and reduce hallucinations.",
    "**Context Injection**: The process of providing more information to an LLM in the prompt to improve its response.",
    "**Prompt Engineering**: The process of designing and refining prompts to elicit specific and high-quality responses from LLMs.",
    "**Few-Shot Prompting**: Providing a few examples of the desired output in the prompt.",
    "**Zero-Shot Prompting**: Asking the LLM to perform a task without providing any examples.",
    "**Chain-of-Thought Prompting**: Encouraging the LLM to explain its reasoning step-by-step.",
    "**Self-Consistency (LLM Prompting)**: Asking the LLM the same question multiple times and choosing the most frequent answer.",
    "**Tree of Thoughts (LLM Prompting)**: A framework for LLM reasoning that allows the model to explore multiple paths of thought.",
    "**Hallucination (LLM)**: A phenomenon where an LLM generates text that is factually incorrect or nonsensical but appears plausible.",
    "**Temperature (LLM Parameter)**: A parameter that controls the randomness of an LLM's output.",
    "**Top-k & Top-p (LLM Parameters)**: Parameters that control the diversity of an LLM's output by sampling from a subset of the most likely tokens.",
    "**Context Window**: The maximum amount of text an LLM can process at once.",
    "**Tokenization (NLP)**: The process of breaking down text into smaller units (tokens).",
    "**BPE (Byte Pair Encoding)**: A subword tokenization algorithm widely used in LLMs.",
    "**SentencePiece**: An open-source subword tokenizer and detokenizer mainly for Neural Network-based text generation systems.",
    "**Word2Vec**: A group of related models that are used to produce word embeddings.",
    "**GloVe (Global Vectors for Word Representation)**: An unsupervised learning algorithm for obtaining vector representations for words.",
    "**FastText**: A library for efficient learning of word representations and sentence classification.",
    "**NLTK (Natural Language Toolkit)**: A leading platform for building Python programs to work with human language data.",
    "**Spacy**: A free, open-source library for advanced Natural Language Processing in Python.",
    "**Hugging Face Transformers**: A library that provides state-of-the-art machine learning models for natural language processing, computer vision, and more.",
    "**Model Hub (Hugging Face)**: A central repository for sharing and discovering machine learning models.",
    "**Dataset Hub (Hugging Face)**: A central repository for sharing and discovering datasets for machine learning.",
    "**Spaces (Hugging Face)**: A platform for hosting and sharing machine learning demos.",
    "**LoRA (Low-Rank Adaptation)**: A technique for fine-tuning large language models efficiently by adding small, trainable matrices.",
    "**QLoRA**: A quantized version of LoRA that allows for even more efficient fine-tuning.",
    "**PEFT (Parameter-Efficient Fine-Tuning)**: A collection of techniques for fine-tuning large models with a small number of parameters.",
    "**Instruction Fine-Tuning**: Fine-tuning an LLM on a dataset of instructions and their corresponding outputs.",
    "**RLHF (Reinforcement Learning from Human Feedback)**: A technique for aligning LLMs with human preferences by using human feedback to train a reward model.",
    "**PPO (Proximal Policy Optimization)**: A reinforcement learning algorithm used in RLHF.",
    "**DPO (Direct Preference Optimization)**: An alternative to RLHF that directly optimizes the model based on human preferences without using a separate reward model.",
    "**Prompt Tuning**: A technique for fine-tuning LLMs by learning a small set of continuous 'soft' prompts.",
    "**Prefix Tuning**: A technique for fine-tuning LLMs by prepending a series of continuous vectors to the input.",
    "**Adapter-based Fine-Tuning**: Adding small 'adapter' layers to an LLM and only training those layers during fine-tuning.",
    "**Model Merging (Ensembling)**: Combining multiple machine learning models to improve overall performance.",
    "**Model Sharding (Parallelism)**: Splitting a large machine learning model across multiple GPUs or servers.",
    "**Data Parallelism (Distributed Training)**: Splitting the training data across multiple GPUs or servers and training the same model on each subset.",
    "**Pipeline Parallelism (Distributed Training)**: Splitting the layers of a neural network across multiple GPUs or servers.",
    "**Tensor Parallelism (Distributed Training)**: Splitting individual tensors across multiple GPUs or servers.",
    "**ZeRO (Zero Redundancy Optimizer)**: A memory optimization technique for large-scale distributed training of deep learning models.",
    "**DeepSpeed**: A deep learning optimization library that makes distributed training efficient and easy.",
    "**Horovod**: A distributed deep learning training framework for TensorFlow, Keras, PyTorch, and Apache MXNet.",
    "**Ray (Framework)**: An open-source unified framework for scaling AI and Python applications.",
    "**Ray Train & Ray Serve**: Components of the Ray framework for distributed training and model serving.",
    "**BentoML**: A framework for building high-performance, scalable machine learning model serving systems.",
    "**Seldon Core**: An open-source platform for deploying machine learning models on Kubernetes.",
    "**Triton Inference Server**: An open-source inference serving software that streamlines AI inferencing.",
    "**TorchServe**: A flexible and easy-to-use tool for serving PyTorch models in production.",
    "**TF Serving**: A flexible, high-performance serving system for machine learning models, designed for production environments.",
    "**ONNX (Open Neural Network Exchange)**: An open standard for representing machine learning models.",
    "**Core ML**: Apple's framework for integrating machine learning models into your apps.",
    "**TensorFlow Lite**: An open-source deep learning framework for on-device inference.",
    "**TVM (Apache)**: An open-source machine learning compiler stack for CPUs, GPUs and specialized accelerators.",
    "**OpenVINO**: An open-source toolkit for optimizing and deploying AI inference.",
    "**XLA (Accelerated Linear Algebra)**: A domain-specific compiler for linear algebra that can accelerate TensorFlow models.",
    "**MLIR (Multi-Level Intermediate Representation)**: A project to build a unified compiler infrastructure for machine learning.",
    "**TVM v0.10+ (Apache)**: Advanced compiler for ML model deployment.",
    "**Graph Neural Networks (GNNs)**: A type of neural network that can operate on graph structures.",
    "**Geometric Deep Learning**: A subfield of deep learning that generalizes neural network architectures to non-Euclidean domains like graphs and manifolds.",
    "**Graph Embeddings**: Techniques for representing graph nodes, edges, or the entire graph as vectors.",
    "**Node2Vec**: An algorithmic framework for learning continuous feature representations for nodes in networks.",
    "**DeepWalk**: An approach for learning latent representations of vertices in a network.",
    "**GCN (Graph Convolutional Network)**: A type of GNN that uses convolution-like operations on graph data.",
    "**GAT (Graph Attention Network)**: A type of GNN that uses attention mechanisms to weight the contributions of neighboring nodes.",
    "**Message Passing Neural Networks (MPNNs)**: A general framework for describing GNNs.",
    "**Temporal Graph Networks (TGNs)**: GNNs that can model dynamic graphs that change over time.",
    "**Inductive Learning on Graphs**: Learning a model that can generalize to new nodes that were not seen during training.",
    "**Transductive Learning on Graphs**: Learning a model that specifically targets nodes in a fixed graph.",
    "**Link Prediction (Graph Analysis)**: The task of predicting whether two nodes in a graph should be connected.",
    "**Node Classification (Graph Analysis)**: The task of assigning a label to each node in a graph.",
    "**Graph Classification (Graph Analysis)**: The task of assigning a label to an entire graph.",
    "**Community Detection (Graph Analysis)**: Finding groups of nodes in a graph that are more densely connected to each other than to the rest of the network.",
    "**Centrality Measures (Degree, Closeness, Betweenness, PageRank)**: Metrics for assessing the importance of nodes in a graph.",
    "**PageRank Algorithm**: The original algorithm used by Google Search to rank web pages in their search engine results.",
    "**Network Analysis Tools (NetworkX, Gephi)**: Libraries and tools for working with and visualizing graph data.",
    "**Knowledge Graphs**: A semantic network that represents knowledge about the real world in a machine-readable format.",
    "**Ontologies (Knowledge Representation)**: A formal representation of a set of concepts within a domain and the relationships between those concepts.",
    "**RDF (Resource Description Framework)**: A standard model for data interchange on the Web.",
    "**SPARQL**: A query language for RDF data.",
    "**OWL (Web Ontology Language)**: A semantic web language designed to represent rich and complex knowledge about things and the relationships between them.",
    "**Property Graphs**: A type of graph database model where nodes and edges can have properties.",
    "**Neo4j**: A popular graph database management system.",
    "**AWS Neptune**: A fully managed graph database service by Amazon.",
    "**OrientDB**: An open source NoSQL multi-model database that includes features of both graph and document databases.",
    "**ArangoDB**: An open-source, multi-model database system with a flexible data model for documents, graphs, and key-values.",
    "**TigerGraph**: A platform for graph analytics and graph databases.",
    "**Graph Theory Foundations (Vertices, Edges, Adjacency Matrix)**: The mathematical basis for graph analysis.",
    "**Seven Bridges of Königsberg**: A historically notable problem in mathematics and the foundation of graph theory.",
    "**Travelling Salesman Problem (TSP)**: A classic optimization problem that asks for the shortest possible route that visits each city exactly once and returns to the origin city.",
    "**Knapsack Problem**: A problem in combinatorial optimization: given a set of items, each with a weight and a value, determine the number of each item to include in a collection so that the total weight is less than or equal to a given limit and the total value is as large as possible.",
    "**P vs NP Problem**: A major unsolved problem in theoretical computer science.",
    "**NP-Complete Problems**: A class of problems for which no known efficient algorithm exists, but a solution can be verified quickly.",
    "**Complexity Classes (P, NP, PSPACE, EXPTIME)**: A way of classifying computational problems according to their inherent difficulty.",
    "**Algorithm Design Techniques (Dynamic Programming, Greedy, Divide & Conquer)**: Fundamental strategies for developing efficient algorithms.",
    "**Sorting Algorithms (QuickSort, MergeSort, HeapSort, BubbleSort)**: Algorithms for arranging elements in a specific order.",
    "**Search Algorithms (Binary Search, Depth-First Search, Breadth-First Search)**: Algorithms for finding specific elements or paths in data structures.",
    "**Time and Space Complexity Analysis (Big O, Big Omega, Big Theta)**: Formally evaluating the efficiency of algorithms.",
    "**Hash Functions & Collision Resolution (Chaining, Open Addressing)**: Core concepts of hash tables.",
    "**Binary Heaps & Priority Queues**: Efficient data structures for maintaining the 'best' element.",
    "**Disjoint Set Union (DSU) / Union-Find**: A data structure that keeps track of a set of elements partitioned into several disjoint sets.",
    "**Tries & Suffix Trees**: Specialized tree structures for string processing.",
    "**Segment Trees & Fenwick Trees (Binary Indexed Trees)**: Data structures for efficient range queries and updates.",
    "**Red-Black Trees & AVL Trees**: Self-balancing binary search trees that guarantee logarithmic time for operations.",
    "**B-Trees & B+ Trees**: Tree structures optimized for systems that read and write large blocks of data, commonly used in databases.",
    "**LSM (Log-Structured Merge-Tree)**: A data structure used by many NoSQL databases to handle high write volumes.",
    "**B-Tree vs LSM-Tree (Trade-offs)**: Comparing read-heavy vs write-heavy data structure performance.",
    "**Index Selection & Optimization**: Choosing the right database indexes to improve query performance.",
    "**Composite Indexes**: Indexes that include multiple columns.",
    "**Clustered vs Non-Clustered Indexes**: How data is physically stored vs how pointers are maintained.",
    "**Full-Text Search Indices (Inverted Indexes)**: The foundation of search engines like Elasticsearch.",
    "**Database Denormalization**: Intentionally adding redundant data to a database to improve read performance.",
    "**Database Partitioning (Sharding)**: Breaking a large database into smaller, more manageable pieces.",
    "**Database Federation**: A virtual database system that provides a single interface to multiple distinct databases.",
    "**Database Mirroring & Replication (Master-Slave, Master-Master)**: Techniques for ensuring high availability and data durability.",
    "**Transaction Logs (Write-Ahead Logging)**: A family of techniques for providing atomicity and durability in database systems.",
    "**Two-Phase Commit (2PC)**: A type of atomic commitment protocol used in distributed systems.",
    "**Three-Phase Commit (3PC)**: A more complex version of 2PC that attempts to avoid blocking under certain failure conditions.",
    "**Paxos & Raft (Distributed Consensus)**: Protocols for reaching agreement in a network of unreliable nodes.",
    "**Vectorization (Database Query Processing)**: Executing operations on batches of data instead of single rows.",
    "**Columnar Storage vs Row Storage (Pros/Cons)**: Comparing analytics-heavy vs OLTP-heavy storage formats.",
    "**Parquet & ORC (Columnar File Formats)**: Optimized file formats for big data analytics.",
    "**Avro (Row-based Serialization)**: A remote procedure call and data serialization framework.",
    "**Protocol Buffers (Protobuf)**: A language-neutral, platform-neutral extensible mechanism for serializing structured data.",
    "**MessagePack (Msgpack)**: A binary-based efficient object serialization format.",
    "**CBOR (Concise Binary Object Representation)**: A binary data serialization format loosely based on JSON.",
    "**JSON vs XML vs YAML (Data Interchange Formats)**: Comparing human-readability and machine-efficiency.",
    "**Data Compression Algorithms (Gzip, Snappy, LZ4, Zstandard)**: Techniques for reducing data size.",
    "**Lossless vs Lossy Compression**: Whether data can be perfectly reconstructed or not.",
    "**Entropy Coding (Huffman, Arithmetic Coding)**: A form of lossless data compression.",
    "**Run-Length Encoding (RLE)**: A simple form of data compression where runs of data are stored as a single data value and count.",
    "**Lempel-Ziv (LZ77, LZ78) Algorithms**: A family of lossless data compression algorithms.",
    "**Burrows-Wheeler Transform (BWT)**: An algorithm used in data compression (like bzip2).",
    "**Bloom Filter (False Positive Rate)**: Handling the trade-off between space efficiency and accuracy.",
    "**Cuckoo Filter**: A space-efficient probabilistic data structure that supports deletion unlike Bloom filters.",
    "**HyperLogLog (HLL)**: An algorithm for the count-distinct problem, approximating the number of distinct elements in a multiset.",
    "**Count-Min Sketch**: A probabilistic data structure that serves as a frequency table of events in a stream of data.",
    "**Reservoir Sampling**: A family of randomized algorithms for choosing a sample of n items from a list S containing n items, where n is a very large or unknown number.",
    "**T-Digest**: An algorithm for computing quantiles and other rank-based statistics on large datasets or data streams.",
    "**Consistent Hashing**: A hashing technique such that when a hash table is resized, only K/n keys need to be remapped on average.",
    "**Rendezvous Hashing (Highest Random Weight Hashing)**: An algorithm that allows clients to achieve a consistent distributed hash table.",
    "**Consistent Hashing with Virtual Nodes (Vnodes)**: Improving the distribution of keys in a consistent hash ring.",
    "**Load Balancing Algorithms (Round Robin, Least Connections, IP Hash)**: Strategies for distributing traffic across servers.",
    "**Sticky Sessions (Session Affinity)**: Ensuring that all requests from a single user are routed to the same server.",
    "**Side-Channel Attack Mitigation (Constant-Time Algorithms)**: Reducing the risk of information leakage via timing or power analysis.",
    "**Defense in Depth**: A security strategy that uses multiple layers of security for comprehensive protection.",
    "**Principle of Fail-Safe Defaults**: Designing systems so that if they fail, they fail into a secure state.",
    "**Economy of Mechanism**: Keeping security mechanisms as simple and small as possible.",
    "**Complete Mediation**: Checking every access to every object for authorization.",
    "**Psychological Acceptability**: Ensuring that security mechanisms are easy for users to follow correctly.",
    "**Privacy-Preserving Contact Tracing (GAEN)**: The protocol developed by Google and Apple during the COVID-19 pandemic.",
    "**K-Anonymity (Privacy Model)**: A simple model for anonymizing data.",
    "**Differential Privacy (Global vs Local)**: Ensuring that the inclusion of any single individual in a dataset does not significantly change the outcome of an analysis.",
    "**Privacy Budget (Alpha, Epsilon)**: Managing the total amount of privacy loss across multiple queries in differential privacy.",
    "**Adversarial Examples in AI**: Inputs to machine learning models that an attacker has intentionally designed to cause the model to make a mistake.",
    "**Evasion Attacks (ML Security)**: Attacks that happen at inference time.",
    "**Poisoning Attacks (ML Security)**: Attacks that happen at training time.",
    "**Model Inversion (ML Security)**: Reconstructing sensitive training data from model outputs.",
    "**Model Extraction (Stealing)**: Replicating a proprietary machine learning model by querying its API.",
    "**Fairness Metrics (Statistical Parity, Equal Opportunity)**: Quantifying the fairness of machine learning models.",
    "**Uncertainty Quantification in ML**: Estimating the confidence of a model's predictions.",
    "**Bayesian Neural Networks**: A type of neural network that uses Bayesian inference to estimate uncertainty.",
    "**Active Learning (ML Iteration)**: Using the model to pick the best data points for labeling.",
    "**Transfer Learning (Domain Adaptation)**: Adapting a model from one domain to another.",
    "**Zero-Shot Learning (Knowledge Transfer)**: A model's ability to recognize or classify new data without any prior training on that specific class.",
    "**One-Shot Learning**: A machine learning task where the objective is to learn about something from just one example.",
    "**Curriculum Learning**: Training a machine learning model by starting with easy examples and gradually increasing the difficulty.",
    "**Ensemble Learning (Bagging, Boosting, Stacking)**: Combining multiple models to get better performance than any single model.",
    "**Random Forest (Bagging)**: An ensemble learning method for classification, regression and other tasks that operates by constructing a multitude of decision trees at training time.",
    "**XGBoost (Gradient Boosting)**: An open-source software library which provides a regularized gradient boosting framework.",
    "**LightGBM**: A fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework based on decision tree algorithms.",
    "**CatBoost**: An open-source gradient boosting on decision trees library.",
    "**AdaBoost (Adaptive Boosting)**: A machine learning meta-algorithm which can be used in conjunction with many other types of learning algorithms to improve performance.",
    "**Gradient Descent (Stochastic, Mini-batch)**: The primary optimization algorithm for training neural networks.",
    "**Backpropagation**: The central algorithm for computing the gradients of a loss function with respect to the weights in a neural network.",
    "**Vanishing Gradient Problem**: A difficulty in training certain types of neural networks where gradients become very small, preventing weights from changing.",
    "**Exploding Gradient Problem**: A difficulty in training certain types of neural networks where gradients become very large, causing unstable updates.",
    "**Activation Functions (ReLU, Sigmoid, Tanh, Softmax)**: Non-linear functions applied to the output of a neuron.",
    "**Loss Functions (MSE, Cross-Entropy, Hinge Loss)**: Functions that measure the difference between the predicted and actual values.",
    "**Regularization (L1, L2, Dropout)**: Techniques for preventing overfitting in machine learning models.",
    "**Overfitting vs Underfitting**: Common problems in machine learning where the model is either too complex or too simple.",
    "**Train-Test Split & Cross-Validation**: Techniques for evaluating the generalization performance of a machine learning model.",
    "**K-Fold Cross-Validation**: A robust technique for model evaluation that involves splitting the data into k subsets.",
    "**Grid Search vs Random Search (Hyperparameter Tuning)**: Different strategies for exploring the space of hyperparameters.",
    "**Bayesian Optimization**: A more efficient strategy for hyperparameter tuning using a probabilistic model.",
    "**Evolutionary Algorithms (Genetic Algorithms)**: Search and optimization techniques inspired by biological evolution.",
    "**Fuzzy Logic**: A form of many-valued logic in which the truth values of variables may be any real number between 0 and 1.",
    "**Heuristic Analysis**: A method of solving problems by taking an experimental approach or using a set of rules of thumb.",
    "**Meta-Heuristics (Simulated Annealing, Particle Swarm Optimization)**: Higher-level procedures used to find or select a heuristic that may provide a sufficiently good solution to an optimization problem.",
    "**Simulated Annealing**: A probabilistic technique for approximating the global optimum of a given function.",
    "**Ant Colony Optimization**: A population-based metaheuristic that can be used to find approximate solutions to difficult optimization problems.",
    "**Genetic Programming**: A technique in which computer programs are encoded as a set of genes that are then modified (evolved) over time.",
    "**Expert Systems**: A computer system that emulates the decision-making ability of a human expert.",
    "**Symbolic AI**: The branch of AI that represents knowledge using symbols and rules.",
    "**Knowledge Representation and Reasoning (KRR)**: The field of AI dedicated to representing information about the world in a form that a computer system can utilize to solve complex tasks.",
    "**Inference Engine**: A component of the system that applies logical rules to the knowledge base to deduce new information.",
    "**Forward Chaining**: An inference strategy that starts with known facts and applies rules to reach new conclusions.",
    "**Backward Chaining**: An inference strategy that starts with a goal and works backward to see if the known facts support it.",
    "**Conflict Resolution (Expert Systems)**: The process of choosing which rule to apply when multiple rules match the current facts.",
    "**Blackboard System**: A common-interest platform for solving problems where different 'specialists' contribute their knowledge.",
    "**Agent-Based Modeling (ABM)**: A type of computational model for simulating the actions and interactions of autonomous agents.",
    "**Multi-Agent Systems (MAS)**: A computerized system composed of multiple interacting intelligent agents.",
    "**Game Theory (Nash Equilibrium)**: The study of mathematical models of strategic interaction among rational decision-makers.",
    "**Prisoner's Dilemma**: A standard example of a game analyzed in game theory that shows why two completely rational individuals might not cooperate, even if it appears that it is in their best interests to do so.",
    "**Zero-Sum Game**: A mathematical representation of a situation in which each participant's gain or loss of utility is exactly balanced by the losses or gains of the utility of the other participants.",
    "**Minimax Algorithm (AI in Games)**: A decision rule used in artificial intelligence, decision theory, game theory, statistics, and philosophy for minimizing the possible loss for a worst case scenario.",
    "**Alpha-Beta Pruning (Minimax Enhancement)**: A search algorithm that seeks to decrease the number of nodes that are evaluated by the minimax algorithm in its search tree.",
    "**Monte Carlo Tree Search (MCTS)**: A heuristic search algorithm for some kinds of decision processes, most notably employed in software that plays board games.",
    "**AlphaGo Zero**: A version of DeepMind's Go-playing AI that learned to play entirely by playing against itself.",
    "**MuZero**: A successor to AlphaZero that can master games without knowing their rules.",
    "**Artificial General Intelligence (AGI)**: The hypothetical ability of an intelligent agent to understand or learn any intellectual task that a human being can.",
    "**Artificial Superintelligence (ASI)**: An agent that possesses intelligence far surpassing that of the brightest and most gifted human minds.",
    "**Turing Test**: A test of a machine's ability to exhibit intelligent behavior equivalent to, or indistinguishable from, that of a human.",
    "**The Chinese Room (Philosophical thought experiment)**: A challenges to the claim that a computer can have a mind and understanding.",
    "**Singularity (Technological)**: A hypothetical point in time at which technological growth becomes uncontrollable and irreversible, resulting in unfathomable changes to human civilization.",
    "**AI Alignment (Outer vs Inner)**: Ensuring that the AI's specified goal matches our true intent and that the AI's actual behavior matches its specified goal.",
    "**Reward Hacking (AI Safety)**: When an AI finds a way to get a high reward without actually achieving the desired goal.",
    "**Goal Misgeneralization (AI Safety)**: When an AI's goal changes when it is moved from its training environment to a new environment.",
    "**Instrumental Convergence**: The idea that an intelligent agent with a wide range of goals will likely pursue certain 'instrumental' goals, such as survival and resource acquisition.",
    "**Power-Seeking Behavior in AI**: The tendency of some AI systems to seek control over their environment to ensure they can achieve their goals.",
    "**AI Boxing**: A hypothetical way of keeping a superintelligent AI contained.",
    "**Oracle AI**: An AI that is only allowed to answer questions and not take actions in the world.",
    "**Formal Methods for AI Safety**: Using mathematical proofs to ensure the safety of AI systems.",
    "**Constitutional AI**: A method for training AI systems using a set of principles or 'constitution' to guide their behavior.",
    "**Open Source AI (Controversial definitions)**: The debate over what it means for an AI model to be open source.",
    "**Llama (Meta AI)**: A family of large language models released by Meta.",
    "**Mistral & Mixtral (Mistral AI)**: High-performance open-weight models from the French company Mistral AI.",
    "**Falcon (TII)**: An open-source large language model developed by the Technology Innovation Institute in Abu Dhabi.",
    "**LLM Ecosystem (LangChain, LlamaIndex, Haystack)**: Frameworks for building LLM-powered applications.",
    "**Chains (LangChain)**: Combining multiple LLM calls or other tools into a sequence.",
    "**Agents (LangChain)**: LLMs that can use tools and make decisions about which actions to take.",
    "**Memory (LangChain)**: Managing the history of interactions between an LLM and a user.",
    "**Retrieval (LlamaIndex)**: Indexing and retrieving local data for use with LLMs.",
    "**Guardrails (Nemo Guardrails)**: Tools for ensuring that LLM-powered applications behave safely and predictably.",
    "**Semantic Router**: A lightweight layer that uses embeddings to route queries to different prompts or tools.",
    "**LLM-as-a-Judge**: Using a large language model to evaluate the performance of another model.",
    "**MT-Bench**: A benchmark for evaluating the multi-turn conversation and instruction-following abilities of LLMs.",
    "**MMLU (Massive Multitask Language Understanding)**: A benchmark designed to measure the knowledge acquired during pretraining by evaluating models on a set of 57 subjects.",
    "**HumanEval**: A benchmark for evaluating the code generation abilities of LLMs.",
    "**LMSYS Chatbot Arena**: A benchmark platform for LLMs based on crowdsourced human evaluation.",
    "**Contextual Integrity (Privacy)**: A theory of privacy that focuses on the 'appropriateness' of information flow within a specific context.",
    "**Nissenbaum's Privacy as Contextual Integrity**: The seminal work on this theory.",
    "**Privacy-Preserving Data Mining (PPDM)**: Techniques for extracting useful information from data without compromising the privacy of individuals.",
    "**Secure Outsourcing of Computation**: Allowing a third party to perform computations on your data without them being able to see the data or the results.",
    "**Private Set Intersection (PSI)**: A cryptographic technique that allows two parties to find the intersection of their sets without revealing anything else about their sets.",
    "**Opaque Metadata**: Encryption that hides even the length and structure of sensitive data.",
    "**Network Anonymity (Onion Routing, Garlic Routing)**: Hiding the source and destination of network traffic.",
    "**Ipredator (VPN)**: A defunct VPN service focused on privacy and censorship resistance.",
    "**Mullvad VPN**: A privacy-focused VPN service that allows anonymous accounts with no personal information.",
    "**IVPN**: Another privacy-focused VPN service with a strong transparency record.",
    "**ProtonMail & ProtonVPN**: A suite of privacy-focused online services.",
    "**Tutanota**: An end-to-end encrypted email service.",
    "**DuckDuckGo**: A search engine that emphasizes protecting searchers' privacy and avoiding the filter bubble of personalized search results.",
    "**Brave Browser**: A privacy-focused web browser that blocks ads and trackers by default.",
    "**LibreWolf**: A community-driven, privacy-focused fork of Firefox.",
    "**GrapheneOS**: An Android-based operating system for smartphones with a heavy focus on privacy and security.",
    "**CalyxOS**: Another security-focused Android ROM.",
    "**LineageOS**: A free and open-source operating system for various devices, based on the Android mobile platform.",
    "**Tails (OS)**: A security-focused Debian-based Linux distribution aimed at preserving privacy and anonymity.",
    "**Qubes OS**: A security-oriented operating system that aims to provide security through isolation.",
    "**Whonix**: A Debian-based desktop operating system designed for advanced security and privacy.",
    "**Privacy-Focused Social Networks (PixelFed, Lemmy, Pleroma)**: Decentralized alternatives to mainstream social media.",
    "**Fediverse**: A collection of federated social networking services.",
    "**Personal Data Vaults (Solid Project)**: Tim Berners-Lee's project to give people control over their own data.",
    "**Data Sovereignty for Indigenous Peoples**: The right of Indigenous peoples to govern the collection, ownership, and application of data about them.",
    "**Information Stewardship**: The ethical responsibility for the management of information assets.",
    "**Data Altruism**: Making data available for the common good.",
    "**Data Intermediaries (Data Trusts, Data Cooperatives)**: Entities that facilitate the sharing of data while protecting the interests of the data subjects.",
    "**Algorithm Auditing**: The process of examining an algorithm for bias, errors, and other issues.",
    "**Impact Assessment for Algorithms**: Evaluating the potential societal impacts of an algorithm before it is deployed.",
    "**Right to Explanation (GDPR)**: The right of a data subject to receive an explanation for a decision made by an automated system.",
    "**Adversarial Robustness in ML**: The ability of a machine learning model to resist adversarial attacks.",
    "**Robustness Benchmarks for AI**: Datasets and tasks designed to test the limits of AI systems.",
    "**OOD (Out-of-Distribution) Detection**: Identifying when the input data to a model is significantly different from the data it was trained on.",
    "**Concept Drift vs Data Drift**: Changes in the relationship between input and output vs changes in the input distribution.",
    "**Online Learning (Incremental Learning)**: Updating a model as new data arrives without retraining from scratch.",
    "**Catastrophic Forgetting**: A phenomenon where a neural network forgets previously learned information when it is trained on new data.",
    "**Elastic Weight Consolidation (EWC)**: A technique for mitigating catastrophic forgetting.",
    "**Replay-based Continual Learning**: Storing and re-training on a subset of old data to prevent forgetting.",
    "**Meta-Learning (Learning to Learn)**: Developing algorithms that can learn new tasks quickly with minimal data.",
    "**MAML (Model-Agnostic Meta-Learning)**: A popular meta-learning algorithm.",
    "**Few-Shot Image Classification**: Recognizing new image categories from only a few examples.",
    "**Model Architecture Search (NAS)**: Using machine learning to design the architecture of neural networks.",
    "**Neural Architecture Search with Reinforcement Learning**: Using RL to explore the space of possible architectures.",
    "**Evolutionary NAS**: Using genetic algorithms for neural architecture search.",
    "**EfficientNet**: A family of convolutional neural networks that achieve state-of-the-art accuracy with much fewer parameters and FLOPs.",
    "**Vision Transformers (ViT)**: Applying Transformer models to computer vision tasks.",
    "**Swin Transformer**: A hierarchical Vision Transformer using shifted windows.",
    "**MAEs (Masked Autoencoders)**: A self-supervised learning technique for computer vision.",
    "**CLIP (Contrastive Language-Image Pre-training)**: A model that learns to connect images and text.",
    "**DALL-E 2 & 3 (OpenAI)**: Generative AI models that create images from text descriptions.",
    "**Stable Diffusion (Stability AI)**: A latent text-to-image diffusion model capable of generating photo-realistic images from any text input.",
    "**Midjourney**: A generative AI program and service that generates images from natural language descriptions.",
    "**Generative AI for Video (Runway, Pika, Sora)**: New models that can generate or edit video from text.",
    "**Diffusion Models**: A class of generative models that learn to reverse a process of adding noise to data.",
    "**GANs (Generative Adversarial Networks)**: A class of machine learning frameworks designed by Ian Goodfellow where two neural networks contest with each other in a game.",
    "**VAEs (Variational Autoencoders)**: A type of generative model that learns a probabilistic representation of data.",
    "**Autoregressive Models**: Generative models that generate data one step at a time, conditioned on previous steps.",
    "**Flow-based Generative Models**: Generative models that use invertible transformations to map data to a simple latent distribution.",
    "**Energy-Based Models (EBMs)**: A class of models that associate a scalar energy with each configuration of variables.",
    "**Score-based Generative Models**: A class of models that learn the score function (gradient of the log-density) of the data distribution.",
    "**Consistency Models (Generative AI)**: A new class of generative models that can generate high-quality samples in a single step.",
    "**Sampling Methods (Ancestral, DDIM, DPM-Solver)**: Techniques for generating samples from generative models.",
    "**Latent Space Navigation**: Exploring the representational space of a generative model to find specific outputs or interpolate between them.",
    "**Style Transfer (Neural Style Transfer)**: Applying the style of one image to the content of another.",
    "**Super-Resolution (AI-based)**: Using machine learning to increase the resolution of images or videos.",
    "**Inpainting & Outpainting (AI-based)**: Filling in missing parts of an image or extending it beyond its borders.",
    "**Deepfake (Creation and Detection)**: Synthetic media in which a person in an existing image or video is replaced with someone else's likeness.",
    "**AI for Music Generation (Suno, Udio, Magenta)**: Models that can compose and perform music.",
    "**Jukebox (OpenAI)**: A neural network that generates music, including rudimentary singing, as raw audio in a variety of genres and artist styles.",
    "**AudioLDM**: A text-to-audio system that generates audio samples given a text description.",
    "**Whisper (OpenAI)**: An automatic speech recognition (ASR) system trained on 680,000 hours of multilingual and multitask supervised data collected from the web.",
    "**TTS (Text-to-Speech) - Bark, Tortoise, ElevenLabs**: High-quality AI-based voice synthesis systems.",
    "**Voice Cloning**: Creating a digital replica of a specific person's voice.",
    "**Emotion in TTS**: Systems that can generate speech with specific emotional tones.",
    "**Multimodal AI**: AI systems that can process and understand multiple types of input (e.g. text, images, audio).",
    "**GPT-4V & Gemini 1.5 Pro**: Large multimodal models from OpenAI and Google.",
    "**Visual Question Answering (VQA)**: The task of answering questions about an image.",
    "**Image Captioning (AI-based)**: Automatically generating a textual description for an image.",
    "**Video Understanding (AI-based)**: Extracting information and insights from video data.",
    "**Multimodal Sentiment Analysis**: Analyzing emotions by combining information from text, audio, and video.",
    "**LMMs (Large Multimodal Models)**: The extension of LLMs to multiple modalities.",
    "**Instruction-Following Multimodal Models**: Models that can perform complex tasks based on multimodal instructions.",
    "**Robotics and AI (Embodied AI)**: Integrating AI into physical agents that can interact with the world.",
    "**Sim-to-Real Transfer (Robotics)**: Training a robot in a simulated environment and transferring the learned skills to a physical robot.",
    "**End-to-End Robot Learning**: Learning robot control directly from raw sensor inputs to motor outputs.",
    "**Imitation Learning (Behavior Cloning)**: Training a robot to mimic the behavior of a human expert.",
    "**Haptic AI**: AI systems that can sense and respond to touch.",
    "**Computer Vision for Robotics (SLAM, Object Detection)**: Enabling robots to see and navigate their environment.",
    "**SLAM (Simultaneous Localization and Mapping)**: The computational problem of constructing or updating a map of an unknown environment while simultaneously keeping track of an agent's location within it.",
    "**Norse Navigation Metaphor (Sólsteinn/Sunstone)**: Similar to SLAM or orientation in complex information spaces; finding your way when the path is clouded.",
    "**Architecural Dreki (Dragon Ship)**: A metaphor for a robust, well-engineered, and intimidatingly fast software system designed for raid-like efficiency.",
    "**Yggdrasil-scale Architecture**: Systems designed with central trunks (core services) and deep roots (data persistence) that connect multiple worlds (environments).",
    "**Digital Hamingja**: A metaphor for system reputation, reliability, and 'luck' (uptime) built through good engineering deeds.",
    "**Wyrd Analysis**: Debugging complex race conditions or event chains by tracing the 'threads' of fate through the logic.",
    "**Valhalla Scalability**: A system so robust it welcomes the 'honorable death' of individual nodes, knowing they will rise again in the next cluster.",
    "**Berserker Mode (Burst Scaling)**: A system's ability to go beyond its normal resource limits during extreme load events.",
    "**Gungnir Precision**: Unit tests that never miss their mark and strike deep into the logic of a PR.",
    "**Mjölnir Maintenance**: Using heavy-handed refactoring to smash technical debt and rework the system's foundation.",
    "**Futhark Encryption**: Using runes (cryptographic keys) to ward off the giants (adversaries) from the digital settlement."
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 1001 - 1500\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+1001}. {entry}\n")
