import os

file_path = r"c:\Users\volma\anti-gravity-githublocal-NorseSaga-Engine\Viking_girlfriend_openclaw_skill\viking_girlfriend_skill\data\knowledge_reference\SOFTWARE_ENGINEERING.md"

entries = [
    "**Cybersecurity Engineering (Shield-Building)**: The application of engineering principles to ensure the security of computer systems and networks.",
    "**Threat Modeling (STRIDE)**: A process for identifying, quantifying, and addressing the security threats of an application (Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege).",
    "**Attack Surface Analysis (Testing the Wall)**: Identifying all potential entry points and vulnerabilities in an application.",
    "**Secure Software Development Lifecycle (SSDLC)**: Integrating security practices into every phase of the software development lifecycle.",
    "**OWASP Top 10**: A standard awareness document for developers and web application security, representing the most critical security risks to web applications.",
    "**Broken Access Control (OWASP #1)**: Vulnerabilities where users can perform actions outside of their intended permissions.",
    "**Cryptographic Failures (OWASP #2)**: Failures related to the use of weak or missing cryptography.",
    "**Injection (OWASP #3)**: A class of vulnerabilities where untrusted data is sent to an interpreter as part of a command or query (e.g. SQLi, OS Command Injection).",
    "**Insecure Design (OWASP #4)**: Vulnerabilities that arise from the lack of security controls in the design phase.",
    "**Security Misconfiguration (OWASP #5)**: Vulnerabilities caused by incorrect or default security settings.",
    "**Vulnerable and Outdated Components (OWASP #6)**: Risks associated with using software components with known vulnerabilities.",
    "**Identification and Authentication Failures (OWASP #7)**: Failures in confirming the user's identity, authentication, and session management.",
    "**Software and Data Integrity Failures (OWASP #8)**: Vulnerabilities where code or data is updated without verifying its integrity.",
    "**Security Logging and Monitoring Failures (OWASP #9)**: Insufficient logging and monitoring that hinders the detection of attacks.",
    "**Server-Side Request Forgery (SSRF) (OWASP #10)**: A vulnerability where an attacker can cause a server to make a request to an unintended location.",
    "**SQL Injection (SQLi) (Shield-Piercing)**: Attacker inserts malicious SQL code into an inquiry to manipulate a database.",
    "**Cross-Site Scripting (XSS) (Digital Trickery)**: Attacker injects malicious scripts into content from otherwise trusted websites.",
    "**Stored XSS (Persistent XSS)**: The malicious script is permanently stored on the target server.",
    "**Reflected XSS (Non-Persistent XSS)**: The malicious script is 'reflected' off a web application to the victim's browser.",
    "**DOM-based XSS**: Malicious scripts are executed due to vulnerabilities in the client-side code itself.",
    "**Cross-Site Request Forgery (CSRF)**: An attack that forces an authenticated user to execute unwanted actions on a web application in which they're currently authenticated.",
    "**Insecure Direct Object Reference (IDOR)**: A type of access control vulnerability where an application uses user-supplied input to access objects directly.",
    "**Path Traversal (Dot-Dot-Slash Attack)**: An exploit that allows an attacker to access files and directories that are stored outside the web root folder.",
    "**Local File Inclusion (LFI)**: Attacker tricks the web application into exposing or running files on the server.",
    "**Remote File Inclusion (RFI)**: Attacker tricks the web application into loading a remote file, usually a script, from an external server.",
    "**Clickjacking (UI Redressing)**: A malicious technique of tricking a user into clicking on something different from what the user perceives.",
    "**XML External Entity (XXE) Injection**: An attack against an application that parses XML input.",
    "**Buffer Overflow (Vessel Overflow)**: A vulnerability where a program writes more data to a buffer than it can hold, overwriting adjacent memory.",
    "**Stack Overflow (Memory)**: A type of buffer overflow where the stack is the memory segment being overwritten.",
    "**Heap Overflow (Memory)**: A type of buffer overflow where the heap is the memory segment being overwritten.",
    "**Integer Overflow & Underflow**: When an arithmetic operation results in a value that is too large or too small to be represented by the integer type.",
    "**Use-After-Free (UAF)**: A memory corruption vulnerability that occurs when an application continues to use a pointer after it has been freed.",
    "**Double Free**: A memory corruption vulnerability that occurs when `free()` is called twice on the same memory address.",
    "**Format String Vulnerability**: When an application incorrectly uses user-supplied input as a format string for an output function (like `printf`).",
    "**Race Condition (Time-of-Check to Time-of-Use - TOCTOU)**: A vulnerability that occurs when a system's behavior depends on the sequence or timing of other uncontrollable events.",
    "**Directory Indexing (Information Leak)**: When a web server provides a list of all files in a directory that doesn't have an index file.",
    "**Sensitive Data Exposure**: When an application does not adequately protect sensitive information like passwords, credit card numbers, or PII.",
    "**Man-in-the-Middle (MITM) (Eavesdropping)**: An attack where the attacker secretly relays and possibly alters the communication between two parties who believe they are directly communicating with each other.",
    "**Man-in-the-Browser (MITB)**: A form of MITM attack where an attacker infects a web browser to modify web pages or transactions.",
    "**Session Hijacking (Stealing the Mead)**: Taking over a valid user session.",
    "**Session Fixation (Trapped Seat)**: Forcing a user to use a session ID that is known to the attacker.",
    "**Denial of Service (DoS) (Digital Siege)**: An attack that aims to make a computer or network resource unavailable to its intended users.",
    "**Distributed Denial of Service (DDoS) (The Great Raid)**: A DoS attack that uses multiple compromised systems as sources of attack traffic.",
    "**Ping of Death (Classic)**: A DoS attack that sends malformed or oversized ICMP packets to a target system.",
    "**SYN Flood**: A type of DoS attack that exploits a vulnerability in the TCP connection sequence.",
    "**UDP Flood**: A type of DoS attack that sends a large number of UDP packets to random ports on a target system.",
    "**HTTP Flood (Layer 7 DDoS)**: A type of DDoS attack that sends a large number of HTTP requests to a web server to overwhelm it.",
    "**Slowloris**: A type of DDoS attack that allows a single machine to take down another machine's web server with minimal bandwidth.",
    "**NTP Amplification**: A type of DDoS attack that exploits a vulnerability in the Network Time Protocol (NTP) to multiply the volume of attack traffic.",
    "**DNS Amplification**: A type of DDoS attack that exploits a vulnerability in the Domain Name System (DNS) to multiply the volume of attack traffic.",
    "**Smurf Attack (Classic)**: A type of DDoS attack that uses a large number of ICMP packets with the victim's spoofed source IP to broadcast addresses.",
    "**Fraggle Attack (Classic)**: A variation of a Smurf attack that uses UDP instead of ICMP.",
    "**Zero-Day Vulnerability (The Unknown Raider)**: A security flaw that is unknown to the software vendor and for which no patch or fix is available.",
    "**Exploit Kit**: A software toolkit used by cybercriminals to detect and exploit vulnerabilities on remote computers.",
    "**Ransomware (The Danegeld)**: Malicious software that encrypts a victim's files and demands a ransom for the decryption key.",
    "**Malware (Malicious Software)**: Any software intentionally designed to cause damage to a computer, server, client, or computer network.",
    "**Virus (Digital Infection)**: A type of malware that, when executed, replicates itself by modifying other computer programs and inserting its own code.",
    "**Worm (Self-Spreading)**: A type of malware that replicates itself in order to spread to other computers.",
    "**Trojan Horse (The Wooden Horse)**: A type of malware that is disguised as legitimate software.",
    "**Spyware (The Traitor)**: Malware that secretly gathers information about a person or organization and sends it to another entity.",
    "**Adware**: Malware that automatically displays or downloads advertising material when a user is online.",
    "**Rootkit (Deep Infiltrator)**: A collection of computer software, typically malicious, designed to enable access to a computer or an area of its software that is not otherwise allowed and often masks its existence.",
    "**Backdoor (Secret Entrance)**: A covert method of bypassing normal authentication or encryption in a computer system.",
    "**Keylogger (Keystroke Logging)**: A type of spyware that records the keys struck on a keyboard, typically in a covert manner.",
    "**Botnet (The Zombie Army)**: A network of private computers infected with malicious software and controlled as a group without the owners' knowledge.",
    "**Command and Control (C2) Server**: A server that sends commands to members of a botnet and receives reports from them.",
    "**Phishing (The Bait)**: The fraudulent practice of sending emails purporting to be from reputable companies in order to induce individuals to reveal personal information.",
    "**Spear Phishing (Targeted Bait)**: A phishing attempt that targets a specific individual or organization.",
    "**Whaling (Hunting the Jarl)**: A form of spear phishing that targets high-ranking executives.",
    "**Vishing (Voice Phishing)**: Phishing conducted by telephone or over VoIP.",
    "**Smishing (SMS Phishing)**: Phishing conducted via SMS text messages.",
    "**Social Engineering (Digital Manipulation)**: The use of deception to manipulate individuals into divulging confidential or personal information.",
    "**Pretexting**: Creating a fabricated scenario (pretext) to obtain information from a victim.",
    "**Baiting**: Promising an item or good (e.g. free music or movie download) to entice users.",
    "**Tailgating (Piggybacking)**: Following an authorized person into a secure area.",
    "**Quid Pro Quo (Something for Something)**: An attacker promises a service or benefit in exchange for information.",
    "**Dumpster Diving (Scavenging)**: Searching through trash to find information that can be used to facilitate a cyberattack.",
    "**Shoulder Surfing**: Looking over a person's shoulder as they enter sensitive information.",
    "**Eavesdropping (Technical)**: Secretly listening to a private conversation or communication.",
    "**Skimming**: The use of a device to clandestinely steal credit card information during a legitimate transaction.",
    "**ATM Skimmer**: A device that is placed over the card slot of an ATM to steal card information.",
    "**Advanced Persistent Threat (APT)**: A stealthy computer network attack in which a person or group gains unauthorized access to a network and remains undetected for an extended period.",
    "**Indicator of Compromise (IoC)**: Forensic evidence of potential malicious activity on a system or network.",
    "**Indicator of Attack (IoA)**: Evidence that an attack is currently in progress.",
    "**Digital Forensics (Law-Speaking of the Bytes)**: The branch of forensic science encompassing the recovery and investigation of material found in digital devices.",
    "**Incident Response (Slaying the Beast)**: The process of responding to and managing a security breach or cyberattack.",
    "**Identification (Incident Response)**: Detecting and confirming a security incident.",
    "**Containment (Incident Response)**: Preventing the security incident from spreading or causing more damage.",
    "**Eradication (Incident Response)**: Removing the root cause of the security incident.",
    "**Recovery (Incident Response)**: Restoring systems and data to a normal state.",
    "**Lessons Learned (Incident Response)**: Reviewing the incident to improve future response.",
    "**Vulnerability Scanning (Scouting the Wall)**: Using automated tools to identify potential security vulnerabilities.",
    "**Penetration Testing (Ethical Hacking / Raiding for Good)**: An authorized simulated cyberattack on a computer system, performed to evaluate its security.",
    "**Red Teaming (The Raiders)**: An independent group that challenges an organization's security assumptions by simulating the actions of a real-world adversary.",
    "**Blue Teaming (The Defenders)**: A group that handles the internal security of an organization and defends against cyberattacks.",
    "**Purple Teaming**: A collaborative approach where red and blue teams work together to improve an organization's overall security posture.",
    "**Bug Bounty Program (The Reward for Information)**: A deal offered by many websites, organizations and software developers by which individuals can receive recognition and compensation for reporting bugs.",
    "**Responsible Disclosure (Vulnerability Disclosure Policy)**: A model where a vulnerability is reported to the vendor, allowing them a reasonable amount of time to fix it before it is disclosed to the public.",
    "**Full Disclosure (Security)**: Disclosing all details of a vulnerability to the public immediately.",
    "**CVE (Common Vulnerabilities and Exposures)**: A list of publicly disclosed computer security flaws.",
    "**CVSS (Common Vulnerability Scoring System)**: A free and open industry standard for assessing the severity of computer system security vulnerabilities.",
    "**CWE (Common Weakness Enumeration)**: A community-developed list of common software security weaknesses.",
    "**CAPEC (Common Attack Pattern Enumeration and Classification)**: A comprehensive dictionary and classification taxonomy of known attacks.",
    "**ATT&CK Framework (MITRE)**: A globally-accessible knowledge base of adversary tactics and techniques based on real-world observations.",
    "**Kill Chain (Cyber)**: A conceptual model of the stages of a cyberattack (Reconnaissance, Weaponization, Delivery, Exploitation, Installation, Command and Control, Actions on Objectives).",
    "**Intrusion Detection System (IDS) (The Lookout)**: A device or software application that monitors a network or systems for malicious activity or policy violations.",
    "**Intrusion Prevention System (IPS) (The Guard)**: A network security tool that monitors network or system activities for malicious activity and takes action to prevent it.",
    "**Host-based IDS (HIDS)**: An IDS that monitors a single host for suspicious activity.",
    "**Network-based IDS (NIDS)**: An IDS that monitors network traffic for suspicious activity.",
    "**SIEM (Security Information and Event Management)**: A software solution that aggregates and analyzes activity from many different resources across your entire IT infrastructure.",
    "**SOAR (Security Orchestration, Automation, and Response)**: A set of software programs that help security teams coordinate and automate their response to security threats.",
    "**Security Operations Center (SOC) (The War Room)**: A centralized unit that deals with security issues on an organizational and technical level.",
    "**Managed Security Service Provider (MSSP)**: A company that provides outsourced security services to businesses.",
    "**Endpoint Detection and Response (EDR)**: An integrated endpoint security solution that combines real-time monitoring and collection of endpoint data with rules-based automated response.",
    "**Extended Detection and Response (XDR)**: A security technology that unifies detection and response across multiple security layers.",
    "**Network Detection and Response (NDR)**: A security solution that uses machine learning and data analytics to detect and respond to suspicious activity on a network.",
    "**Threat Intelligence (The Scout's Report)**: Information that an organization uses to understand the threats that have, will, or are currently targeting the organization.",
    "**OSINT (Open Source Intelligence)**: Information gathered from publicly available sources.",
    "**Dark Web Monitoring**: The process of searching and tracking information on the dark web.",
    "**Honey Pot (The Decoy)**: A security mechanism set to detect, deflect, or, in some manner, counteract attempts at unauthorized use of information systems.",
    "**Honey Net**: A network of honey pots.",
    "**Honey Token**: Data that appears valuable but is actually a decoy used to detect unauthorized access.",
    "**Sandboxing (The Training Grounds)**: A security mechanism for separating running programs, usually in an effort to mitigate system failures or software vulnerabilities from spreading.",
    "**Virtual Private Network (VPN) (The Secret Path)**: An encrypted tunnel over a public network.",
    "**Firewall (The Great Wall)**: A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules.",
    "**Packet Filtering Firewall**: A firewall that filters traffic based on source/destination IP addresses, ports, and protocols.",
    "**Stateful Inspection Firewall**: A firewall that tracks the state of active network connections and allows or blocks traffic based on that state.",
    "**Next-Generation Firewall (NGFW)**: A firewall that adds deep-packet inspection, intrusion prevention, and application-level control to traditional firewall features.",
    "**Web Application Firewall (WAF)**: A firewall that specifically targets web application traffic.",
    "**Database Firewall**: A firewall that monitors and filters traffic to a database.",
    "**Air Gapping (The Isolated Island)**: A security measure that involves isolating a computer or network from any other network, including the Internet.",
    "**Bastion Host (The Front Gate)**: A specialized computer on a network specifically designed and configured to withstand attacks.",
    "**DMZ (Demilitarized Zone) (The Buffer Zone)**: A physical or logical subnetwork that contains and exposes an organization's external-facing services to an untrusted, usually larger, network such as the Internet.",
    "**Cryptography (Writing in Runes)**: The practice and study of techniques for secure communication in the presence of adversarial behavior.",
    "**Encryption (Hiding the Secret)**: The process of converting information or data into a code, especially to prevent unauthorized access.",
    "**Decryption (Revealing the Secret)**: The process of converting encrypted data back into its original form.",
    "**Cipher (The Method)**: An algorithm for performing encryption or decryption.",
    "**Symmetric Key Cryptography (The Shared Secret Key)**: A type of cryptography where the same key is used for both encryption and decryption.",
    "**AES (Advanced Encryption Standard)**: A symmetric-key block cipher algorithm used worldwide.",
    "**DES (Data Encryption Standard) (Obsolete)**: A symmetric-key algorithm for the encryption of digital data.",
    "**3DES (Triple DES) (Obsolete)**: A symmetric-key block cipher, which applies the DES cipher algorithm three times to each data block.",
    "**ChaCha20 & Poly1305**: A high-speed symmetric cipher and message authentication code.",
    "**Asymmetric Key Cryptography (Public Key Cryptography / Two-Key Rune System)**: A type of cryptography that uses a pair of keys: a public key and a private key.",
    "**Public Key (The Shield-Mark)**: A key that can be shared with anyone.",
    "**Private Key (The Soul-Key)**: A key that must be kept secret.",
    "**RSA (Rivest-Shamir-Adleman)**: A widely used asymmetric cryptographic algorithm.",
    "**Elliptic Curve Cryptography (ECC)**: An approach to public-key cryptography based on the algebraic structure of elliptic curves over finite fields.",
    "**Diffie-Hellman Key Exchange (DH)**: A method of securely exchanging cryptographic keys over a public channel.",
    "**ECDH (Elliptic Curve Diffie-Hellman)**: A key agreement protocol that allows two parties to establish a shared secret over an insecure channel using ECC.",
    "**Digital Signature (The Jarl's Seal)**: A mathematical scheme for demonstrating the authenticity of digital messages or documents.",
    "**ECDSA (Elliptic Curve Digital Signature Algorithm)**: A digital signature algorithm that uses ECC.",
    "**Hash Function (The Unbreakable Seal)**: A mathematical algorithm that maps data of arbitrary size to a bit array of a fixed size.",
    "**SHA-256 (Secure Hash Algorithm 256-bit)**: A popular cryptographic hash function.",
    "**MD5 (Message Digest 5) (Insecure)**: A widely used hash function producing a 128-bit hash value.",
    "**SHA-1 (Insecure)**: A cryptographic hash function which takes an input and produces a 160-bit hash value.",
    "**HMAC (Hash-based Message Authentication Code)**: A specific type of message authentication code (MAC) involving a cryptographic hash function and a secret cryptographic key.",
    "**Salt (Cryptography)**: Random data that is used as an additional input to a one-way function that hashes data, a password or passphrase.",
    "**Pepper (Cryptography)**: A secret constant added to a password before hashing, similar to salt but not stored in the database.",
    "**Key Derivation Function (KDF)**: A cryptographic hash function that derives one or more secret keys from a secret value such as a main key or a password.",
    "**Bcrypt, Scrypt, Argon2**: Modern, secure password hashing algorithms designed to be slow and memory-intensive to resist brute-force attacks.",
    "**PKI (Public Key Infrastructure)**: A set of roles, policies, hardware, software and procedures needed to create, manage, distribute, use, store and revoke digital certificates and manage public-key encryption.",
    "**Certificate Authority (CA) (The Trust-Giver)**: An entity that issues digital certificates.",
    "**Registration Authority (RA)**: An entity that verifies the identity of an applicant for a digital certificate.",
    "**Digital Certificate (Identity Rune)**: An electronic document used to prove pixels of a public key.",
    "**X.509**: A standard that defines the format of public key certificates.",
    "**CRL (Certificate Revocation List)**: A list of digital certificates that have been revoked by the issuing certificate authority.",
    "**OCSP (Online Certificate Status Protocol)**: An Internet protocol used for obtaining the revocation status of an X.509 digital certificate.",
    "**SSL (Secure Sockets Layer) (Obsolete)**: The predecessor to TLS.",
    "**TLS (Transport Layer Security)**: A cryptographic protocol designed to provide communications security over a computer network.",
    "**HTTPS (HTTP Secure)**: An extension of HTTP for secure communication over a computer network.",
    "**Perfect Forward Secrecy (PFS)**: A feature of specific key agreement protocols that ensures that a session key derived from a set of long-term keys will not be compromised if one of the long-term keys is compromised in the future.",
    "**Quantum-Resistant Cryptography (The Unbreakable Runes of the Future)**: Cryptographic algorithms that are thought to be secure against a cryptanalytic attack by a quantum computer.",
    "**Post-Quantum Cryptography (PQC)**: Another term for quantum-resistant cryptography.",
    "**NIST PQC Competition**: An international competition organized by NIST to find the best quantum-resistant cryptographic algorithms.",
    "**Lattice-Based Cryptography**: A class of quantum-resistant cryptographic algorithms based on lattice problems.",
    "**Kyber (Crystals-Kyber)**: A key-encapsulation mechanism (KEM) selected by NIST for quantum-resistant cryptography.",
    "**Dilithium (Crystals-Dilithium)**: A digital signature algorithm selected by NIST for quantum-resistant cryptography.",
    "**Fully Homomorphic Encryption (FHE)**: A form of encryption that allows computations to be performed on ciphertext, generating an encrypted result which, when decrypted, matches the result of the operations as if they had been performed on the plaintext.",
    "**Searchable Symmetric Encryption (SSE)**: Encryption that allows for keyword searches on encrypted data without decrypting it.",
    "**Proxy Re-Encryption (PRE)**: A type of public-key encryption that allows a proxy to transform a ciphertext that has been encrypted for one party into a ciphertext for another party, without the proxy being able to see the underlying data.",
    "**Identity-Based Encryption (IBE)**: A type of public-key encryption in which a user can generate a public key from a unique identifier of an individual.",
    "**Attribute-Based Encryption (ABE)**: A type of public-key encryption in which the secret key of a user and the ciphertext are dependent upon attributes.",
    "**Functional Encryption (FE)**: A type of public-key encryption that allows a user with a specific key to compute a function of the encrypted data without seeing the data itself.",
    "**Steganography (Hidden in Plain Sight)**: The practice of concealing a message, image, or video within another message, image, or video.",
    "**Digital Watermarking**: A kind of marker covertly embedded in a noise-tolerant signal such as audio, video or image data.",
    "**Obfuscation (Code Muddying)**: The practice of making code more difficult for humans to understand.",
    "**Minification**: Removing all unnecessary characters from source code without changing its functionality.",
    "**Packer (Software)**: A program that compresses and optionally encrypts an executable file.",
    "**Anti-Debugging (Warding off the Analysts)**: Techniques used by software to prevent itself from being analyzed by a debugger.",
    "**Anti-Virtualization (Warding off the Sandbox)**: Techniques used by software to detect if it's running in a virtual machine and change its behavior.",
    "**Control Flow Obfuscation**: Modifying the execution path of a program to make it harder to follow.",
    "**Dead Code Insertion**: Adding code that is never executed to confuse analysts.",
    "**Instruction Substitution**: Replacing common CPU instructions with more complex sequences of instructions that do the same thing.",
    "**Opaque Predicates**: Branching conditions that always evaluate to the same value but are difficult for an analyst to determine.",
    "**Polymorphic Code**: Code that uses a mutation engine to change its appearance each time it replicates.",
    "**Metamorphic Code**: Code that completely rewrites itself each time it replicates.",
    "**Reverse Engineering (Deconstructing the Rune-Work)**: The process of analyzing a system to identify its components and their interrelationships and create representations of the system in another form or at a higher level of abstraction.",
    "**Disassembler (IDA Pro, Ghidra)**: A program that translates machine code into assembly language.",
    "**Debugger (x64dbg, GDB, OllyDbg)**: A program used to test and debug other programs.",
    "**Decompiler (JADX, dotPeek)**: A program that translates binary code into a high-level programming language.",
    "**Static Analysis (Software Security)**: Analyzing software without executing it.",
    "**Dynamic Analysis (Software Security)**: Analyzing software while it is executing.",
    "**Fuzzing (Robustness Testing)**: An automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program.",
    "**Mutation-based Fuzzing**: Modifying existing, valid inputs to create new fuzzed inputs.",
    "**Generation-based Fuzzing**: Creating new fuzzed inputs from scratch based on a specification or model.",
    "**Grey-box Fuzzing (AFL)**: Fuzzing that uses code coverage feedback to guide the search for new inputs.",
    "**American Fuzzy Lop (AFL)**: A popular grey-box fuzzer.",
    "**LibFuzzer**: A library for in-process, coverage-guided, evolutionary fuzzing of other libraries.",
    "**Symbolic Execution**: A technique in computer science that can be used to analyze a program and see what inputs cause each part of a program to execute.",
    "**Concolic Testing**: A hybrid software verification technique that performs symbolic execution along a concrete execution path.",
    "**Taint Analysis**: A form of information-flow analysis that tracks the influence of untrusted input on a program's execution.",
    "**Control-Flow Integrity (CFI)**: A security policy that prevents an attacker from redirecting the flow of execution of a program to an arbitrary location.",
    "**ASLR (Address Space Layout Randomization)**: A computer security technique which involves randomly arranging the positions of key data areas of a program.",
    "**DEP (Data Execution Prevention) / NX (No-Execute)**: A security feature that prevents code from being executed from non-executable memory segments.",
    "**Stack Canary (The Bird in the Mine)**: A value placed on the stack that is checked before a function returns to detect stack buffer overflows.",
    "**Fortify Source**: A set of compiler features that add run-time checks to several potentially dangerous functions.",
    "**Control-Flow Guard (CFG)**: A platform security feature of Windows that prevents some types of memory corruption attacks.",
    "**SafeSEH (Structured Exception Handling)**: A security feature that prevents an attacker from overwriting an exception handler on the stack.",
    "**SEHOP (Structured Exception Handler Overwrite Protection)**: A security feature that prevents an attacker from exploiting an SEH overwrite.",
    "**Return-Oriented Programming (ROP) (The Raider's Trick)**: A technique used by an attacker to execute code in the presence of security measures such as NX.",
    "**ROP Chain**: A sequence of small pieces of existing code (gadgets) linked together to perform a specific task.",
    "**Jump-Oriented Programming (JOP)**: A variation of ROP that uses indirect jumps instead of returns.",
    "**Sigreturn-Oriented Programming (SROP)**: A variation of ROP that exploits the `sigreturn` system call.",
    "**Kernel-based Attacks (Attacking the Realm's Core)**: Exploits that target the operating system kernel.",
    "**Local Privilege Escalation (LPE)**: An attack that allows a user with limited privileges to gain higher privileges (e.g. root or SYSTEM).",
    "**Remote Privilege Escalation**: An attack that allows a remote user to gain privileges on a target system.",
    "**Container Escape (Escaping the Pit)**: An exploit that allows an attacker to break out of a container and gain access to the host operating system.",
    "**Side-Channel Attack (The Whisper-Thin Threat)**: Any attack based on information gained from the physical implementation of a computer system, rather than weaknesses in the implemented algorithm itself.",
    "**Timing Attack**: A side-channel attack that exploits variations in the time it takes to perform specific operations.",
    "**Power Analysis (DPA, SPA)**: A side-channel attack that exploits variations in a system's power consumption.",
    "**Electromagnetic Analysis (EMA)**: A side-channel attack that exploits electromagnetic emissions from a computer system.",
    "**Acoustic Cryptanalysis**: A side-channel attack that exploits the sound emitted during a computation.",
    "**Differential Fault Analysis (DFA)**: A side-channel attack that involves inducing faults in a system and observing the results.",
    "**Cold Boot Attack**: A type of physical attack that exploits the data remanence property of DRAM to recover cryptographic keys from memory after a computer is turned off.",
    "**TEMPEST (Spec)**: A U.S. National Security Agency specification and a NATO certification referring to spying on information systems through out-of-band emanations.",
    "**Rowhammer (The Memory-Shaker)**: A hardware-level exploit that targets vulnerabilities in DDR3 and DDR4 RAM.",
    "**Spectre (CPU Flaw)**: A vulnerability that allows an attacker to bypass isolation between applications by exploiting speculative execution in modern CPUs.",
    "**Meltdown (CPU Flaw)**: A vulnerability that allows an attacker to read kernel memory by exploiting out-of-order execution in modern Intel CPUs.",
    "**L1TF (L1 Terminal Fault / Foreshadow)**: A speculative execution side-channel vulnerability that affects modern Intel processors.",
    "**MDS (Microarchitectural Data Sampling / ZombieLoad / RIDL / Fallout)**: A set of speculative execution side-channel vulnerabilities that affect modern Intel processors.",
    "**Downfall (CPU Vulnerability)**: A vulnerability that allows an attacker to steal data from other users and applications on Intel processors.",
    "**Re-Spec (CPU Vulnerability)**: A class of side-channel attacks that exploit the ways that processors predict whether an instruction is speculatively executed.",
    "**Security by Obscurity (The Fool's Shield)**: Relying on the secrecy of a system's design for security, rather than robust security mechanisms.",
    "**Security by Design**: Building security into a system from the ground up.",
    "**Open Security Principle (Kerckhoffs's Principle)**: The principle that a cryptographic system should be secure even if everything about the system, except for the key, is public knowledge.",
    "**Shannon's Maxim**: 'The enemy knows the system'.",
    "**Zero Trust Architecture (Always Verify)**: A security model that requires all users, devices, and applications to be authenticated and authorized regardless of their location on the network.",
    "**BeyondCorp (Google)**: A zero-trust security framework developed by Google.",
    "**Micro-Segmentation (The Digital Moat)**: A network security technique that involves dividing a network into smaller, isolated zones.",
    "**Zoning and Conduit (Industrial Security)**: A concept for logically grouping assets and communication channels in an industrial control system.",
    "**Principle of Least Privilege (PoLP)**: Granting users and applications only the minimum privileges necessary to perform their tasks.",
    "**Need-to-know**: Limiting access to information to those individuals who require it to perform their official duties.",
    "**Privileged Access Management (PAM)**: The strategies and technologies for monitoring and managing privileged access to systems.",
    "**Identity and Access Management (IAM)**: A framework for managing digital identities and controlling access to resources.",
    "**Role-Based Access Control (RBAC)**: An approach to restricting system access to authorized users based on their roles within an organization.",
    "**Attribute-Based Access Control (ABAC)**: An access control model where access rights are granted to users through the use of policies which combine attributes together.",
    "**Policy-Based Access Control (PBAC)**: A strategy for managing security and user access based on predefined policies.",
    "**Delegated Authentication**: Allowing one application to authenticate a user on behalf of another.",
    "**Federated Identity**: A system that allows users to use the same credentials for multiple applications across different organizations.",
    "**Single Sign-On (SSO) (The One Key)**: A session and user authentication service that allows a user to use one set of login credentials to access multiple applications.",
    "**Same-Origin Policy (SOP)**: A critical security mechanism that restricts how a document or script loaded from one origin can interact with a resource from another origin.",
    "**CORS (Cross-Origin Resource Sharing)**: A mechanism that allows many resources (e.g., fonts, JavaScript, etc.) on a web page to be requested from another domain outside the domain from which the resource originated.",
    "**Content Security Policy (CSP)**: An added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting (XSS) and data injection attacks.",
    "**Strict-Transport-Security (HSTS)**: A web security policy mechanism that helps to protect websites against man-in-the-middle attacks.",
    "**X-Frame-Options**: A header that can be used to indicate whether or not a browser should be allowed to render a page in a `<frame>`, `<iframe>`, `<embed>` or `<object>`.",
    "**X-Content-Type-Options: nosniff**: A header that prevents a browser from sniffing the content type of a response.",
    "**Referrer-Policy**: A header that controls how much referrer information should be included with requests.",
    "**Permissions-Policy (Feature-Policy)**: A header that allows a site to control which browser features (like camera, microphone) can be used by that site and any sub-frames it loads.",
    "**Secure Cookie Flags (Secure, HttpOnly, SameSite)**: Critical flags for protecting cookies from being stolen or misused.",
]

with open(file_path, "a", encoding="utf-8") as f:
    f.write("\n## Entries 1501 - 2000\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+1501}. {entry}\n")
