import os
from pathlib import Path

_KNOWLEDGE_REF = (
    Path(__file__).resolve().parent.parent
    / "viking_girlfriend_skill" / "data" / "knowledge_reference"
)
file_path = _KNOWLEDGE_REF / "SOFTWARE_ENGINEERING.md"

entries = [
    "**SOLID Principles**: A set of five design principles intended to make software designs more understandable, flexible, and maintainable.",
    "**Single Responsibility Principle (SRP)**: A class should have one, and only one, reason to change.",
    "**Open/Closed Principle (OCP)**: Software entities should be open for extension, but closed for modification.",
    "**Liskov Substitution Principle (LSP)**: Objects of a superclass should be replaceable with objects of its subclasses without breaking the application.",
    "**Interface Segregation Principle (ISP)**: No client should be forced to depend on methods it does not use.",
    "**Dependency Inversion Principle (DIP)**: High-level modules should not depend on low-level modules; both should depend on abstractions.",
    "**DRY (Don't Repeat Yourself)**: A principle of software development aimed at reducing repetition of software patterns.",
    "**KISS (Keep It Simple, Stupid)**: A design principle stating that most systems work best if they are kept simple rather than made complicated.",
    "**YAGNI (You Ain't Gonna Need It)**: A principle which states that a programmer should not add functionality until deemed necessary.",
    "**Design Patterns**: Typical solutions to common problems in software design.",
    "**Singleton Pattern**: Ensures a class has only one instance and provides a global point of access to it.",
    "**Factory Method Pattern**: Defines an interface for creating an object, but lets subclasses decide which class to instantiate.",
    "**Abstract Factory Pattern**: Provides an interface for creating families of related or dependent objects without specifying their concrete classes.",
    "**Builder Pattern**: Separates the construction of a complex object from its representation.",
    "**Prototype Pattern**: Specifies the kinds of objects to create using a prototypical instance, and creates new objects by copying this prototype.",
    "**Adapter Pattern**: Allows the interface of an existing class to be used as another interface.",
    "**Bridge Pattern**: Decouples an abstraction from its implementation so that the two can vary independently.",
    "**Composite Pattern**: Composes objects into tree structures to represent part-whole hierarchies.",
    "**Decorator Pattern**: Attaches additional responsibilities to an object dynamically.",
    "**Facade Pattern**: Provides a unified interface to a set of interfaces in a subsystem.",
    "**Flyweight Pattern**: Uses sharing to support large numbers of fine-grained objects efficiently.",
    "**Proxy Pattern**: Provides a surrogate or placeholder for another object to control access to it.",
    "**Chain of Responsibility Pattern**: Avoids coupling the sender of a request to its receiver by giving more than one object a chance to handle the request.",
    "**Command Pattern**: Encapsulates a request as an object, thereby letting you parameterize clients with different requests.",
    "**Interpreter Pattern**: Given a language, defines a representation for its grammar along with an interpreter that uses the representation to interpret sentences in the language.",
    "**Iterator Pattern**: Provides a way to access the elements of an aggregate object sequentially without exposing its underlying representation.",
    "**Mediator Pattern**: Defines an object that encapsulates how a set of objects interact.",
    "**Memento Pattern**: Without violating encapsulation, captures and externalizes an object's internal state so that the object can be restored to this state later.",
    "**Observer Pattern**: Defines a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically.",
    "**State Pattern**: Allows an object to alter its behavior when its internal state changes.",
    "**Strategy Pattern**: Defines a family of algorithms, encapsulates each one, and makes them interchangeable.",
    "**Template Method Pattern**: Defines the skeleton of an algorithm in an operation, deferring some steps to subclasses.",
    "**Visitor Pattern**: Represents an operation to be performed on the elements of an object structure.",
    "**Unit Testing**: Testing individual units or components of a software.",
    "**Integration Testing**: Testing groups of related modules to ensure they work together correctly.",
    "**System Testing**: Testing the complete and integrated software product.",
    "**Acceptance Testing**: Testing conducted to determine if the requirements of a specification or contract are met.",
    "**Regression Testing**: Re-running functional and non-functional tests to ensure that previously developed and tested software still performs after a change.",
    "**Test-Driven Development (TDD)**: A software development process relying on software requirements being converted to test cases before software is fully developed.",
    "**Behavior-Driven Development (BDD)**: An extension of TDD that focuses on the behavioral requirement of software.",
    "**Continuous Integration (CI)**: The practice of merging all developers' working copies to a shared mainline several times a day.",
    "**Continuous Deployment (CD)**: A software engineering approach in which software functionalities are delivered frequently through automated deployments.",
    "**Version Control System (VCS)**: A system that records changes to a file or set of files over time so that you can recall specific versions later.",
    "**Git**: A distributed version control system for tracking changes in source code during software development.",
    "**Branching**: The process of creating a separate line of development in a version control system.",
    "**Merging**: The process of combining changes from one branch into another.",
    "**Rebasing**: The process of moving or combining a sequence of commits to a new base commit.",
    "**Pull Request (PR)**: A method of submitting contributions to an open-source project or onto a specific branch.",
    "**Agile Software Development**: An approach to software development under which requirements and solutions evolve through the collaborative effort of self-organizing and cross-functional teams.",
    "**Scrum**: An agile framework for managing knowledge work, with an emphasis on software development.",
    "**Kanban**: A method for managing the creation of products with an emphasis on continual delivery while not overburdening the development team.",
    "**Sprint**: A set period of time during which specific work has to be completed and made ready for review.",
    "**Epics**: Large bodies of work that can be broken down into a number of smaller tasks (called stories).",
    "**User Stories**: Short, simple descriptions of a feature told from the perspective of the person who desires the new capability.",
    "**Refactoring**: The process of restructuring existing computer code—changing the factoring—without changing its external behavior.",
    "**Technical Debt**: The implied cost of additional rework caused by choosing an easy solution now instead of using a better approach that would take longer.",
    "**Code Review**: A systematic examination of computer source code.",
    "**Static Code Analysis**: The analysis of computer software that is performed without actually executing programs.",
    "**Dynamic Code Analysis**: The analysis of computer software that is performed by executing programs on a real or virtual processor.",
    "**Microservices Architecture**: An architectural style that structures an application as a collection of services that are highly maintainable and testable.",
    "**Monolithic Architecture**: A traditional unified model for the design of a software program.",
    "**Serverless Computing**: A cloud-computing execution model in which the cloud provider allocates machine resources on demand.",
    "**Docker**: A set of platform as a service products that use OS-level virtualization to deliver software in packages called containers.",
    "**Kubernetes**: An open-source container-orchestration system for automating computer application deployment, scaling, and management.",
    "**API (Application Programming Interface)**: A set of functions and procedures allowing the creation of applications that access the features or data of an operating system, application, or other service.",
    "**REST (Representational State Transfer)**: An architectural style for providing standards between computer systems on the web.",
    "**GraphQL**: A data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data.",
    "**gRPC**: A high-performance, open-source universal RPC framework.",
    "**Webhooks**: A way for an app to provide other applications with real-time information.",
    "**Authentication**: The process of verifying the identity of a user or process.",
    "**Authorization**: The process of specifying access rights/privileges to resources.",
    "**JWT (JSON Web Token)**: An open standard that defines a compact and self-contained way for securely transmitting information between parties as a JSON object.",
    "**OAuth 2.0**: An industry-standard protocol for authorization.",
    "**CORS (Cross-Origin Resource Sharing)**: A mechanism that allows many resources on a web page to be requested from another domain outside the domain from which the resource originated.",
    "**Database Normalization**: The process of structuring a relational database in accordance with a series of so-called normal forms.",
    "**SQL (Structured Query Language)**: A standard language for accessing and manipulating databases.",
    "**NoSQL**: A mechanism for storage and retrieval of data that is modeled in means other than the tabular relations used in relational databases.",
    "**ACID Properties**: Atomicity, Consistency, Isolation, Durability - a set of properties of database transactions.",
    "**BASE Properties**: Basically Available, Soft state, Eventual consistency - an alternative to ACID for NoSQL databases.",
    "**Indexing**: A data structure technique to efficiently retrieve records from the database files based on some attributes on which the indexing has been done.",
    "**Query Optimization**: A feature of many relational database management systems in which the database system attempts to determine the most efficient way to execute a given query.",
    "**Concurrency Control**: A database management systems requirement for ensuring that database transactions are performed concurrently without violating the data integrity.",
    "**Memory Management**: The process of controlling and coordinating computer memory.",
    "**Garbage Collection (GC)**: A form of automatic memory management.",
    "**Heap Memory**: A region of memory that was used for dynamic memory allocation.",
    "**Stack Memory**: A region of memory that is used for local variables and function calls.",
    "**Pointer**: A variable whose value is the address of another variable.",
    "**Buffer Overflow**: An anomaly where a program, while writing data to a buffer, overruns the buffer's boundary and overwrites adjacent memory locations.",
    "**Multithreading**: The ability of a central processing unit (CPU) to provide multiple threads of execution concurrently.",
    "**Race Condition**: A phenomenon that may occur inside a critical section where the output of the process is unexpectedly dependent on the sequence or timing of other events.",
    "**Deadlock**: A state in which each member of a group is waiting for another member, including itself, to take action.",
    "**Mutex (Mutual Exclusion)**: A program object that allows multiple program threads to share the same resource, such as file access, but not simultaneously.",
    "**Semaphore**: A variable or abstract data type used to control access to a common resource by multiple processes in a concurrent system.",
    "**Event-Driven Programming**: A programming paradigm in which the flow of the program is determined by events such as user actions.",
    "**Functional Programming**: A programming paradigm where programs are constructed by applying and composing functions.",
    "**Object-Oriented Programming (OOP)**: A programming paradigm based on the concept of \"objects\", which can contain data and code.",
    "**Procedural Programming**: A programming paradigm, derived from imperative programming, based on the concept of the procedure call.",
    "**Declarative Programming**: A programming paradigm that expresses the logic of a computation without describing its control flow.",
    "**Imperative Programming**: A programming paradigm that uses statements that change a program's state.",
    "**Aspect-Oriented Programming (AOP)**: A programming paradigm that aims to increase modularity by allowing the separation of cross-cutting concerns."
]

os.makedirs(os.path.dirname(file_path), exist_ok=True)
with open(file_path, "w", encoding="utf-8") as f:
    f.write("# Knowledge Domain: Software Engineering\n\n")
    f.write("This database contains entries related to software engineering, as curated by Sigrid.\n\n")
    f.write("## Entries 1 - 100\n\n")
    for i, entry in enumerate(entries):
        f.write(f"{i+1}. {entry}\n")
