import os

file_path = r"c:\Users\volma\anti-gravity-githublocal-NorseSaga-Engine\Viking_girlfriend_openclaw_skill\viking_girlfriend_skill\data\knowledge_reference\CYBERSECURITY.md"

entries = [
    "**Cybersecurity (The Shield of Midgard)**: The practice of protecting systems, networks, and programs from digital attacks.",
    "**Information Security (InfoSec)**: The practice of protecting information by mitigating information risks.",
    "**CIA Triad (Confidentiality, Integrity, Availability)**: The core model designed to guide policies for information security within an organization.",
    "**Confidentiality (The Secret Rune)**: Ensuring that information is accessible only to those authorized to have access.",
    "**Integrity (The Unbroken Oath)**: Ensuring that information is accurate and has not been tampered with.",
    "**Availability (The Always-Open Gate)**: Ensuring that information and resources are available to authorized users when needed.",
    "**Authentication (The Identification Ritual)**: The process of verifying the identity of a user, device, or system.",
    "**Authorization (The Right of Entry)**: The process of granting or denying access to resources based on a user's identity.",
    "**Accounting (The Scribe's Record)**: The process of tracking user activity and resource usage.",
    "**Non-Repudiation (The Indelible Mark)**: The assurance that someone cannot deny the validity of something.",
    "**Least Privilege (The Minimal Trust)**: The principle of providing users with only the minimum level of access needed to perform their jobs.",
    "**Defense in Depth (The Layered Walls of Asgard)**: A security strategy that uses multiple layers of defense to protect information.",
    "**Attack Surface (The Exposed Frontier)**: The total number of points (the 'attack vectors') where an unauthorized user (the 'attacker') can try to enter data to or extract data from an environment.",
    "**Threat (The Shadow over the Realm)**: A potential cause of an unwanted incident, which may result in harm to a system or organization.",
    "**Vulnerability (The Chink in the Armor)**: A weakness in an information system, system security procedures, internal controls, or implementation that could be exploited by a threat source.",
    "**Risk (The Weight of the Danger)**: The potential for loss, damage, or destruction of an asset as a result of a threat exploiting a vulnerability.",
    "**Exploit (The Raider's Tool)**: A piece of software, a chunk of data, or a sequence of commands that takes advantage of a vulnerability to cause unintended or unanticipated behavior to occur on computer software, hardware, or something electronic.",
    "**Threat Actor (The Adversary / The Raider)**: An entity that is partially or wholly responsible for an incident that impacts – or has the potential to impact – an organization's security.",
    "**Malware (The Digital Plague)**: Software that is specifically designed to disrupt, damage, or gain unauthorized access to a computer system.",
    "**Virus (The Spreading Sickness)**: A type of malware that, when executed, replicates itself by modifying other computer programs and inserting its own code.",
    "**Worm (The Burrowing Beast)**: A standalone malware computer program that replicates itself in order to spread to other computers.",
    "**Trojan Horse (The Deceptive Gift)**: Any malware which misleads users of its true intent.",
    "**Ransomware (The Digital Extortion)**: A type of malware that threatens to publish the victim's data or perpetually block access to it unless a ransom is paid.",
    "**Spyware (The Hidden Eye)**: Software that aims to gather information about a person or organization, without their knowledge, and send such information to another entity without the consumer's consent.",
    "**Adware**: Software that automatically displays or downloads advertising material such as banners or pop-ups when a user is online.",
    "**Rootkit (The Deep Infiltrator)**: A collection of computer software, typically malicious, designed to enable access to a computer or an area of its software that is not otherwise allowed and often masks its existence or the existence of other software.",
    "**Keylogger (The Stroke-Stealer)**: A type of surveillance software that has the capability to record every keystroke you make to a log file, usually encrypted.",
    "**Backdoor (The Secret Entrance)**: A method of bypassing normal authentication or encryption in a computer system, a product, or an embedded device.",
    "**Logic Bomb (The Sleeping Trap)**: A piece of code intentionally inserted into a software system that will set off a malicious function when specified conditions are met.",
    "**Botnet (The Shadow Army)**: A number of Internet-connected computers, each of which is running one or more bots.",
    "**Phishing (The Deceptive Hook)**: The fraudulent practice of sending emails purporting to be from reputable companies in order to induce individuals to reveal personal information, such as passwords and credit card numbers.",
    "**Spear Phishing (The Targeted Strike)**: A phishing expedition in which the emails are carefully designed to target a particular person or organization.",
    "**Whaling (Hunting the Jarl)**: A form of spear phishing aimed at high-profile targets within an organization, such as senior executives.",
    "**Vishing (Voice Phishing)**: The fraudulent practice of making phone calls or leaving voice messages purporting to be from reputable companies in order to induce individuals to reveal personal information.",
    "**Smishing (SMS Phishing)**: Phishing involving a text message or Short Message Service (SMS).",
    "**Social Engineering (The Manipulation of the Mind)**: The use of deception to manipulate individuals into divulging confidential or personal information that may be used for fraudulent purposes.",
    "**Pretexting (The False Tale)**: A type of social engineering where an attacker creates a fabricated scenario to persuade a victim to provide information.",
    "**Baiting (The Tempting Trap)**: A type of social engineering where an attacker leaves a malware-infected device (like a USB flash drive) in a place where someone is likely to find it.",
    "**Quid Pro Quo (This for That)**: A type of social engineering where an attacker promises a benefit in exchange for information.",
    "**Tailgating (Piggybacking)**: A physical security breach in which an unauthorized person follows an authorized person into a restricted area.",
    "**Shoulder Surfing (The Peering Eye)**: A type of social engineering where an attacker looks over someone's shoulder to see their password or other sensitive information.",
    "**Dumpster Diving (Searching the Waste)**: A technique used to retrieve information that could be used to carry out a social engineering attack.",
    "**Cryptography (The Art of Hidden Runes)**: The practice and study of techniques for secure communication in the presence of adversarial behavior.",
    "**Encryption (Hiding the Rune)**: The process of converting information or data into a code, especially to prevent unauthorized access.",
    "**Decryption (Revealing the Rune)**: The process of taking encoded or encrypted text or other data and converting it back into text that you or the computer can read and understand.",
    "**Plaintext (The Clear Tongue)**: Information a user can read.",
    "**Ciphertext (The Hidden Tongue)**: The result of encryption performed on plaintext using an algorithm, called a cipher.",
    "**Cipher (The Rule of Hiding)**: An algorithm for performing encryption or decryption.",
    "**Key (The Rune-Key)**: A piece of information that determines the functional output of a cryptographic algorithm.",
    "**Symmetric Encryption (The Single Key)**: An encryption system where the same key is used for both encryption and decryption.",
    "**Asymmetric Encryption (The Twin Keys)**: An encryption system where different keys are used for encryption and decryption.",
    "**Public Key**: A key that can be shared with anyone.",
    "**Private Key (The Soul-Key)**: A key that must be kept secret.",
    "**Hash Function (The Digital Fingerprint)**: A mathematical function that converts an input into a fixed-size string of characters, which is typically a digest that is unique to the input.",
    "**Salt (Cryptography)**: Random data that is used as an additional input to a one-way function that hashes data, a password or passphrase.",
    "**Digital Signature (The Seal of the Jarl)**: A mathematical scheme for verifying the authenticity of digital messages or documents.",
    "**Digital Certificate (The Rune-Scroll of Identity)**: An electronic document used to prove the ownership of a public key.",
    "**Certificate Authority (CA) (The Keeper of the Seals)**: An entity that issues digital certificates.",
    "**Public Key Infrastructure (PKI)**: A set of roles, policies, hardware, software and procedures needed to create, manage, distribute, use, store and revoke digital certificates and manage public-key encryption.",
    "**TLS (Transport Layer Security)**: A cryptographic protocol designed to provide communications security over a computer network.",
    "**SSL (Secure Sockets Layer) (Obsolete)**: The predecessor to TLS.",
    "**Hashing Algorithms (MD5, SHA-1, SHA-256, SHA-3).**",
    "**Encryption Algorithms (AES, RSA, ECC, ChaCha20).**",
    "**AES (Advanced Encryption Standard)**: A symmetric block cipher chosen by the U.S. government to protect classified information.",
    "**RSA (Rivest-Shamir-Adleman)**: One of the first public-key cryptosystems and is widely used for secure data transmission.",
    "**ECC (Elliptic Curve Cryptography)**: An approach to public-key cryptography based on the algebraic structure of elliptic curves over finite fields.",
    "**Diffie-Hellman Key Exchange (The Secret Meeting)**: A method of securely exchanging cryptographic keys over a public channel.",
    "**Perfect Forward Secrecy (PFS)**: A feature of specific key agreement protocols that gives assurance that session keys will not be compromised even if long-term secrets used in the session key exchange are compromised.",
    "**Key Stretching (Strengthening the Rune)**: Techniques used to make a possibly weak key, typically a password or passphrase, more secure against a brute-force attack by increasing the time it takes to test each possible key.",
    "**Bcrypt & Scrypt**: Password hashing functions designed to be slow and memory-intensive to thwart brute-force attacks.",
    "**Argon2**: The winner of the Password Hashing Competition (PHC) and a modern, high-security password hashing function.",
    "**Steganography (The Rune Hidden in the Image)**: The practice of concealing a file, message, image, or video within another file, message, image, or video.",
    "**Cryptanalysis (Breaking the Runes)**: The study of analyzing information systems in order to study the hidden aspects of the systems.",
    "**Brute-Force Attack (The Relentless Siege)**: A trial-and-error method used to obtain information such as a user password or personal identification number (PIN).",
    "**Dictionary Attack (The Tome of Common Words)**: A technique for defeating a cipher or authentication mechanism by trying to determine its decryption key or password by trying hundreds or sometimes millions of likely possibilities, such as words in a dictionary.",
    "**Rainbow Table (The Premade Map of Hashes)**: A precomputed table for caching the output of cryptographic hash functions, usually for cracking password hashes.",
    "**Network Security (The Guarding of the Sea-Paths)**: The policies and practices adopted to prevent and monitor unauthorized access, misuse, modification, or denial of a computer network and network-accessible resources.",
    "**Firewall (The Wall of Flame)**: A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules.",
    "**Packet Filtering Firewall**: A firewall that examines each packet and blocks or allows it based on its header information.",
    "**Stateful Inspection Firewall**: A firewall that tracks the state of active connections and makes decisions based on the context of the traffic.",
    "**Next-Generation Firewall (NGFW)**: A part of the third generation of firewall technology, combining a traditional firewall with other network device filtering functions.",
    "**Proxy Server (The Intermediary)**: A server (a computer system or an application) that acts as an intermediary for requests from clients seeking resources from other servers.",
    "**VPN (Virtual Private Network) (The Hidden Path)**: A service that creates a safe, encrypted connection over a less secure network like the internet.",
    "**Intrusion Detection System (IDS) (The Scout)**: A device or software application that monitors a network or systems for malicious activity or policy violations.",
    "**Intrusion Prevention System (IPS) (The Defender)**: A network security/threat prevention technology that examines network traffic flows to detect and prevent vulnerability exploits.",
    "**SIEM (Security Information and Event Management)**: A subsection within the field of computer security, where software products and services combine security information management (SIM) and security event management (SEM).",
    "**DMZ (Demilitarized Zone) (The Buffer Realm)**: A physical or logical subnetwork that contains and exposes an organization's external-facing services to an untrusted, usually larger, network such as the Internet.",
    "**Honeypot (The Distraction Trap)**: A computer security mechanism set to detect, deflect, or, in some manner, counteract attempts at unauthorized use of information systems.",
    "**Honeynet**: A network of honeypots.",
    "**Air Gap (The Deep Isolation)**: A network security measure employed on one or more computers to ensure that a secure computer network is physically isolated from unsecured networks, such as the public Internet or an unsecured local area network.",
    "**VLAN (Virtual Local Area Network)**: Any broadcast domain that is partitioned and isolated in a computer network at the data link layer (OSI layer 2).",
    "**NAC (Network Access Control)**: A method of bolstering the security of a proprietary network by restricting the availability of network resources to endpoint devices that comply with a defined security policy.",
    "**Port Scanning (The Scout's Probe)**: A method for determining which ports on a network are open.",
    "**Nmap**: The most popular tool for port scanning.",
    "**Wireshark**: A popular network protocol analyzer.",
    "**TCP/IP (The Foundation of the Sea-Paths)**: The set of communications protocols used for the internet.",
    "**IP Spoofing (The False Identity)**: The creation of Internet Protocol (IP) packets with a false source IP address, for the purpose of hiding the identity of the sender or impersonating another computer system.",
    "**MAC Spoofing**: A technique for changing a factory-assigned Media Access Control (MAC) address of a network interface on a networked device.",
    "**Man-in-the-Middle (MITM) Attack (The Hidden Listener)**: An attack where the attacker secretly relays and possibly alters the communication between two parties who believe they are directly communicating with each other.",
    "**ARP Poisoning / Spoofing**: A technique by which an attacker sends (spoofed) Address Resolution Protocol (ARP) messages onto a local area network to link their MAC address with the IP address of a legitimate server or gateway on the network.",
    "**DNS Poisoning / Spoofing**: A type of computer security hacking in which corrupt Domain Name System data is introduced into a DNS resolver's cache, causing the name server to return an incorrect IP address.",
    "**DoS (Denial of Service) Attack (The Siege)**: A cyber-attack in which the perpetrator seeks to make a machine or network resource unavailable to its intended users by temporarily or indefinitely disrupting services of a host connected to the Internet.",
    "**DDoS (Distributed Denial of Service) Attack (The Great Siege)**: A DoS attack where the traffic comes from many different sources.",
    "**SYN Flood**: A type of DDoS attack that exploits a part of the normal TCP three-way handshake to consume resources on the targeted server and render it unresponsive.",
    "**UDP Flood**: A type of DDoS attack in which a large number of User Datagram Protocol (UDP) packets are sent to a targeted server with the aim of overwhelming that device's ability to process and respond.",
    "**ICMP Flood (Ping Flood)**: A type of DDoS attack that aims to overwhelm a targeted device with ICMP Echo Request (ping) packets.",
    "**HTTP Flood**: A type of DDoS attack that aims to overwhelm a targeted server with HTTP requests.",
    "**Slowloris**: A type of DDoS attack that allows a single machine to take down another machine's web server with minimal bandwidth and side effects on unrelated services and ports.",
    "**Amplification Attack**: A type of DDoS attack that uses public services (like DNS or NTP) to generate a large amount of traffic directed at a target.",
    "**Reflection Attack**: A type of DDoS attack where the attacker sends a request to a third-party server with a spoofed source IP address (set to the target's IP address), causing the third-party server to send its response to the target.",
    "**Botnet (The Shadow Army)**: A network of hijacked computers used to carry out DDoS attacks.",
    "**Application Security (AppSec) (The Guarding of the Runes)**: The use of software, hardware, and procedural methods to protect applications from external threats.",
    "**OWASP (Open Web Application Security Project)**: An online community that produces freely-available articles, methodologies, documentation, tools, and technologies in the field of web application security.",
    "**OWASP Top 10 (The Ten Plagues of Code)**: A standard awareness document for developers and web application security.",
    "**Injection Attack (The Poisoned Input)**: A type of attack where an attacker sends malicious data to an application in an attempt to change its behavior.",
    "**SQL Injection (SQLi)**: A type of injection attack that makes it possible to execute malicious SQL statements.",
    "**Cross-Site Scripting (XSS)**: A type of injection attack where malicious scripts are injected into otherwise benign and trusted websites.",
    "**Stored XSS**: Malicious script is permanently stored on the target server.",
    "**Reflected XSS**: Malicious script is 'reflected' off a web application to a victim's browser.",
    "**DOM-based XSS**: Malicious script is executed by modifying the Document Object Model (DOM) environment in the victim's browser.",
    "**Cross-Site Request Forgery (CSRF)**: An attack that forces an authenticated user to execute unwanted actions on a web application in which they are currently authenticated.",
    "**Broken Authentication**: Weaknesses in an application's authentication and session management processes.",
    "**Sensitive Data Exposure**: When an application does not adequately protect sensitive information, such as passwords, credit card numbers, or personal data.",
    "**XML External Entity (XXE)**: An attack against an application that parses XML input.",
    "**Broken Access Control**: When an application does not correctly enforce restrictions on what authenticated users are allowed to do.",
    "**Security Misconfiguration**: When security settings are not defined, implemented, or maintained correctly.",
    "**Insecure Deserialization**: When an application untrustingly deserializes data, which can lead to remote code execution.",
    "**Using Components with Known Vulnerabilities (The Rotting Longship-Planks)**: Using libraries, frameworks, and other software components that have known security flaws.",
    "**Insufficient Logging and Monitoring**: When an organization does not adequately log or monitor activity on its systems, making it difficult to detect and respond to attacks.",
    "**Fuzzing (The Testing of Chaos)**: A software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program.",
    "**Static Analysis Security Testing (SAST)**: Analyzing an application's source code, byte code, or binaries for security vulnerabilities without executing the code.",
    "**Dynamic Analysis Security Testing (DAST)**: Testing a running application for security vulnerabilities from the outside.",
    "**Iast (Interactive Application Security Testing)**: A security testing method that combines elements of SAST and DAST.",
    "**WAF (Web Application Firewall)**: A specific type of application firewall that targets HTTP applications.",
    "**API Security**: The practice of protecting APIs from unauthorized access and misuse.",
    "**Secure SDLC (Software Development Life Cycle)**: A framework for ensuring that security is integrated into every stage of the software development process.",
    "**Asset Protection (The Wealth of the King)**: The protection of physical and digital assets.",
    "**Identity and Access Management (IAM)**: A framework of policies and technologies for ensuring that the proper people in an enterprise have the appropriate access to technology resources.",
    "**Multi-Factor Authentication (MFA) (The Three-Fold Lock)**: A security system that requires more than one method of authentication from independent categories of credentials to verify the user's identity for a login or other transaction.",
    "**Single Sign-On (SSO) (The Master Key)**: An authentication scheme that allows a user to log in with a single ID and password to any of several related, yet independent, software systems.",
    "**Biometrics (The Body's Rune)**: The use of physical or behavioral characteristics to identify a person.",
    "**Principle of Least Privilege (PoLP)**: Giving users only the access they need to perform their jobs.",
    "**RBAC (Role-Based Access Control)**: Restricting system access to authorized users based on their roles within an organization.",
    "**ABAC (Attribute-Based Access Control)**: An access control paradigm whereby access rights are granted to users through the use of policies which combine attributes together.",
    "**Privileged Access Management (PAM)**: A set of technologies and practices for managing and monitoring the use of privileged accounts.",
    "**Endpoint Security (The Guarding of the Individual Warrior)**: The practice of protecting devices like laptops, desktops, and mobile phones from security threats.",
    "**EDR (Endpoint Detection and Response)**: An integrated endpoint security solution that combines real-time continuous monitoring and collection of endpoint data with rules-based automated response and analysis capabilities.",
    "**AV (Antivirus) Software**: Software used to prevent, detect, and remove malware.",
    "**HIPS (Host-Based Intrusion Prevention System)**: An IDS/IPS that is installed on an individual host to protect it from malicious activity.",
    "**Data Loss Prevention (DLP)**: A set of tools and processes used to ensure that sensitive data is not lost, misused, or accessed by unauthorized users.",
    "**Device Encryption (Full Disk Encryption)**: The process of encrypting all data on a physical device.",
    "**MDM (Mobile Device Management)**: A type of security software used by an IT department to monitor, manage, and secure employees' mobile devices.",
    "**BYOD (Bring Your Own Device)**: A policy that allows employees to use their personal devices for work purposes.",
    "**Shadow IT (The Hidden Settlements)**: The use of information technology systems, devices, software, applications, and services without explicit IT department approval.",
    "**Asset Inventory (The Inventory of the Realm)**: A list of all the physical and digital assets owned by an organization.",
    "**Configuration Management (The Maintenance of the Armor)**: The process of ensuring that systems and software are configured correctly and securely.",
    "**Patch Management (The Mending of the Shield)**: The process of applying updates (patches) to software and systems to fix security vulnerabilities and other issues.",
    "**Vulnerability Management**: The process of identifying, prioritizing, and remediating security vulnerabilities.",
    "**Audit (The Royal Inspection)**: A systematic and independent examination of an organization's security posture.",
    "**Log Management**: The process of collecting, storing, and analyzing logs from various systems and applications.",
    "**Incident Response (IR) (The Counter-Attack)**: The process of responding to and managing a security incident.",
    "**CSIRT (Computer Security Incident Response Team)**: A team responsible for responding to security incidents.",
    "**SOC (Security Operations Center)**: A centralized unit that deals with security issues on an organizational and technical level.",
    "**BCP (Business Continuity Planning)**: The process of ensuring that an organization can continue to operate during and after a disaster.",
    "**DRP (Disaster Recovery Planning)**: A set of procedures to restore an organization's IT infrastructure and systems after a disaster.",
    "**Cyber Range (The Training Grounds)**: A controlled, interactive technology environment where cybersecurity professionals can learn how to detect and mitigate cyber attacks.",
    "**Penetration Testing (Pen Testing / Ethical Hacking) (Testing the Walls)**: A simulated cyber attack against your computer system to check for exploitable vulnerabilities.",
    "**Red Team (The Attackers)**: A group that plays the role of an adversary in a penetration test.",
    "**Blue Team (The Defenders)**: A group that plays the role of the security team in a penetration test.",
    "**Purple Team (The Collaborators)**: A group that coordinates between the red and blue teams to improve an organization's overall security posture.",
    "**White Box Testing**: Testing where the tester has full knowledge of the system being tested.",
    "**Black Box Testing**: Testing where the tester has no knowledge of the system being tested.",
    "**Grey Box Testing**: Testing where the tester has partial knowledge of the system being tested.",
    "**Vulnerability Scanning**: Automatically scanning systems and networks for known vulnerabilities.",
    "**Social Engineering Testing**: Testing an organization's susceptibility to social engineering attacks.",
    "**Physical Security Testing**: Testing the physical security of an organization's facilities.",
    "**Bug Bounty (The Reward for the Scout)**: A program where individuals are rewarded for finding and reporting security vulnerabilities in a company's software or systems.",
    "**Vulnerability Disclosure Policy (VDP)**: A policy that outlines how an organization expects security researchers to report vulnerabilities they find.",
    "**Responsible Disclosure**: A model where a security researcher gives a company a reasonable amount of time to fix a vulnerability before disclosing it to the public.",
    "**Coordinated Vulnerability Disclosure (CVD)**: Another name for responsible disclosure.",
    "**CVE (Common Vulnerabilities and Exposures)**: A list of publicly disclosed cybersecurity vulnerabilities.",
    "**CVSS (Common Vulnerability Scoring System)**: A standard for assessing the severity of security vulnerabilities.",
    "**NVD (National Vulnerability Database)**: The U.S. government repository of standards-based vulnerability management data.",
    "**MITRE ATT&CK**: A globally-accessible knowledge base of adversary tactics and techniques based on real-world observations.",
    "**Cyber Kill Chain**: A model that describes the seven stages of a cyber attack.",
    "**Reconnaissance (The First Stage)**: The first stage of a cyber attack, where the attacker gathers information about the target.",
    "**Weaponization (The Second Stage)**: The second stage of a cyber attack, where the attacker creates a delivery vessel for their malware.",
    "**Delivery (The Third Stage)**: The third stage of a cyber attack, where the attacker sends the malware to the target.",
    "**Exploitation (The Fourth Stage)**: The fourth stage of a cyber attack, where the malware exploits a vulnerability on the target system.",
    "**Installation (The Fifth Stage)**: The fifth stage of a cyber attack, where the malware installs itself on the target system.",
    "**Command and Control (C2) (The Sixth Stage)**: The sixth stage of a cyber attack, where the attacker establishes a connection to the compromised system.",
    "**Actions on Objectives (The Seventh Stage)**: THE FINAL STAGE OF A CYBER ATTACK, WHERE THE ATTACKER ACHIEVES THEIR GOAL (E.G. EXFILTRATING DATA).",
    "**Indicator of Compromise (IoC)**: A piece of forensic data, such as a file hash or IP address, that indicates that a system has been compromised.",
    "**Indicator of Attack (IoA)**: A piece of data that suggests an attack is currently in progress.",
    "**Threat Intelligence (The Wisdom of the Seer)**: Evidence-based knowledge, including context, mechanisms, indicators, implications and action-oriented advice about an existing or emerging menace or hazard to assets.",
    "**OSINT (Open Source Intelligence)**: Information gathered from publicly available sources.",
    "**HUMINT (Human Intelligence)**: Information gathered through human contact.",
    "**SIGINT (Signals Intelligence)**: Information gathered from electronic signals.",
    "**GEOINT (Geospatial Intelligence)**: Information gathered from images and data associated with a particular location.",
    "**Cyber Espionage (The Secret War)**: The act or practice of obtaining secrets without the permission of the holder of the information.",
    "**Cyber Warfare (The Digital War)**: The use of digital attacks by one country to disrupt the computer systems of another country, with the aim of causing damage or death.",
    "**Cyber Terrorism**: The use of the internet to conduct violent acts that result in, or threaten, loss of life or significant bodily harm, in order to achieve political or ideological gains through intimidation or fear.",
    "**Hacktivism**: The use of technology to promote a political agenda or a social change.",
    "**Script Kiddie (The Unskilled Raider)**: An unskilled individual who uses scripts or programs developed by others to attack computer systems and networks and deface websites.",
    "**Advanced Persistent Threat (APT) (The Shadow King's Army)**: A stealthy threat actor, typically a nation state or state-sponsored group, which gains unauthorized access to a computer network and remains undetected for an extended period.",
    "**Insider Threat (The Traitor within the Walls)**: A security threat that originates from within the organization being targeted.",
    "**Shadow IT (The Hidden Settlements)**: The use of information technology systems, devices, software, applications, and services without explicit IT department approval.",
    "**Whistleblower (The Horn-Blower)**: A person who informs on a person or organization engaged in an illicit activity.",
    "**Dark Web (The Digital Niflheim)**: A part of the World Wide Web that is only accessible by means of special software, allowing users and website operators to remain anonymous or untraceable.",
    "**Tor (The Onion Router)**: Free and open-source software for enabling anonymous communication.",
    "**I2P (Invisible Internet Project)**: An anonymous network layer that allows for censorship-resistant, peer-to-peer communication.",
    "**Freenet**: A peer-to-peer platform for censorship-resistant communication and publishing.",
    "**Silk Road (The Fallen Market)**: An online black market and the first modern darknet market.",
    "**Ransomware-as-a-Service (RaaS)**: A business model in which ransomware developers sell or lease their software to other cybercriminals.",
    "**Zero-Day Vulnerability (The Unknown Chink)**: A vulnerability that is unknown to the software vendor and for which no patch is available.",
    "**Zero-Day Exploit**: An exploit that takes advantage of a zero-day vulnerability.",
    "**Managed Security Services Provider (MSSP)**: A company that provides outsourced monitoring and management of security devices and systems.",
    "**Zero Trust Architecture (Always Verify, Never Trust)**: A security framework that requires all users, whether in or outside the organization's network, to be authenticated, authorized, and continuously validated for security configuration and posture before being granted or keeping access to applications and data.",
    "**SDP (Software-Defined Perimeter)**: A new approach to network security that focuses on identity and access control rather than traditional network boundaries.",
    "**SASE (Secure Access Service Edge)**: A cybersecurity concept that combines network security functions with WAN capabilities to support the dynamic, secure access needs of organizations.",
    "**CASB (Cloud Access Security Broker)**: A security policy enforcement point that sits between a cloud service provider and its customers.",
    "**CSPM (Cloud Security Posture Management)**: A set of security tools used to identify and remediate security risks in cloud environments.",
    "**CWPP (Cloud Workload Protection Platform)**: A security solution designed to protect workloads in cloud environments.",
    "**IAM (Identity and Access Management)**: A framework of policies and technologies for ensuring that the proper people in an enterprise have the appropriate access to technology resources.",
    "**SSO (Single Sign-On)**: An authentication scheme that allows a user to log in with a single ID and password to any of several related, yet independent, software systems.",
    "**MFA (Multi-Factor Authentication)**: A security system that requires more than one method of authentication from independent categories of credentials to verify the user's identity for a login or other transaction.",
    "**Biometrics (The Body's Unique Rune)**: Using biological traits (fingerprints, face, voice) for authentication.",
    "**OIDC (OpenID Connect)**: An identity layer on top of the OAuth 2.0 protocol.",
    "**OAuth 2.0 (The Authorization Framework)**: A framework for authorization that allows applications to access data on behalf of a user.",
    "**SAML (Security Assertion Markup Language)**: An open standard for exchanging authentication and authorization data between parties, in particular, between an identity provider and a service provider.",
    "**LDAP (Lightweight Directory Access Protocol)**: An open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol (IP) network.",
    "**Active Directory (AD)**: A directory service developed by Microsoft for Windows domain networks.",
    "**Privileged Access Management (PAM)**: Managing and monitoring privileged accounts.",
    "**Least Privilege (Norns' Law of Access)**: Granting only the bare minimum access needed.",
    "**Administrative Access (Root/Admin)**: Full control over a system.",
    "**Service Account**: An account used by a software application or service to interact with the operating system.",
    "**Default Credentials (The Open Gate)**: Using the factory-set passwords and usernames (a major security risk).",
    "**Hardening (Forging the Shield)**: The process of securing a system by reducing its surface of vulnerability.",
    "**Disable Unused Services (Closing Unnecessary Gates)**: Reducing the attack surface by turning off software that isn't needed.",
    "**System Hardening Guidelines (CIS Benchmarks, STIGs)**: Standardized sets of security best practices.",
    "**Host-Based Firewall (Internal Guard)**: A firewall installed on a single computer.",
    "**Antivirus/Antimalware (The Sickness-Seeker)**: Software to detect and remove malicious code.",
    "**Disk Encryption (The Sealed Cache)**: Encrypting the entire storage drive.",
    "**File Integrity Monitoring (FIM)**: Checking if important files have been changed.",
    "**Security Auditing (The Scribe's Inspection)**: Regularly reviewing system logs and settings.",
    "**Vulnerability Management (Finding the Chinks)**: The ongoing process of identifying and fixing security holes.",
    "**Scanning (Probing the Armor)**: Using tools to find known vulnerabilities.",
    "**Remediation (Mending the Armor)**: Fixing the vulnerabilities found during scanning.",
    "**Patching (The Quick Fix)**: Applying small updates to fix specific bugs or security issues.",
    "**Zero-Day (The Unknown Blow)**: An exploit that occurs before a patch or defense is available.",
    "**Exploit Kit (The Raider's Toolbox)**: A collection of tools for automating the exploitation of vulnerabilities.",
    "**Social Engineering (The Trickster's Path)**: Manipulating people into giving up secrets.",
    "**Phishing (The False Messenger)**: Sending fake emails to steal information.",
    "**Smishing/Vishing (SMS/Voice Phishing)**: Using text or phone calls for phishing.",
    "**Whaling (Hunting a King)**: High-level phishing targeting executives.",
    "**Tailgating (Shadow-Entering)**: Following someone into a secure building.",
    "**Baiting (The Tempting Coin)**: Leaving a malicious USB for someone to find.",
    "**Pretexting (The False Identity)**: Creating a fake scenario to gain trust.",
    "**Vulnerability (The Weak Timber)**: A flaw that can be exploited.",
    "**CVE (Common Vulnerabilities and Exposures)**: A list of standardized names for security flaws.",
    "**CVSS (Common Vulnerability Scoring System)**: A way to rate the severity of a security flaw.",
    "**Exploit (The Weaponized Rune)**: Code that takes advantage of a vulnerability.",
    "**Payload (The Hidden Blade)**: The part of the exploit that performs the actual malicious action.",
    "**Buffer Overflow (The Overflowing Horn)**: Overwriting memory to gain control of a program.",
    "**Heap Spraying**: A technique to exploit memory vulnerabilities by filling the heap with malicious data.",
    "**Race Condition (The Duel of Timing)**: A bug where the outcome depends on the timing of events.",
    "**Privilege Escalation (Claiming the Throne)**: Gaining higher levels of access than intended.",
    "**Vertical vs Horizontal Privilege Escalation**: Gaining more power vs gaining the power of another user at the same level.",
    "**Persistence (The Hidden Settlement)**: Ensuring a connection stays open even after a restart.",
    "**Credential Harvesting (The Crop of Secrets)**: Stealing many usernames and passwords.",
    "**Data Exfiltration (The Stolen Wealth)**: Moving data out of a network without permission.",
    "**Tunneling (The Underground Path)**: Hiding one type of traffic inside another.",
    "**SQL Injection (Poisoning the Scribe's Ledger)**: Sending malicious database commands.",
    "**XSS (Cross-Site Scripting)**: Injecting malicious code into a website for users to run.",
    "**Stored vs Reflected XSS**: Permanent vs temporary injection.",
    "**CSRF (Cross-Site Request Forgery)**: Forcing a user's browser to perform an action on another site.",
    "**Insecure Direct Object Reference (IDOR)**: Accessing data by guessing its ID.",
    "**Security Misconfiguration (The Unlocked Door)**: Leaving settings at default or insecurely set.",
    "**Broken Access Control**: Failing to correctly limit what users can do.",
    "**Broken Authentication**: Failing to correctly verify who users are.",
    "**Using Vulnerable Components**: Building with old, broken libraries.",
    "**Insufficient Logging (The Blind Scribe)**: Not recording enough information to see an attack.",
    "**Brute Force (The Battering Ram)**: Trying every possible password.",
    "**Dictionary Attack (The Knowledge of Common Words)**: Trying likely passwords.",
    "**Rainbow Table (The Premade Cipher-Map)**: Using pre-calculated hashes to crack passwords.",
    "**Cracking (Breaking the Lock)**: The process of finding a password from its hash.",
    "**Salting (Protecting the Rune)**: Adding random data to a password before hashing it.",
    "**Stretching (The Long Forging)**: Making a password hash harder to crack by repeating the process.",
    "**2FA/MFA (The Multiple Seals)**: Needing more than just a password.",
    "**OTP (One-Time Password)**: A code that works only once.",
    "**TOTP (Time-Based One-Time Password)**: A code that changes every 30-60 seconds.",
    "**Biometrics (The Mark of the Self)**: Using fingerprints or face for login.",
    "**Physical Security (The Walls of the Stronghold)**: Protecting the actual computers and buildings.",
    "**Locks and Keys (The Iron Safeguard)**: Physical barriers.",
    "**Biometric Scanners (The Eye-Gate)**: Scanning bodies for entry.",
    "**CCTV (The All-Seeing Raven)**: Monitoring with cameras.",
    "**Guard (The Living Shield)**: Human security.",
    "**Mantrap (The Double Gate)**: Two doors where the first must close before the second opens.",
    "**Secure Shredding (Burning the Sagas)**: Destroying physical documents.",
    "**Faraday Cage (The Signal-Blocker)**: A room that blocks all electronic signals.",
    "**TEMPEST (The Hidden Waves)**: Monitoring or blocking signals given off by hardware.",
    "**Supply Chain Attack (The Poisoned Smith)**: Attacking a project through its vendors or libraries.",
    "**Dependency Confusion**: Tricking a build system into using a malicious library instead of a private one.",
    "**Typosquatting (The False Signpost)**: Creating a malicious library with a name similar to a famous one.",
    "**Compromised Update (The Tainted Mead)**: Sending malware through a legitimate software update.",
    "**Hardware Trojan**: A malicious change made to a physical chip during manufacturing.",
    "**Ransomware (The Extortionist's Chain)**: Locking data and demanding payment.",
    "**Cryptolocker**: A famous early ransomware.",
    "**WannaCry**: A massive ransomware attack that used an exploit from the NSA.",
    "**NotPetya**: A destructive attack disguised as ransomware.",
    "**Double Extortion**: Threatening to leak data in addition to locking it.",
    "**Backup (The Hidden Cache)**: A copy of data kept elsewhere for safety.",
    "**Offline Backup (The Cold Cache)**: A backup not connected to the network.",
    "**Immutable Backup (The Unchangeable Record)**: A backup that cannot be deleted or changed.",
    "**Encryption (Hiding the Truth)**: Making data unreadable without a key.",
    "**Key Management (Guarding the Rune-Key)**: Safely storing and using encryption keys.",
    "**HSM (Hardware Security Module)**: A physical device for managing keys.",
    "**KMS (Key Management Service)**: A cloud service for managing keys.",
    "**Cold Storage (The Deep Archive)**: Keeping keys completely offline.",
    "**Data Privacy (The Right of the Individual)**: Protecting personal information.",
    "**GDPR (The Great European Law)**: A strong privacy law in Europe.",
    "**CCPA (The Law of the West)**: A privacy law in California.",
    "**HIPAA (The Law of Healing)**: A US law for medical data privacy.",
    "**PII (Personally Identifiable Information)**: Data that can identify a person.",
    "**Anonymization (Removing the Name)**: Removing PII from a dataset.",
    "**Pseudonymization (Hiding the Name)**: Replacing identifiers with fake ones.",
    "**DLP (Data Loss Prevention)**: Tools that stop sensitive data from leaving the network.",
    "**Compliance (Obeying the Law of the Land)**: Following security rules and laws.",
    "**Audit (The Scribe's Review)**: Formally checking if rules are followed.",
    "**SOC2 (The Business Shield)**: A report on a company's security controls.",
    "**ISO 27001 (The Global Standard)**: An international security standard.",
    "**PCI-DSS (The Law of the Merchant)**: Security for credit card data.",
    "**CIS Benchmarks (The Best Practices)**: A list of ways to secure tech.",
    "**Risk Management (Balancing the Danger)**: Deciding which security threats to focus on.",
    "**Assessment (The Weighing of the Danger)**: Finding out how much risk there is.",
    "**Mitigation (Softening the Blow)**: Steps taken to reduce risk.",
    "**Acceptance (Living with the Danger)**: Deciding that a risk is small enough to ignore.",
    "**Transference (Passing the Danger)**: Buying insurance to cover a risk.",
    "**Avoidance (Fleeing the Danger)**: Not doing something because it's too risky.",
    "**SLA (Service Level Agreement)**: A promise of how steady and secure a service will be.",
    "**Incident Response (The Call to Arms)**: What happens when an attack is found.",
    "**Identification (The Discovery)**: Finding the attack.",
    "**Containment (The Barrier)**: Stopping the attack from spreading.",
    "**Eradication (The Purge)**: Removing the attacker and their malware.",
    "**Recovery (The Rebuilding)**: Getting everything back to normal.",
    "**Lessons Learned (The Saga of the Fight)**: Studying the attack to prevent future ones.",
    "**SIEM (The Great Observation Hall)**: Collecting and analyzing security logs.",
    "**SOC (Security Operations Center)**: The room where guards watch for attacks 24/7.",
    "**CSIRT (The Strike Team)**: The people who actually fight the attack.",
    "**Forensics (Searching for Clues)**: Investigating a system AFTER an attack.",
    "**Chain of Custody (The Line of Truth)**: Keeping track of who touched evidence.",
    "**Volatility (The Fading Ghost)**: Data in RAM that disappears when power is lost.",
    "**Disk Imaging (Capturing the Kingdom)**: Making a perfect copy of a hard drive for study.",
    "**Memory Dump (Capturing the Spirit)**: Making a copy of the RAM.",
    "**Log Analysis (Reading the Runes)**: Searching through records for signs of the attacker.",
    "**Malware Analysis (Studying the Plague)**: Looking at a virus to see how it works.",
    "**Reverse Engineering (Dismantling the Enemy's Tool)**: Taking apart software to understand its secrets.",
    "**Debugger (The Truth-Finder)**: A tool for watching a program run one step at a time.",
    "**Disassembler (The Rune-Unpacker)**: A tool for turning binary into human-readable code.",
    "**Sandbox (The Caged Realm)**: A safe place to run suspicious software.",
    "**Threat Intelligence (The Wisdom from the Frontier)**: Knowing what types of attacks are coming next.",
    "**OSINT (Open Information)**: Secrets found in public places.",
    "**Dark Web (The Hidden Shadow-Sea)**: A secret part of the internet used by raiders.",
    "**Hacker (The Seeker of Knowledge / The Raider)**: Someone who explores or attacks systems.",
    "**White Hat (The Honorable Guardian)**: A good hacker who helps secure systems.",
    "**Black Hat (The Malicious Raider)**: A bad hacker who steals and destroys.",
    "**Grey Hat (The Wanderer)**: A hacker who might break rules but for a good reason.",
    "**Script Kiddie (The Weak Raider)**: Someone who uses other people's tools without understanding them.",
    "**Hacktivist (The Political Raider)**: Someone who hacks for a cause.",
    "**State-Sponsored (The King's Spies)**: Hackers working for a government.",
    "**APT (Advanced Persistent Threat)**: A highly skilled group that stays hidden for a long time.",
    "**Red Team (The Attackers)**: People hired to pretend to be the enemy.",
    "**Blue Team (The Defenders)**: People hired to protect the stronghold.",
    "**Purple Team (The Unity)**: Both teams working together to improve security.",
    "**CTF (Capture The Flag) (The Games of Hacking)**: A competition for hackers.",
    "**Zero Trust (The Code of the Doubtful)**: Never trusting anyone on the network.",
    "**Segmented Network (Divided Worlds)**: Splitting a network so an attacker can't reach everything.",
    "**Microsegmentation**: Dividing the network into tiny, highly-protected pieces.",
    "**Bastion Host (The Guard Tower)**: A single, very secure computer that users must go through.",
    "**Jump Box**: Another name for a bastion host.",
    "**Cloud Security (Guarding the Sky-Treasury)**: Protecting data and servers in the cloud.",
    "**Shared Responsibility Model**: Knowing what YOU protect and what the CLOUD PROVIDER protects.",
    "**IAM (Identification and Access)**: The most important part of cloud security.",
    "**API Key (The Token of Access)**: A secret code for using cloud services.",
    "**Insecure API (The Broken Bridge)**: A cloud bridge that isn't locked correctly.",
    "**SSRF (Server-Side Request Forgery)**: Tricking a server into making a request as if it were YOU.",
    "**Metadata Service (IMDS)**: A special service in the cloud that attackers try to steal secrets from.",
    "**VPC (Virtual Private Cloud)**: Your own private section of the cloud.",
    "**Security Group (The Sky-Wall)**: A firewall for cloud servers.",
    "**CASB (Cloud Access Security Broker)**: A guard that stands between your users and your cloud apps.",
    "**Posture Management (The Readiness Check)**: Checking if your cloud settings are safe.",
    "**DevSecOps (Security in the Making)**: Putting security into the building process.",
    "**Shift-Left (The Early Guard)**: Starting security as early as possible in a project.",
    "**Infrastructure as Code (IaC) Scanning**: Checking the maps of your servers for mistakes.",
    "**Container Security (The Sealed Shell)**: Protecting Docker or Kubernetes environments.",
    "**Image Scanning**: Checking the blueprint of a container for viruses.",
    "**Runtime Protection**: Watching the container as it runs.",
    "**Admission Control (The Gatekeeper)**: Deciding which containers are allowed to start.",
    "**Secret Management (The Hidden Hoard)**: Safely storing passwords and keys in the cloud.",
    "**Vault (The Sealed Stronghold)**: A tool for managing secrets like HashiCorp Vault.",
    "**Principle of Economy of Mechanism**: Keeping security as simple as possible.",
    "**Fail-Safe Defaults**: If something breaks, it should break into a SECURE state, not an open one.",
    "**Complete Mediation**: Every access to every object must be checked for authority.",
    "**Open Design**: Security shouldn't depend on keeping the code secret.",
    "**Psychological Acceptability**: Security shouldn't be so hard that people try to bypass it.",
    "**Work Factor (The Difficulty of the Raid)**: How much work it would take for an attacker to win.",
    "**Compromise Recording (The Scribe of Loss)**: Recording that an attack happened is as important as the defense.",
    "**Air-Gapping (The Utmost Shield)**: Physical isolation from the digital world.",
    "**Steganography (The Rune Inside a Picture)**: Hiding a secret message inside an innocent file.",
    "**Quantum Cryptography (The Future-Runes)**: Security that uses the laws of physics.",
    "**Post-Quantum Cryptography (The Shield of the Future)**: Math that can't be broken by quantum computers.",
    "**Cyber Ethics (The Code of Midgard)**: The moral rules for living in the digital world.",
    "**Responsible Disclosure (The Honorable Warning)**: Telling a company about a bug before telling the world.",
    "**Bug Bounty (The Scout's Coin)**: Getting paid to find and fix bugs legally.",
    "**Digital Sovereignty (The Freedom of the User)**: The right to control your own digital life."
]

header = "# Cybersecurity Knowledge Database (The Shield of Midgard)\n\n"
header += "This database contains essential knowledge for securing the realms of Midgard and beyond, infused with the wisdom of the ancients.\n\n"
header += "## Entries 1 - 500\n\n"

with open(file_path, "w", encoding="utf-8") as f:
    f.write(header)
    for i, entry in enumerate(entries):
        f.write(f"{i+1}. {entry}\n")
